import {
  runBoundedServiceRoleRpc,
  type SupabaseRpcClient,
} from "@/lib/db/bounded-supabase-rpc";
import {
  runGovernedSupabaseRpc,
  type SupabaseRpcOperationFamily,
} from "@/lib/db/supabase-rpc-runtime-governor";

export const SUPABASE_RPC_OPERATIONS = {
  stripe_webhook_event_claim: { rpcName: "velmere_claim_stripe_webhook_event", deadlineMs: 3_000, family: "payments" },
  payment_event_watermark_apply: { rpcName: "velmere_apply_payment_event_watermark", deadlineMs: 3_000, family: "payments" },
  stripe_webhook_effect_claim: { rpcName: "velmere_claim_stripe_webhook_effect", deadlineMs: 3_000, family: "payments" },
  stripe_webhook_effect_complete: { rpcName: "velmere_complete_stripe_webhook_effect", deadlineMs: 4_000, family: "payments" },
  stripe_webhook_effect_fail: { rpcName: "velmere_fail_stripe_webhook_effect", deadlineMs: 4_000, family: "payments" },
  stripe_webhook_effect_dead_letter: { rpcName: "velmere_dead_letter_stripe_webhook_effect", deadlineMs: 4_000, family: "payments" },
  commerce_paid_fulfilment_enqueue: { rpcName: "velmere_commit_commerce_paid_and_enqueue_fulfilment", deadlineMs: 5_000, family: "payments" },
  commerce_fulfilment_outbox_claim: { rpcName: "velmere_claim_commerce_fulfilment_outbox", deadlineMs: 5_000, family: "fulfilment" },
  commerce_fulfilment_outbox_complete: { rpcName: "velmere_complete_commerce_fulfilment_outbox", deadlineMs: 5_000, family: "fulfilment" },
  commerce_fulfilment_outbox_fail: { rpcName: "velmere_fail_commerce_fulfilment_outbox", deadlineMs: 5_000, family: "fulfilment" },
  commerce_fulfilment_outbox_release: { rpcName: "velmere_release_commerce_fulfilment_outbox", deadlineMs: 4_000, family: "fulfilment" },
  fulfilment_outbox_worker_claim: { rpcName: "velmere_claim_fulfilment_incident_outbox_worker", deadlineMs: 4_000, family: "fulfilment" },
  fulfilment_outbox_event_complete: { rpcName: "velmere_complete_fulfilment_incident_outbox_event", deadlineMs: 4_000, family: "fulfilment" },
  fulfilment_outbox_event_release: { rpcName: "velmere_release_fulfilment_incident_outbox_event", deadlineMs: 4_000, family: "fulfilment" },
  fulfilment_outbox_event_fail: { rpcName: "velmere_fail_fulfilment_incident_outbox_event", deadlineMs: 4_000, family: "fulfilment" },
  fulfilment_outbox_worker_finish: { rpcName: "velmere_finish_fulfilment_incident_outbox_worker", deadlineMs: 4_000, family: "fulfilment" },
  fulfilment_incident_resolve: { rpcName: "velmere_resolve_fulfilment_incident", deadlineMs: 5_000, family: "fulfilment" },
  audit_pdf_token_claim: { rpcName: "velmere_claim_audit_pdf_token", deadlineMs: 4_000, family: "audit" },
  audit_pdf_token_finalize: { rpcName: "velmere_finalize_audit_pdf_token", deadlineMs: 4_000, family: "audit" },
  audit_pdf_token_reservation_fail: { rpcName: "velmere_fail_audit_pdf_token_reservation", deadlineMs: 4_000, family: "audit" },
  durable_computation_claim: { rpcName: "velmere_claim_durable_computation", deadlineMs: 5_000, family: "audit" },
  durable_computation_complete: { rpcName: "velmere_complete_durable_computation", deadlineMs: 5_000, family: "audit" },
  durable_computation_fail: { rpcName: "velmere_fail_durable_computation", deadlineMs: 5_000, family: "audit" },
  durable_computation_maintenance_claim: { rpcName: "velmere_claim_durable_computation_maintenance", deadlineMs: 4_000, family: "audit" },
  durable_computation_metrics: { rpcName: "velmere_get_durable_computation_metrics", deadlineMs: 4_000, family: "audit" },
  durable_computation_cleanup: { rpcName: "velmere_cleanup_durable_computations", deadlineMs: 5_000, family: "audit" },
  durable_computation_alert_record: { rpcName: "velmere_record_durable_computation_alert", deadlineMs: 3_000, family: "audit" },
  durable_computation_maintenance_finish: { rpcName: "velmere_finish_durable_computation_maintenance", deadlineMs: 4_000, family: "audit" },
  durable_computation_dead_letter_requeue: { rpcName: "velmere_requeue_durable_computation_dead_letter", deadlineMs: 4_000, family: "audit" },
  durable_computation_worker_claim_batch: { rpcName: "velmere_claim_durable_computation_worker_batch", deadlineMs: 5_000, family: "audit" },
  durable_computation_worker_claim_batch_fair: { rpcName: "velmere_claim_durable_computation_worker_batch_fair", deadlineMs: 5_000, family: "audit" },
  durable_computation_worker_claim_batch_budgeted: { rpcName: "velmere_claim_durable_computation_worker_batch_budgeted", deadlineMs: 5_000, family: "audit" },
  durable_computation_worker_release_claims_budget: { rpcName: "velmere_release_durable_computation_worker_claims_budget", deadlineMs: 4_000, family: "audit" },
  durable_computation_worker_heartbeat: { rpcName: "velmere_heartbeat_durable_computation_worker", deadlineMs: 3_000, family: "audit" },
  durable_computation_worker_heartbeat_owned: { rpcName: "velmere_heartbeat_durable_computation_worker_owned", deadlineMs: 3_000, family: "audit" },
  durable_computation_cycle_receipt_record: { rpcName: "velmere_record_durable_computation_cycle_receipt", deadlineMs: 4_000, family: "audit" },
  durable_computation_alert_claim_batch: { rpcName: "velmere_claim_durable_computation_alerts", deadlineMs: 4_000, family: "audit" },
  durable_computation_alert_settle: { rpcName: "velmere_settle_durable_computation_alert", deadlineMs: 4_000, family: "audit" },
  durable_computation_staging_probe: { rpcName: "velmere_probe_durable_computation_capabilities", deadlineMs: 5_000, family: "audit" },
  durable_computation_deployment_promote: { rpcName: "velmere_promote_durable_computation_deployment", deadlineMs: 5_000, family: "audit" },
  durable_computation_deployment_rollback: { rpcName: "velmere_rollback_durable_computation_deployment", deadlineMs: 5_000, family: "audit" },
  durable_computation_alert_reconcile: { rpcName: "velmere_reconcile_durable_computation_alert_outbox", deadlineMs: 4_000, family: "audit" },
  provider_reliability_lease_acquire: { rpcName: "velmere_acquire_provider_reliability_lease", deadlineMs: 3_000, family: "audit" },
  provider_reliability_lease_settle: { rpcName: "velmere_settle_provider_reliability_lease", deadlineMs: 3_000, family: "audit" },
  provider_observation_record: { rpcName: "velmere_record_provider_observation", deadlineMs: 4_000, family: "audit" },
  provider_observation_reconcile: { rpcName: "velmere_reconcile_provider_observations", deadlineMs: 5_000, family: "audit" },
  provider_observation_compact: { rpcName: "velmere_compact_provider_observations", deadlineMs: 5_000, family: "audit" },
  provider_observation_alert_record: { rpcName: "velmere_record_provider_observation_alert", deadlineMs: 4_000, family: "audit" },
  provider_observation_quarantine_reconcile: { rpcName: "velmere_reconcile_provider_observation_quarantine", deadlineMs: 5_000, family: "audit" },
  provider_observation_quarantine_action: { rpcName: "velmere_apply_provider_observation_quarantine_action", deadlineMs: 5_000, family: "audit" },
  provider_quality_incident_reconcile: { rpcName: "velmere_reconcile_provider_quality_incident", deadlineMs: 5_000, family: "audit" },
  provider_quality_incident_snapshot: { rpcName: "velmere_get_provider_quality_incident_snapshot", deadlineMs: 4_000, family: "audit" },
  provider_quality_incident_action: { rpcName: "velmere_apply_provider_quality_incident_action", deadlineMs: 5_000, family: "audit" },
  provider_quality_auto_rollback_context: { rpcName: "velmere_get_provider_quality_auto_rollback_context", deadlineMs: 4_000, family: "audit" },
  provider_quality_auto_rollback_execute: { rpcName: "velmere_execute_provider_quality_auto_rollback", deadlineMs: 5_000, family: "audit" },
  provider_quality_auto_rollback_verify: { rpcName: "velmere_verify_provider_quality_auto_rollback", deadlineMs: 5_000, family: "audit" },
  provider_quality_auto_rollback_status: { rpcName: "velmere_get_provider_quality_auto_rollback_status", deadlineMs: 4_000, family: "audit" },
  provider_quality_recovery_proof_record: { rpcName: "velmere_record_provider_quality_recovery_proof", deadlineMs: 5_000, family: "audit" },
  provider_quality_recovery_proof_verify: { rpcName: "velmere_verify_provider_quality_recovery_proof", deadlineMs: 5_000, family: "audit" },
  provider_quality_recovery_proof_status: { rpcName: "velmere_get_provider_quality_recovery_proof_status", deadlineMs: 4_000, family: "audit" },
  provider_recovery_smoke_receipt_record: { rpcName: "velmere_record_provider_recovery_smoke_receipt", deadlineMs: 5_000, family: "audit" },
  provider_recovery_smoke_receipt_status: { rpcName: "velmere_get_provider_recovery_smoke_receipt_status", deadlineMs: 4_000, family: "audit" },
  provider_recovery_release_certificate_record: { rpcName: "velmere_record_provider_recovery_release_certificate", deadlineMs: 5_000, family: "audit" },
  provider_recovery_release_certificate_verify: { rpcName: "velmere_verify_provider_recovery_release_certificate", deadlineMs: 5_000, family: "audit" },
  provider_recovery_release_certificate_status: { rpcName: "velmere_get_provider_recovery_release_certificate_status", deadlineMs: 4_000, family: "audit" },
  provider_recovery_release_bundle_record: { rpcName: "velmere_record_provider_recovery_release_bundle", deadlineMs: 5_000, family: "audit" },
  provider_recovery_release_bundle_verify: { rpcName: "velmere_verify_provider_recovery_release_bundle", deadlineMs: 5_000, family: "audit" },
  provider_recovery_release_bundle_status: { rpcName: "velmere_get_provider_recovery_release_bundle_status", deadlineMs: 4_000, family: "audit" },
  release_candidate_attestation_record: { rpcName: "velmere_record_release_candidate_attestation", deadlineMs: 5_000, family: "audit" },
  release_candidate_attestation_verify: { rpcName: "velmere_verify_release_candidate_attestation", deadlineMs: 5_000, family: "audit" },
  release_candidate_attestation_status: { rpcName: "velmere_get_release_candidate_attestation_status", deadlineMs: 4_000, family: "audit" },
  release_provenance_index_record: { rpcName: "velmere_record_release_provenance_index", deadlineMs: 5_000, family: "audit" },
  release_provenance_index_verify: { rpcName: "velmere_verify_release_provenance_index", deadlineMs: 5_000, family: "audit" },
  release_provenance_index_status: { rpcName: "velmere_get_release_provenance_index_status", deadlineMs: 4_000, family: "audit" },
  release_provenance_public_feed: { rpcName: "velmere_get_public_release_provenance_feed", deadlineMs: 4_000, family: "audit" },
  release_proof_package_record: { rpcName: "velmere_record_release_proof_package", deadlineMs: 5_000, family: "audit" },
  release_proof_package_verify: { rpcName: "velmere_verify_release_proof_package", deadlineMs: 5_000, family: "audit" },
  release_proof_package_status: { rpcName: "velmere_get_release_proof_package_status", deadlineMs: 4_000, family: "audit" },
  release_proof_package_public_feed: { rpcName: "velmere_get_public_release_proof_packages", deadlineMs: 5_000, family: "audit" },
  release_trust_checkpoint_record: { rpcName: "velmere_record_release_trust_checkpoint", deadlineMs: 5_000, family: "audit" },
  release_trust_checkpoint_verify: { rpcName: "velmere_verify_release_trust_checkpoint", deadlineMs: 5_000, family: "audit" },
  release_trust_checkpoint_status: { rpcName: "velmere_get_release_trust_checkpoint_status", deadlineMs: 4_000, family: "audit" },
  release_trust_checkpoint_public_feed: { rpcName: "velmere_get_public_release_trust_checkpoints", deadlineMs: 5_000, family: "audit" },
  release_trust_consistency_record: { rpcName: "velmere_record_release_trust_consistency_proof", deadlineMs: 5_000, family: "audit" },
  release_trust_consistency_verify: { rpcName: "velmere_verify_release_trust_consistency_proof", deadlineMs: 5_000, family: "audit" },
  release_trust_consistency_status: { rpcName: "velmere_get_release_trust_consistency_status", deadlineMs: 4_000, family: "audit" },
  release_trust_consistency_public_feed: { rpcName: "velmere_get_public_release_trust_consistency_proofs", deadlineMs: 5_000, family: "audit" },
  release_transparency_record: { rpcName: "velmere_record_release_transparency_entry", deadlineMs: 5_000, family: "audit" },
  release_transparency_verify: { rpcName: "velmere_verify_release_transparency_entry", deadlineMs: 5_000, family: "audit" },
  release_transparency_status: { rpcName: "velmere_get_release_transparency_entry_status", deadlineMs: 4_000, family: "audit" },
  release_transparency_public_feed: { rpcName: "velmere_get_public_release_transparency_entries", deadlineMs: 5_000, family: "audit" },
  release_transparency_checkpoint_record: { rpcName: "velmere_record_release_transparency_checkpoint", deadlineMs: 5_000, family: "audit" },
  release_transparency_checkpoint_verify: { rpcName: "velmere_verify_release_transparency_checkpoint", deadlineMs: 5_000, family: "audit" },
  release_transparency_checkpoint_status: { rpcName: "velmere_get_release_transparency_checkpoint_status", deadlineMs: 4_000, family: "audit" },
  release_transparency_checkpoint_public_feed: { rpcName: "velmere_get_public_release_transparency_checkpoints", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_record: { rpcName: "velmere_record_release_transparency_witness_quorum", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_verify: { rpcName: "velmere_verify_release_transparency_witness_quorum", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_status: { rpcName: "velmere_get_release_transparency_witness_quorum_status", deadlineMs: 4_000, family: "audit" },
  release_transparency_witness_public_feed: { rpcName: "velmere_get_public_release_transparency_witness_quorums", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_health_policy_apply: { rpcName: "velmere_apply_release_transparency_witness_health_policy", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_health_reconcile: { rpcName: "velmere_reconcile_release_transparency_witness_health", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_health_verify: { rpcName: "velmere_verify_release_transparency_witness_health", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_health_status: { rpcName: "velmere_get_release_transparency_witness_health_status", deadlineMs: 4_000, family: "audit" },
  release_transparency_witness_health_public_feed: { rpcName: "velmere_get_public_release_transparency_witness_health", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_health_recovery_apply: { rpcName: "velmere_apply_release_transparency_witness_health_recovery", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_health_recovery_verify: { rpcName: "velmere_verify_release_transparency_witness_health_recovery", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_health_recovery_status: { rpcName: "velmere_get_release_transparency_witness_health_recovery_status", deadlineMs: 4_000, family: "audit" },
  release_transparency_witness_health_recovery_public_feed: { rpcName: "velmere_get_public_release_transparency_witness_health_recoveries", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_rollback_resolution_record: { rpcName: "velmere_record_release_transparency_witness_rollback_resolution", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_rollback_resolution_verify: { rpcName: "velmere_verify_release_transparency_witness_rollback_resolution", deadlineMs: 5_000, family: "audit" },
  release_transparency_witness_rollback_resolution_status: { rpcName: "velmere_get_release_transparency_witness_rollback_resolution_status", deadlineMs: 4_000, family: "audit" },
  release_transparency_witness_rollback_resolution_public_feed: { rpcName: "velmere_get_public_release_transparency_witness_rollback_resolutions", deadlineMs: 5_000, family: "audit" },
  vlm_paid_entitlement_lifecycle_apply: { rpcName: "velmere_apply_vlm_paid_entitlement_lifecycle_event", deadlineMs: 5_000, family: "payments" },
  vlm_paid_entitlement_create_or_read: { rpcName: "velmere_create_or_read_vlm_paid_entitlement", deadlineMs: 5_000, family: "payments" },
  advanced_audit_release_transition_record: { rpcName: "velmere_record_advanced_audit_release_transition_v2", deadlineMs: 5_000, family: "audit" },
  paid_audit_terminal_transition_apply: { rpcName: "velmere_apply_paid_audit_terminal_transition", deadlineMs: 5_000, family: "payments" },
  audit_checkout_bind: { rpcName: "velmere_bind_paid_audit_checkout", deadlineMs: 5_000, family: "audit" },
  audit_paid_case_promote: { rpcName: "velmere_promote_paid_audit_case", deadlineMs: 5_000, family: "audit" },
  audit_payment_terminal_apply: { rpcName: "velmere_apply_audit_payment_terminal_event", deadlineMs: 5_000, family: "audit" },
  audit_customer_history_get: { rpcName: "velmere_get_audit_case_customer_history", deadlineMs: 5_000, family: "audit" },
  audit_advanced_reviewer_assign: { rpcName: "velmere_assign_advanced_audit_reviewer", deadlineMs: 5_000, family: "audit" },
  audit_basic_worker_lease_claim: { rpcName: "velmere_claim_basic_audit_worker_lease", deadlineMs: 4_000, family: "audit" },
  audit_basic_worker_lease_preflight: { rpcName: "velmere_preflight_basic_audit_worker_lease", deadlineMs: 4_000, family: "audit" },
  audit_basic_worker_lease_settle: { rpcName: "velmere_settle_basic_audit_worker_lease", deadlineMs: 4_000, family: "audit" },
  audit_basic_worker_complete_with_exact_pdf: { rpcName: "velmere_complete_basic_audit_with_exact_pdf_v1", deadlineMs: 10_000, family: "audit" },
  audit_pro_worker_lease_claim: { rpcName: "velmere_claim_pro_audit_worker_lease", deadlineMs: 4_000, family: "audit" },
  audit_pro_worker_lease_settle: { rpcName: "velmere_settle_pro_audit_worker_lease", deadlineMs: 4_000, family: "audit" },
  audit_pro_worker_complete_with_snapshot: { rpcName: "velmere_complete_pro_audit_with_snapshot", deadlineMs: 8_000, family: "audit" },
  audit_pro_worker_complete_with_exact_pdf_v2: { rpcName: "velmere_complete_pro_audit_with_exact_pdf_v2", deadlineMs: 10_000, family: "audit" },
  audit_advanced_worker_lease_claim: { rpcName: "velmere_claim_advanced_audit_worker_lease", deadlineMs: 4_000, family: "audit" },
  audit_advanced_worker_lease_settle: { rpcName: "velmere_settle_advanced_audit_worker_lease", deadlineMs: 4_000, family: "audit" },
  audit_advanced_worker_complete_with_snapshot: { rpcName: "velmere_complete_advanced_audit_with_snapshot", deadlineMs: 8_000, family: "audit" },
  audit_advanced_worker_complete_with_exact_pdf_v2: { rpcName: "velmere_complete_advanced_audit_with_exact_pdf_v2", deadlineMs: 10_000, family: "audit" },
  audit_verify_initial_publish: { rpcName: "velmere_publish_completed_audit_to_verify_v1", deadlineMs: 5_000, family: "audit" },
  verify_publication_event_append: { rpcName: "velmere_append_verify_publication_event_v1", deadlineMs: 5_000, family: "audit" },
  verify_publication_resolve_exact: { rpcName: "velmere_resolve_verify_publication_exact_v1", deadlineMs: 3_000, family: "audit" },
  verify_publication_search: { rpcName: "velmere_search_verify_publications_v1", deadlineMs: 4_000, family: "audit" },
  verify_publication_history: { rpcName: "velmere_get_verify_publication_history_v1", deadlineMs: 4_000, family: "audit" },
  verify_monitor_job_claim: { rpcName: "velmere_claim_verify_monitor_jobs_v1", deadlineMs: 4_000, family: "audit" },
  verify_monitor_job_settle: { rpcName: "velmere_settle_verify_monitor_job_v1", deadlineMs: 6_000, family: "audit" },
  verify_monitor_health: { rpcName: "velmere_get_verify_monitor_health_v1", deadlineMs: 4_000, family: "audit" },
  auth_security_event_record: { rpcName: "velmere_record_auth_security_event", deadlineMs: 1_000, family: "auth" },
  auth_session_family_issue: { rpcName: "velmere_issue_auth_session_family", deadlineMs: 3_000, family: "auth" },
  auth_session_family_rotate: { rpcName: "velmere_rotate_auth_session_family", deadlineMs: 3_000, family: "auth" },
  auth_session_family_revoke: { rpcName: "velmere_revoke_auth_session_family", deadlineMs: 3_000, family: "auth" },
  auth_session_family_verify: { rpcName: "velmere_verify_auth_session_family", deadlineMs: 2_000, family: "auth" },
  auth_session_family_revoke_subject: { rpcName: "velmere_revoke_auth_session_subject", deadlineMs: 3_000, family: "auth" },
  account_erasure_session_revocation_confirm: { rpcName: "velmere_confirm_account_erasure_session_revocation_v1", deadlineMs: 4_000, family: "auth" },
  password_recovery_grant_issue: { rpcName: "velmere_issue_password_recovery_grant", deadlineMs: 3_000, family: "auth" },
  password_recovery_grant_consume: { rpcName: "velmere_consume_password_recovery_grant", deadlineMs: 3_000, family: "auth" },
  auth_alert_worker_claim: { rpcName: "velmere_claim_auth_security_alerts", deadlineMs: 4_000, family: "auth" },
  auth_alert_event_settle: { rpcName: "velmere_settle_auth_security_alert", deadlineMs: 4_000, family: "auth" },
} as const satisfies Record<string, { rpcName: string; deadlineMs: number; family: SupabaseRpcOperationFamily }>;

export type SupabaseRpcOperation = keyof typeof SUPABASE_RPC_OPERATIONS;

export function runRegisteredServiceRoleRpc(input: {
  operation: SupabaseRpcOperation;
  args?: Record<string, unknown>;
  clientOverride?: SupabaseRpcClient | null;
}) {
  const definition = SUPABASE_RPC_OPERATIONS[input.operation];
  return runGovernedSupabaseRpc({
    family: definition.family,
    execute: () => runBoundedServiceRoleRpc({
      operation: input.operation,
      rpcName: definition.rpcName,
      args: input.args,
      deadlineMs: definition.deadlineMs,
      clientOverride: input.clientOverride,
    }),
  });
}
