/**
 * Forensic Validation Furnace - External Ground Truth Registry
 * Authoritative independent verification facts gathered from primary sources:
 * Etherscan, BSCScan, Arbiscan, SEC EDGAR, CME Group, Yahoo Finance, CoinGecko.
 */

export interface ExternalAssetFact {
  symbol: string;
  officialName: string;
  expectedClass: "evm_contract" | "native_chain" | "market_asset";
  primaryIdentifier: string; // address or ticker
  primaryVenueOrChain: string;
  officialDecimals?: number;
  officialCurrency: string;
  primaryExplorerUrl: string;
  officialSourceType: "BLOCKCHAIN_RPC" | "SEC_EDGAR" | "EXCHANGE_FEED" | "COMMODITY_EXCHANGE";
  governancePattern: string;
  knownRiskFactors: string[];
  historicalEvents: string[];
}

export const EXTERNAL_GROUND_TRUTH: Record<string, ExternalAssetFact> = {
  // 1. EVM Smart Contracts (20)
  "USDT": {
    symbol: "USDT",
    officialName: "Tether USD",
    expectedClass: "evm_contract",
    primaryIdentifier: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 6,
    officialCurrency: "USD",
    primaryExplorerUrl: "https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Centralized Upgradable Proxy (custom Tether proxy)",
    knownRiskFactors: ["Blacklist function", "Uncollateralized mint capability by owner", "Single-key administrative control"],
    historicalEvents: ["2017 Omni-to-ERC20 migration", "Multi-billion dollar freezes under law enforcement requests"]
  },
  "USDC": {
    symbol: "USDC",
    officialName: "USD Coin",
    expectedClass: "evm_contract",
    primaryIdentifier: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 6,
    officialCurrency: "USD",
    primaryExplorerUrl: "https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "FiatTokenProxy (EIP-1967 like upgradeable pattern)",
    knownRiskFactors: ["Blacklister role", "Pauser role", "MasterMinter multi-tier permission"],
    historicalEvents: ["SVB depeg incident March 2023", "Circle regulatory compliance freezes"]
  },
  "WBNB": {
    symbol: "WBNB",
    officialName: "Wrapped BNB",
    expectedClass: "evm_contract",
    primaryIdentifier: "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
    primaryVenueOrChain: "BNB Smart Chain",
    officialDecimals: 18,
    officialCurrency: "BNB",
    primaryExplorerUrl: "https://bscscan.com/token/0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Immutable Canonical Wrapper",
    knownRiskFactors: ["Fallback reentrancy risk on withdraw if recipient is contract", "Zero upgradeability"],
    historicalEvents: ["Canonical BSC foundation contract deployed 2020"]
  },
  "CAKE-RTR": {
    symbol: "CAKE-RTR",
    officialName: "PancakeSwap Router v2",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x10ed43c718714eb63d5aa57b78b54704e256024e",
    primaryVenueOrChain: "BNB Smart Chain",
    officialCurrency: "BNB",
    primaryExplorerUrl: "https://bscscan.com/address/0x10ed43c718714eb63d5aa57b78b54704e256024e",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Immutable DEX Router",
    knownRiskFactors: ["Slippage tolerance parameter exploitation", "Arbitrary token call risks"],
    historicalEvents: ["BSC Uniswap-v2 clone migration April 2021"]
  },
  "UNI-V3-RTR": {
    symbol: "UNI-V3-RTR",
    officialName: "Uniswap v3 SwapRouter",
    expectedClass: "evm_contract",
    primaryIdentifier: "0xe592427a0aece92de3edee1f18e0157c05861564",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialCurrency: "ETH",
    primaryExplorerUrl: "https://etherscan.io/address/0xe592427a0aece92de3edee1f18e0157c05861564",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Immutable Concentrated Liquidity Periphery",
    knownRiskFactors: ["Deadline timestamp bypass", "Multi-hop path poisoning"],
    historicalEvents: ["Uniswap v3 core deployment May 2021"]
  },
  "DAI": {
    symbol: "DAI",
    officialName: "Dai Stablecoin",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x6b175474e89094c44da98b954eedeac495271d0f",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 18,
    officialCurrency: "USD",
    primaryExplorerUrl: "https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "MakerDAO Governance Ward/Rely Pattern",
    knownRiskFactors: ["Debt ceiling adjustments", "PSM USDC reserve exposure"],
    historicalEvents: ["Black Thursday 2020 zero-bid liquidations", "Multi-Collateral Dai upgrade"]
  },
  "LINK": {
    symbol: "LINK",
    officialName: "Chainlink Token",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x514910771af9ca656af840dff83e8264ecf986ca",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 18,
    officialCurrency: "LINK",
    primaryExplorerUrl: "https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "ERC677 TransferAndCall Standard",
    knownRiskFactors: ["Hook callback reentrancy if target does not guard onTokenTransfer"],
    historicalEvents: ["Chainlink oracle network foundational deployment 2017"]
  },
  "PEPE": {
    symbol: "PEPE",
    officialName: "Pepe",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x6982508145454ce325ddbe47a25d4ec3d2311933",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 18,
    officialCurrency: "PEPE",
    primaryExplorerUrl: "https://etherscan.io/token/0x6982508145454ce325ddbe47a25d4ec3d2311933",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Renounced Ownable Memecoin",
    knownRiskFactors: ["Historical multisig rogue team transfer August 2023", "Extreme volatility"],
    historicalEvents: ["Stealth launch April 2023", "CEX liquidity expansion"]
  },
  "SHIB": {
    symbol: "SHIB",
    officialName: "SHIBA INU",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 18,
    officialCurrency: "SHIB",
    primaryExplorerUrl: "https://etherscan.io/token/0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Immutable Standard ERC20",
    knownRiskFactors: ["Massive initial supply gifted to Vitalik Buterin (burned/donated)", "Extreme meme speculation"],
    historicalEvents: ["Vitalik India Covid Relief donation May 2021"]
  },
  "AAVE-POOL": {
    symbol: "AAVE-POOL",
    officialName: "Aave v3 Pool",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x87870bca3f3fd6335c3f4ce8392d69350b4fa4e2",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialCurrency: "ETH",
    primaryExplorerUrl: "https://etherscan.io/address/0x87870bca3f3fd6335c3f4ce8392d69350b4fa4e2",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Aave Governance v3 Timelock + ACLManager",
    knownRiskFactors: ["Flash loan attack surfaces on illiquid collateral", "Oracle latency frontrunning"],
    historicalEvents: ["Aave v3 Ethereum deployment January 2023"]
  },
  "stETH": {
    symbol: "stETH",
    officialName: "Lido Liquid Staked ETH",
    expectedClass: "evm_contract",
    primaryIdentifier: "0xae7ab96520de3a18e5e111b5eaab095312d7fe84",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 18,
    officialCurrency: "ETH",
    primaryExplorerUrl: "https://etherscan.io/token/0xae7ab96520de3a18e5e111b5eaab095312d7fe84",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Aragon DAO Proxy Rebase Token",
    knownRiskFactors: ["Daily rebase balance change breaks non-rebase DeFi protocols", "Validator slashing exposure"],
    historicalEvents: ["Celsius / 3AC stETH depeg pressure June 2022", "Ethereum Shapella withdrawal enablement"]
  },
  "3CRV": {
    symbol: "3CRV",
    officialName: "Curve.fi 3pool",
    expectedClass: "evm_contract",
    primaryIdentifier: "0xbebc44782c7db0a1a60cb6fe97d0b483032ff1c7",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 18,
    officialCurrency: "USD",
    primaryExplorerUrl: "https://etherscan.io/address/0xbebc44782c7db0a1a60cb6fe97d0b483032ff1c7",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Curve VotingEscrow DAO + Vyper Stableswap",
    knownRiskFactors: ["Imbalanced pool vulnerability when one component stablecoin depegs"],
    historicalEvents: ["UST collapse May 2022 3pool draining", "Vyper compiler reentrancy exploit 2023"]
  },
  "ARB-INBOX": {
    symbol: "ARB-INBOX",
    officialName: "Arbitrum One Bridge Inbox",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x4dbd4fc535ac27206064b68ffcf827b0a60bab3f",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialCurrency: "ETH",
    primaryExplorerUrl: "https://etherscan.io/address/0x4dbd4fc535ac27206064b68ffcf827b0a60bab3f",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Arbitrum Security Council 9-of-14 Multisig + Rollup Timelock",
    knownRiskFactors: ["Sequencer censorship fallback to L1 inbox", "Emergency upgrade overrides"],
    historicalEvents: ["Nitro upgrade 2022", "Arbitrum governance token airdrop 2023"]
  },
  "SAFE": {
    symbol: "SAFE",
    officialName: "Gnosis Safe L2 Master Copy",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x3e5c63644e683549055b9be8653de26e0b4cd36e",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialCurrency: "ETH",
    primaryExplorerUrl: "https://etherscan.io/address/0x3e5c63644e683549055b9be8653de26e0b4cd36e",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Self-governed Multi-Signature Threshold Scheme",
    knownRiskFactors: ["Fallback handler reentrancy if malicious module attached", "Signature malleability in legacy schemes"],
    historicalEvents: ["Safe v1.3.0 release", "Spin-off from Gnosis to Safe DAO"]
  },
  "cUSDC": {
    symbol: "cUSDC",
    officialName: "Compound USD Coin",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x39aa39c021dfbae8fac545936693ac917d5e7563",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 8,
    officialCurrency: "USD",
    primaryExplorerUrl: "https://etherscan.io/token/0x39aa39c021dfbae8fac545936693ac917d5e7563",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Compound Comptroller Delegator Architecture",
    knownRiskFactors: ["Interest rate jump model spikes", "Comptroller proposal distribution bugs"],
    historicalEvents: ["Compound Proposal 62 token distribution bug September 2021"]
  },
  "SAFEMOON": {
    symbol: "SAFEMOON",
    officialName: "SafeMoon",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x8076c74c5e3f5852037f31ff0093eeb8c8add8d3",
    primaryVenueOrChain: "BNB Smart Chain",
    officialDecimals: 9,
    officialCurrency: "SAFEMOON",
    primaryExplorerUrl: "https://bscscan.com/token/0x8076c74c5e3f5852037f31ff0093eeb8c8add8d3",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Privileged Ownable High-Tax Memecoin",
    knownRiskFactors: ["10% transfer fee (5% liquidity + 5% reflection)", "Liquidity pool drain vulnerability", "SEC indictment of leadership"],
    historicalEvents: ["2021 meme bull run", "Public burn routine exploit March 2023 ($8.9M drain)"]
  },
  "FLOKI": {
    symbol: "FLOKI",
    officialName: "Floki",
    expectedClass: "evm_contract",
    primaryIdentifier: "0xfb5b838b6cff2d9991874f439794e0985f4658ab",
    primaryVenueOrChain: "BNB Smart Chain",
    officialDecimals: 9,
    officialCurrency: "FLOKI",
    primaryExplorerUrl: "https://bscscan.com/token/0xfb5b838b6cff2d9991874f439794e0985f4658ab",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Upgraded Multi-Bridge Meme Token",
    knownRiskFactors: ["Cross-chain bridge dependence", "Marketing tax governance changes"],
    historicalEvents: ["Contract relaunch from V1 to V3 2022"]
  },
  "SNX": {
    symbol: "SNX",
    officialName: "Synthetix Proxy",
    expectedClass: "evm_contract",
    primaryIdentifier: "0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialDecimals: 18,
    officialCurrency: "SNX",
    primaryExplorerUrl: "https://etherscan.io/token/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Custom Proxy ERC20 with Spartan Council Governance",
    knownRiskFactors: ["Global debt pool fluctuations", "Synthetic asset frontrunning"],
    historicalEvents: ["sKRW oracle misprice incident 2019", "Synthetix v3 modular architecture"]
  },
  "BLUR": {
    symbol: "BLUR",
    officialName: "Blur Marketplace Exchange",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x000000000000ad05ccc4f10045630fb539565570",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialCurrency: "ETH",
    primaryExplorerUrl: "https://etherscan.io/address/0x000000000000ad05ccc4f10045630fb539565570",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Immutable Vanity Address Order Matcher",
    knownRiskFactors: ["Signature cancellation gas costs", "Off-chain orderbook matching disputes"],
    historicalEvents: ["Blur marketplace launch October 2022 surpassing OpenSea volume"]
  },
  "TORN": {
    symbol: "TORN",
    officialName: "Tornado.Cash Router",
    expectedClass: "evm_contract",
    primaryIdentifier: "0xd90e2f925da726b50c4ed8d0fb90ad053324f31b",
    primaryVenueOrChain: "Ethereum Mainnet",
    officialCurrency: "ETH",
    primaryExplorerUrl: "https://etherscan.io/address/0xd90e2f925da726b50c4ed8d0fb90ad053324f31b",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Zero-Knowledge Non-Custodial Mixer",
    knownRiskFactors: ["OFAC Sanctions designation", "DAO governance hijacking attack (Proposal exploit May 2023)"],
    historicalEvents: ["US Treasury OFAC Sanctions August 2022", "Governance takeover & restoration May 2023"]
  },

  // 2. Native Chains (10)
  "BTC": {
    symbol: "BTC",
    officialName: "Bitcoin Core",
    expectedClass: "native_chain",
    primaryIdentifier: "BTC",
    primaryVenueOrChain: "Bitcoin Network",
    officialDecimals: 8,
    officialCurrency: "BTC",
    primaryExplorerUrl: "https://mempool.space",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Proof of Work Nakamoto Consensus (BIP Softforks)",
    knownRiskFactors: ["ASIC hashpower centralization", "51% attack threshold (theoretically costly)", "MEV transaction fee volatility"],
    historicalEvents: ["Genesis block January 2009", "Taproot activation November 2021", "Halving April 2024"]
  },
  "ETH": {
    symbol: "ETH",
    officialName: "Ethereum Execution Protocol",
    expectedClass: "native_chain",
    primaryIdentifier: "ETH",
    primaryVenueOrChain: "Ethereum Beacon Chain",
    officialDecimals: 18,
    officialCurrency: "ETH",
    primaryExplorerUrl: "https://beaconcha.in",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Proof of Stake Casper FFG + LMD GHOST",
    knownRiskFactors: ["Liquid staking concentration (Lido 28%+)", "OFAC compliant relayer censorship"],
    historicalEvents: ["The Merge September 2022", "Dencun EIP-4844 blobs March 2024"]
  },
  "SOL": {
    symbol: "SOL",
    officialName: "Solana Core",
    expectedClass: "native_chain",
    primaryIdentifier: "SOL",
    primaryVenueOrChain: "Solana Mainnet-Beta",
    officialDecimals: 9,
    officialCurrency: "SOL",
    primaryExplorerUrl: "https://solscan.io",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Proof of History + Tower BFT",
    knownRiskFactors: ["Historical mainnet cluster halting incidents", "Turbine packet loss during high bot activity"],
    historicalEvents: ["Multiple cluster outages 2021-2023", "Firedancer independent client development"]
  },
  "BNB": {
    symbol: "BNB",
    officialName: "BNB Beacon / Smart Chain",
    expectedClass: "native_chain",
    primaryIdentifier: "BNB",
    primaryVenueOrChain: "BNB Smart Chain",
    officialDecimals: 18,
    officialCurrency: "BNB",
    primaryExplorerUrl: "https://bscscan.com",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Proof of Staked Authority (21-45 Elected Validators)",
    knownRiskFactors: ["Validator set concentration around ecosystem operators", "BSC Token Hub bridge exploit October 2022"],
    historicalEvents: ["BSC Token Hub hard fork fix October 2022", "BNB Beacon Chain sunset 2024"]
  },
  "DOGE": {
    symbol: "DOGE",
    officialName: "Dogecoin Core",
    expectedClass: "native_chain",
    primaryIdentifier: "DOGE",
    primaryVenueOrChain: "Dogecoin Network",
    officialDecimals: 8,
    officialCurrency: "DOGE",
    primaryExplorerUrl: "https://dogechain.info",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Auxiliary Proof of Work (Merged mined with Litecoin Scrypt)",
    knownRiskFactors: ["LTC mining pool hashpower concentration", "Zero hard supply cap (inflationary 5B DOGE/year)"],
    historicalEvents: ["AuxPoW hard fork 2014 preventing 51% attack", "2021 viral social media rally"]
  },
  "XRP": {
    symbol: "XRP",
    officialName: "Ripple Ledger Base",
    expectedClass: "native_chain",
    primaryIdentifier: "XRP",
    primaryVenueOrChain: "XRP Ledger",
    officialDecimals: 6,
    officialCurrency: "XRP",
    primaryExplorerUrl: "https://xrpscan.com",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Ripple Protocol Consensus Algorithm (Unique Node Lists - UNL)",
    knownRiskFactors: ["Default UNL centralization around Ripple Labs / foundations", "Escrow supply releases"],
    historicalEvents: ["SEC vs Ripple summary judgment July 2023 (non-security status for programmatic sales)"]
  },
  "ADA": {
    symbol: "ADA",
    officialName: "Cardano Settlement Layer",
    expectedClass: "native_chain",
    primaryIdentifier: "ADA",
    primaryVenueOrChain: "Cardano Mainnet",
    officialDecimals: 6,
    officialCurrency: "ADA",
    primaryExplorerUrl: "https://cardanoscan.io",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Ouroboros Praos Proof of Stake + Voltaire CIP-1694 Governance",
    knownRiskFactors: ["eUTxO concurrency design bottlenecks", "Slow peer-reviewed rollout"],
    historicalEvents: ["Shelley decentralization 2020", "Alonzo smart contracts 2021", "Chang hardfork 2024"]
  },
  "AVAX": {
    symbol: "AVAX",
    officialName: "Avalanche C-Chain",
    expectedClass: "native_chain",
    primaryIdentifier: "AVAX",
    primaryVenueOrChain: "Avalanche Primary Network",
    officialDecimals: 18,
    officialCurrency: "AVAX",
    primaryExplorerUrl: "https://snowtrace.io",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Avalanche Snowman Consensus Subnet Architecture",
    knownRiskFactors: ["Primary network validator high hardware requirements", "C-Chain state bloat"],
    historicalEvents: ["Avalanche Rush incentive program 2021", "Teleporter cross-subnet messaging 2024"]
  },
  "DOT": {
    symbol: "DOT",
    officialName: "Polkadot Relay Chain",
    expectedClass: "native_chain",
    primaryIdentifier: "DOT",
    primaryVenueOrChain: "Polkadot Relay Chain",
    officialDecimals: 10,
    officialCurrency: "DOT",
    primaryExplorerUrl: "https://polkadot.subscan.io",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Nominated Proof of Stake (NPoS) + OpenGov",
    knownRiskFactors: ["Parachain slot auction complexity", "28-day unbonding period liquidity lock"],
    historicalEvents: ["Polkadot 1.0 completion", "Polkadot 2.0 Agile Coretime transition"]
  },
  "TRX": {
    symbol: "TRX",
    officialName: "Tron Protocol",
    expectedClass: "native_chain",
    primaryIdentifier: "TRX",
    primaryVenueOrChain: "Tron Mainnet",
    officialDecimals: 6,
    officialCurrency: "TRX",
    primaryExplorerUrl: "https://tronscan.org",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Delegated Proof of Stake (27 Super Representatives)",
    knownRiskFactors: ["Concentrated SR validator set", "Energy model high fee changes for USDT transfers"],
    historicalEvents: ["Mainnet independence 2018", "Becoming largest network by USDT volume"]
  },

  // 3. Traditional Market Assets: Equities, ETFs, Commodities, Forex (10)
  "AAPL": {
    symbol: "AAPL",
    officialName: "Apple Inc. Equity",
    expectedClass: "market_asset",
    primaryIdentifier: "AAPL",
    primaryVenueOrChain: "NASDAQ GS",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.sec.gov/edgar/browse/?CIK=0000320193",
    officialSourceType: "SEC_EDGAR",
    governancePattern: "Corporate Board of Directors + Public Shareholder Voting",
    knownRiskFactors: ["Global hardware supply chain concentration in China/Taiwan", "Antitrust app store regulatory fines"],
    historicalEvents: ["First company to reach $3 Trillion market cap", "Annual 10-K SEC audits verified"]
  },
  "NVDA": {
    symbol: "NVDA",
    officialName: "NVIDIA Corp. Equity",
    expectedClass: "market_asset",
    primaryIdentifier: "NVDA",
    primaryVenueOrChain: "NASDAQ GS",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.sec.gov/edgar/browse/?CIK=0001045810",
    officialSourceType: "SEC_EDGAR",
    governancePattern: "Corporate Board of Directors + SEC Regulated",
    knownRiskFactors: ["TSMC single-source semiconductor fabrication", "US export restrictions on AI accelerators to China"],
    historicalEvents: ["10-for-1 stock split June 2024", "Dominance in datacenter AI infrastructure"]
  },
  "MSFT": {
    symbol: "MSFT",
    officialName: "Microsoft Corp. Equity",
    expectedClass: "market_asset",
    primaryIdentifier: "MSFT",
    primaryVenueOrChain: "NASDAQ GS",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.sec.gov/edgar/browse/?CIK=0000789019",
    officialSourceType: "SEC_EDGAR",
    governancePattern: "Corporate Board of Directors + AAA Credit Rating",
    knownRiskFactors: ["Cloud infrastructure competition", "CrowdStrike kernel outage reputational impact 2024"],
    historicalEvents: ["OpenAI strategic partnership", "Activision Blizzard acquisition $69B"]
  },
  "TSLA": {
    symbol: "TSLA",
    officialName: "Tesla Inc. Equity",
    expectedClass: "market_asset",
    primaryIdentifier: "TSLA",
    primaryVenueOrChain: "NASDAQ GS",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.sec.gov/edgar/browse/?CIK=0001318605",
    officialSourceType: "SEC_EDGAR",
    governancePattern: "Corporate Board of Directors + High Key-Person Dependency",
    knownRiskFactors: ["Key-man risk (Elon Musk)", "EV margin compression from Chinese manufacturers (BYD)"],
    historicalEvents: ["S&P 500 inclusion December 2020", "Delaware Court CEO compensation dispute"]
  },
  "SPY": {
    symbol: "SPY",
    officialName: "SPDR S&P 500 ETF Trust",
    expectedClass: "market_asset",
    primaryIdentifier: "SPY",
    primaryVenueOrChain: "NYSE Arca",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.ssga.com/us/en/intermediary/etfs/funds/spdr-sp-500-etf-trust-spy",
    officialSourceType: "SEC_EDGAR",
    governancePattern: "Unit Investment Trust (State Street Global Advisors)",
    knownRiskFactors: ["Top-heavy index concentration (Mag-7 ~30%)", "Market-wide systematic liquidity drawdowns"],
    historicalEvents: ["Oldest surviving US exchange-traded fund founded 1993"]
  },
  "QQQ": {
    symbol: "QQQ",
    officialName: "Invesco QQQ Trust",
    expectedClass: "market_asset",
    primaryIdentifier: "QQQ",
    primaryVenueOrChain: "NASDAQ",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.invesco.com/qqq-etf/en/home.html",
    officialSourceType: "SEC_EDGAR",
    governancePattern: "Unit Investment Trust (Invesco Capital Management)",
    knownRiskFactors: ["Tech sector systemic cyclicality", "Nasdaq-100 special rebalance threshold triggers"],
    historicalEvents: ["Special rebalance July 2023 to curb mega-cap tech dominance"]
  },
  "GC=F": {
    symbol: "GC=F",
    officialName: "Gold Comex Futures",
    expectedClass: "market_asset",
    primaryIdentifier: "GC=F",
    primaryVenueOrChain: "COMEX / CME Group",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.cmegroup.com/markets/metals/precious/gold.html",
    officialSourceType: "COMMODITY_EXCHANGE",
    governancePattern: "CME Rulebook Cleared Contract (100 troy oz)",
    knownRiskFactors: ["Delivery physical settlement constraints", "Central bank interest rate opportunity cost"],
    historicalEvents: ["All-time highs 2024 surpassing $2,500/oz amid geopolitical safe-haven demand"]
  },
  "CL=F": {
    symbol: "CL=F",
    officialName: "Crude Oil WTI Futures",
    expectedClass: "market_asset",
    primaryIdentifier: "CL=F",
    primaryVenueOrChain: "NYMEX / CME Group",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.cmegroup.com/markets/energy/crude-oil/light-sweet-crude.html",
    officialSourceType: "COMMODITY_EXCHANGE",
    governancePattern: "CME Rulebook Cleared Contract (1,000 U.S. barrels)",
    knownRiskFactors: ["Geopolitical Middle East / OPEC+ quota volatility", "Cushing storage tank saturation"],
    historicalEvents: ["Negative pricing incident April 20, 2020 (-$37.63/barrel due to expiring contract storage exhaustion)"]
  },
  "EURUSD=X": {
    symbol: "EURUSD=X",
    officialName: "EUR/USD Forex Spot",
    expectedClass: "market_asset",
    primaryIdentifier: "EURUSD=X",
    primaryVenueOrChain: "Global Interbank Spot FX",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/eurofxref-graph-usd.en.html",
    officialSourceType: "EXCHANGE_FEED",
    governancePattern: "Decentralized OTC Interbank Continuous Dealing",
    knownRiskFactors: ["ECB vs Federal Reserve interest rate differential", "Macro sovereign fiscal divergences"],
    historicalEvents: ["Parity breach 2022 during European energy crisis"]
  },
  "SI=F": {
    symbol: "SI=F",
    officialName: "Silver Comex Futures",
    expectedClass: "market_asset",
    primaryIdentifier: "SI=F",
    primaryVenueOrChain: "COMEX / CME Group",
    officialCurrency: "USD",
    primaryExplorerUrl: "https://www.cmegroup.com/markets/metals/precious/silver.html",
    officialSourceType: "COMMODITY_EXCHANGE",
    governancePattern: "CME Rulebook Cleared Contract (5,000 troy oz)",
    knownRiskFactors: ["Dual monetary and industrial (solar panel) demand swings", "High leverage volatility"],
    historicalEvents: ["Hunt Brothers short squeeze attempt 1980", "2021 retail silver squeeze"]
  },

  // 4. Edge & Adversarial Trap Fixtures (10)
  "MAL-BYTE": {
    symbol: "MAL-BYTE",
    officialName: "Malformed Bytecode Trap Fixture",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x9999999999999999999999999999999999999001",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialCurrency: "ETH",
    primaryExplorerUrl: "urn:velmere:adversarial:mal-byte",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Truncated Invalid Opcode Injection",
    knownRiskFactors: ["EVM crash attempt on invalid opcode 0xFE / truncated PUSH", "Decompiler parser panic test"],
    historicalEvents: ["Adversarial test suite fixture"]
  },
  "UNR-SEL": {
    symbol: "UNR-SEL",
    officialName: "Unreachable Selector Trap Fixture",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x9999999999999999999999999999999999999002",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialCurrency: "ETH",
    primaryExplorerUrl: "urn:velmere:adversarial:unr-sel",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Dead Code Path Routing",
    knownRiskFactors: ["Selector table contains entries unreachable due to prior revert in dispatcher"],
    historicalEvents: ["Adversarial test suite fixture"]
  },
  "ZERO-DEC": {
    symbol: "ZERO-DEC",
    officialName: "Zero Decimals Extreme Token Fixture",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x9999999999999999999999999999999999999003",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialDecimals: 0,
    officialCurrency: "ZDEC",
    primaryExplorerUrl: "urn:velmere:adversarial:zero-dec",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Extreme Integer Divisibility Boundary",
    knownRiskFactors: ["Integer division truncation in DeFi pools", "Floating point rounding bugs"],
    historicalEvents: ["Adversarial test suite fixture"]
  },
  "HIGH-DEC": {
    symbol: "HIGH-DEC",
    officialName: "High Decimals (36) Extreme Token Fixture",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x9999999999999999999999999999999999999004",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialDecimals: 36,
    officialCurrency: "HDEC",
    primaryExplorerUrl: "urn:velmere:adversarial:high-dec",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Overflow Decimal Boundary",
    knownRiskFactors: ["Uint256 overflow during 10^36 scaling calculations"],
    historicalEvents: ["Adversarial test suite fixture"]
  },
  "PRX-LOOP": {
    symbol: "PRX-LOOP",
    officialName: "Circular Proxy Storage Loop Fixture",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x9999999999999999999999999999999999999005",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialCurrency: "ETH",
    primaryExplorerUrl: "urn:velmere:adversarial:prx-loop",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "A -> B -> A Recursive Delegatecall Trap",
    knownRiskFactors: ["Infinite loop execution during proxy resolution", "Stack overflow in static call analyzers"],
    historicalEvents: ["Adversarial test suite fixture"]
  },
  "ORC-DIV": {
    symbol: "ORC-DIV",
    officialName: "Divergent Oracle Feed Fixture",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x9999999999999999999999999999999999999006",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialCurrency: "ETH",
    primaryExplorerUrl: "urn:velmere:adversarial:orc-div",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Contradictory Price Multi-Feed Quorum",
    knownRiskFactors: [">500 bps divergence between primary and secondary feeds", "Arbitrage manipulation attack vector"],
    historicalEvents: ["Adversarial test suite fixture"]
  },
  "UNV-BYTE": {
    symbol: "UNV-BYTE",
    officialName: "Stripped Unverified Bytecode Fixture",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x9999999999999999999999999999999999999007",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialCurrency: "ETH",
    primaryExplorerUrl: "urn:velmere:adversarial:unv-byte",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Zero Metadata / Stripped Swarm Hash",
    knownRiskFactors: ["No Solidity source code available", "Decompilation heuristics required"],
    historicalEvents: ["Adversarial test suite fixture"]
  },
  "STALE-Q": {
    symbol: "STALE-Q",
    officialName: "Stale Deprecated Market Quote Fixture",
    expectedClass: "market_asset",
    primaryIdentifier: "STALE-Q",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialCurrency: "USD",
    primaryExplorerUrl: "urn:velmere:adversarial:stale-q",
    officialSourceType: "EXCHANGE_FEED",
    governancePattern: "Frozen Timestamp Feed Simulation",
    knownRiskFactors: ["Feed timestamp > 86400 seconds old", "UI must flag as STALE, never CURRENT"],
    historicalEvents: ["Adversarial test suite fixture"]
  },
  "COLL-AMB": {
    symbol: "COLL-AMB",
    officialName: "Symbol Collision Ambiguous Chain Fixture",
    expectedClass: "native_chain",
    primaryIdentifier: "COLL-AMB",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialCurrency: "COLL",
    primaryExplorerUrl: "urn:velmere:adversarial:coll-amb",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Conflicting Ticker across 3 Distinct Networks",
    knownRiskFactors: ["Chain ID ambiguity", "False asset resolution risk"],
    historicalEvents: ["Adversarial test suite fixture"]
  },
  "EIP1167-TRAP": {
    symbol: "EIP1167-TRAP",
    officialName: "Minimal EIP-1167 Clone Trap Fixture",
    expectedClass: "evm_contract",
    primaryIdentifier: "0x9999999999999999999999999999999999999010",
    primaryVenueOrChain: "Synthetic Adversarial Chamber",
    officialCurrency: "ETH",
    primaryExplorerUrl: "urn:velmere:adversarial:eip1167-trap",
    officialSourceType: "BLOCKCHAIN_RPC",
    governancePattern: "Minimal Proxy 45-byte Clone with Non-Standard Byte Injection",
    knownRiskFactors: ["Misdetection as full contract instead of clone", "Target implementation self-destruct risk"],
    historicalEvents: ["Adversarial test suite fixture"]
  }
};
