import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { createHash } from "node:crypto";
import assert from "node:assert/strict";
import { test } from "node:test";
import { verifyEvidenceFile } from "./verify-evidence-file.mjs";
const root=fs.mkdtempSync(path.join(os.tmpdir(),"velmere-r13g-"));
fs.mkdirSync(path.join(root,"evidence"));fs.writeFileSync(path.join(root,"evidence","terms.txt"),"reviewed bytes");
const digest=createHash("sha256").update("reviewed bytes").digest("hex");
process.on("exit",()=>fs.rmSync(root,{recursive:true,force:true}));
test("exact file bytes pass integrity only",()=>assert.deepEqual(verifyEvidenceFile(root,{path:"evidence/terms.txt",sha256:digest}),[]));
test("invented hash fails",()=>assert.ok(verifyEvidenceFile(root,{path:"evidence/terms.txt",sha256:"a".repeat(64)}).includes("evidence_hash_mismatch")));
for(const p of [""," ",".","..","/etc/passwd","../terms.txt","evidence/../terms.txt","evidence/./terms.txt","evidence//terms.txt","C:/secret","evidence\\terms.txt"]) test(`reject path ${JSON.stringify(p)}`,()=>assert.ok(verifyEvidenceFile(root,{path:p,sha256:digest}).length));
test("missing hash rejected",()=>assert.ok(verifyEvidenceFile(root,{path:"evidence/terms.txt"}).includes("bad_evidence_hash")));
test("directory is not evidence",()=>assert.ok(verifyEvidenceFile(root,{path:"evidence",sha256:digest}).includes("evidence_not_regular_file")));
test("missing file rejected",()=>assert.ok(verifyEvidenceFile(root,{path:"missing.txt",sha256:digest}).includes("evidence_file_unreadable")));
test("empty file rejected",()=>{fs.writeFileSync(path.join(root,"empty.txt"),"");assert.ok(verifyEvidenceFile(root,{path:"empty.txt",sha256:digest}).includes("evidence_empty"));});
test("symlink rejected",()=>{fs.symlinkSync(path.join(root,"evidence","terms.txt"),path.join(root,"link.txt"));assert.ok(verifyEvidenceFile(root,{path:"link.txt",sha256:digest}).includes("symlink_evidence_forbidden"));});
test("changed evidence fails even with old valid hash",()=>{fs.writeFileSync(path.join(root,"changed.txt"),"different bytes");assert.ok(verifyEvidenceFile(root,{path:"changed.txt",sha256:digest}).includes("evidence_hash_mismatch"));});
for(const e of [null,[],"https://example.invalid/terms"]) test(`reject non-object ${JSON.stringify(e)}`,()=>assert.ok(verifyEvidenceFile(root,e).length));
