from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path

EXPECTED_PARENT = {
    'fileCount': 1597,
    'payloadBytes': 20973292,
    'pathSetSha256': 'b8d9b3c2753e3f7f0c0b3a6054cf8c254d2a91b9c9c5d8f37310add478ac3f73',
    'sourceContentAggregateSha256': '6d400af1c8a042b9f1b9876744dc4e00d8786bb480a989cb78b477674760ee54',
}
EXPECTED_OUTPUT = {
    'fileCount': 1597,
    'payloadBytes': 20976155,
    'pathSetSha256': 'b8d9b3c2753e3f7f0c0b3a6054cf8c254d2a91b9c9c5d8f37310add478ac3f73',
    'sourceContentAggregateSha256': '406ef7545190872c7aa97bff31128f0d9496bed388dae950e47d71d0864acb9f',
}
FILES = {
    'lib/security/audit-report-assembler.ts': ('f3b95f8d43d94ee6087b30a12814cbe78b6ed61bfe3dc186323fbc18af167438', 25026, '8c0c6a3b2a3822f94c50c05d13e418cd5163f9af2569f5436ecd879edfe6f1a8', 26357),
    'lib/security/audit-report-customer-projection.ts': ('1835fa6a7a521b644500368405a3dd2c7eadc19e8c730ebabb8c81c81d635d9b', 5278, 'e033dc3ba853fdba6ad6fde9b3e929007d3f68830046918baff5777598f2afa8', 5841),
    'lib/security/audit-account-customer-snapshot.ts': ('9a16f5ac334beb280ed50ec608049ab54c5722fe06a4bf0dd52dea82d0274912', 17276, '0633fdac32eef832195d831e8ea40d181cbfd00e8679f6be793ff8d45244ae7e', 17880),
    'lib/security/audit-customer-report-pipeline.ts': ('fb7ab2a5d7a577538fa2340ce5884b80a231473ce53a753bf6d7c4518168623f', 24104, '0a6a389ab512fd54d914cde8edab260a3f57787a6bf2d16768bb2c66c7e7db83', 24402),
    'lib/server/security-route-modules/audit-report-assembler.ts': ('a2b3d3e9036a06de4213e309d49cea515e21aacc983280c2979ebaf341d07c1e', 11692, '69815f9409c8a9311404f02308141f762705da2a4712da28e5fdb41af3eb93aa', 11759),
}

def sha(b: bytes) -> str: return hashlib.sha256(b).hexdigest()

def projection(root: Path, manifest: dict):
    rows=[]; total=0; agg=hashlib.sha256(); paths=[]
    for exp in manifest['files']:
        b=(root/exp['path']).read_bytes(); h=sha(b); paths.append(exp['path']); total+=len(b)
        rows.append({'path':exp['path'],'byteLength':len(b),'sha256':h})
        agg.update(f"{exp['path']}\0{len(b)}\0{h}\n".encode())
    return {'fileCount':len(rows),'payloadBytes':total,'pathSetSha256':sha('\n'.join(paths).encode()),'sourceContentAggregateSha256':agg.hexdigest(),'files':rows}

def replace_once(s: str, old: str, new: str, label: str) -> str:
    if s.count(old) != 1: raise SystemExit(f'{label}:preimage_count={s.count(old)}')
    return s.replace(old,new,1)

ap=argparse.ArgumentParser(); ap.add_argument('--source-root',required=True); ap.add_argument('--manifest',required=True); ap.add_argument('--output-manifest',required=True); ap.add_argument('--receipt',required=True); a=ap.parse_args()
root=Path(a.source_root); manifest=json.loads(Path(a.manifest).read_text(encoding='utf-8'))
parent=projection(root,manifest); parent_no_files={k:v for k,v in parent.items() if k!='files'}
if parent_no_files != EXPECTED_PARENT: raise SystemExit(f'P71 parent identity mismatch:{parent_no_files}')
for rel,(before_sha,before_bytes,_,_) in FILES.items():
    b=(root/rel).read_bytes()
    if len(b)!=before_bytes or sha(b)!=before_sha: raise SystemExit(f'P71 preimage mismatch:{rel}:{len(b)}:{sha(b)}')

p=root/'lib/security/audit-report-assembler.ts'; s=p.read_text(encoding='utf-8')
s=replace_once(s,'export type Pass2578ReportFindingSeverity = "info" | "watch" | "elevated" | "critical";\n\nexport type Pass2578ReportSection = {','export type Pass2578ReportFindingSeverity = "info" | "watch" | "elevated" | "critical";\nexport type Pass2578EvidenceGapPriority = "low" | "medium" | "high" | "blocked";\n\nexport type Pass2578ReportSection = {','assembler:type-priority')
s=replace_once(s,'export type Pass2578TopFinding = {\n  id: string;\n  severity: Pass2578ReportFindingSeverity;\n  title: string;\n  publicLine: string;\n  proLine: string;\n  advancedAction: string;\n  sourceFamily: string;\n};','export type Pass2578TopFinding = {\n  id: string;\n  truthClass: "verified_adverse";\n  severity: Pass2578ReportFindingSeverity;\n  title: string;\n  publicLine: string;\n  proLine: string;\n  advancedAction: string;\n  sourceFamily: string;\n};\n\nexport type Pass2578EvidenceGap = {\n  id: string;\n  truthClass: "evidence_gap";\n  priority: Pass2578EvidenceGapPriority;\n  state: Pass2578ReportSectionState;\n  title: string;\n  publicLine: string;\n  proLine: string;\n  advancedAction: string;\n  sourceFamily: string;\n};','assembler:types')
s=replace_once(s,'    proPdfSections: number;\n    advancedActions: number;\n  };\n  sections: Pass2578ReportSection[];\n  basicSections: Pass2578ReportSection[];\n  proPdfSections: Pass2578ReportSection[];\n  advancedQueue: string[];\n  topFindings: Pass2578TopFinding[];\n  proPdfLines: string[];','    proPdfSections: number;\n    advancedActions: number;\n    verifiedFindings: number;\n    evidenceGaps: number;\n  };\n  sections: Pass2578ReportSection[];\n  basicSections: Pass2578ReportSection[];\n  proPdfSections: Pass2578ReportSection[];\n  advancedQueue: string[];\n  topFindings: Pass2578TopFinding[];\n  evidenceGaps: Pass2578EvidenceGap[];\n  proPdfLines: string[];','assembler:report')
s=replace_once(s,'function severityFor(state: Pass2578ReportSectionState, impact: number): Pass2578ReportFindingSeverity {\n  if (state === "ready") return "info";\n  if (state === "blocked" || impact >= 18) return "critical";\n  if (state === "manual_review" || impact >= 12) return "elevated";\n  return "watch";\n}','function evidenceGapPriority(state: Pass2578ReportSectionState, impact: number): Pass2578EvidenceGapPriority {\n  if (state === "blocked") return "blocked";\n  if (state === "missing" || impact >= 18) return "high";\n  if (state === "manual_review" || state === "partial" || impact >= 12) return "medium";\n  return "low";\n}','assembler:priority-fn')
s=replace_once(s,'function findingFromSection(locale: string, item: Pass2578ReportSection): Pass2578TopFinding {\n  const sourceFamily = item.sourceFamilies[0] ?? "velmere-engine";\n  return {\n    id: `finding-${item.id}`,\n    severity: severityFor(item.state, item.scoreImpact),\n    title: `${item.title} · ${stateWord(locale, item.state)}`,\n    publicLine: item.customerSummary,\n    proLine: item.proPdfSummary,\n    advancedAction: item.advancedAction,\n    sourceFamily,\n  };\n}','function evidenceGapFromSection(locale: string, item: Pass2578ReportSection): Pass2578EvidenceGap {\n  const sourceFamily = item.sourceFamilies[0] ?? "velmere-engine";\n  return {\n    id: `gap-${item.id}`,\n    truthClass: "evidence_gap",\n    priority: evidenceGapPriority(item.state, item.scoreImpact),\n    state: item.state,\n    title: `${item.title} · ${stateWord(locale, item.state)}`,\n    publicLine: item.customerSummary,\n    proLine: item.proPdfSummary,\n    advancedAction: item.advancedAction,\n    sourceFamily,\n  };\n}','assembler:gap-fn')
s=replace_once(s,'      "Missing evidence is a first-class output, not hidden copy",','      "Missing evidence is a first-class output, not hidden copy",\n      "Evidence gaps are never vulnerability findings and never receive vulnerability severity",','assembler:contract')
s=replace_once(s,'      {\n        slot: "top_findings",\n        dataPath: "pass2578AuditReportAssembler.topFindings",\n        visualOwner: "shared",\n        notes: "Best place for minimal luxury cards in your visual pass.",\n      },','      {\n        slot: "evidence_gaps",\n        dataPath: "pass2578AuditReportAssembler.evidenceGaps",\n        visualOwner: "shared",\n        notes: "Evidence-gap cards only. Never style or label these as verified vulnerability findings or vulnerability severity.",\n      },','assembler:slot')
s=replace_once(s,'  const topFindings = sections\n    .filter((item) => item.state !== "ready" || item.scoreImpact > 8)\n    .sort((a, b) => (b.scoreImpact + b.missingCount * 3) - (a.scoreImpact + a.missingCount * 3))\n    .slice(0, 7)\n    .map((item) => findingFromSection(locale, item));','  // Section state describes evidence readiness, not an adverse vulnerability finding.\n  // Never convert missing/blocked/partial evidence into vulnerability severity.\n  const evidenceGaps = sections\n    .filter((item) => item.state !== "ready")\n    .sort((a, b) => (b.scoreImpact + b.missingCount * 3) - (a.scoreImpact + a.missingCount * 3))\n    .slice(0, 7)\n    .map((item) => evidenceGapFromSection(locale, item));\n  const topFindings: Pass2578TopFinding[] = [];','assembler:derive')
s=replace_once(s,'    `Evidence: evidence=${totalEvidence}; missing=${totalMissing}; topFindings=${topFindings.length}; advancedActions=${advancedQueue.length}`,','    `Evidence: evidence=${totalEvidence}; missing=${totalMissing}; verifiedFindings=${topFindings.length}; evidenceGaps=${evidenceGaps.length}; advancedActions=${advancedQueue.length}`,','assembler:pdf-line')
s=replace_once(s,'        `Pro PDF powinien zawierać ${proPdfSections.length} sekcji i ${topFindings.length} głównych findingów przed finalnym layoutem.`,\n        `Pro PDF sollte ${proPdfSections.length} Sektionen und ${topFindings.length} Hauptfindings vor finalem Layout enthalten.`,\n        `Pro PDF should include ${proPdfSections.length} sections and ${topFindings.length} top findings before final layout.`,','        `Pro PDF powinien zawierać ${proPdfSections.length} sekcji, ${evidenceGaps.length} jawnych luk dowodowych i ${topFindings.length} zweryfikowanych adverse findings. Luki dowodowe nie są findingami podatności.`,\n        `Pro PDF sollte ${proPdfSections.length} Sektionen, ${evidenceGaps.length} explizite Evidenzlücken und ${topFindings.length} verifizierte adverse Findings enthalten. Evidenzlücken sind keine Schwachstellen-Findings.`,\n        `Pro PDF should include ${proPdfSections.length} sections, ${evidenceGaps.length} explicit evidence gaps and ${topFindings.length} verified adverse findings. Evidence gaps are not vulnerability findings.`,','assembler:verdict')
s=replace_once(s,'      proPdfSections: proPdfSections.length,\n      advancedActions: advancedQueue.length,\n    },','      proPdfSections: proPdfSections.length,\n      advancedActions: advancedQueue.length,\n      verifiedFindings: topFindings.length,\n      evidenceGaps: evidenceGaps.length,\n    },','assembler:summary')
s=replace_once(s,'    advancedQueue,\n    topFindings,\n    proPdfLines,','    advancedQueue,\n    topFindings,\n    evidenceGaps,\n    proPdfLines,','assembler:return')
p.write_text(s,encoding='utf-8',newline='')

p=root/'lib/security/audit-report-customer-projection.ts'; s=p.read_text(encoding='utf-8')
s=replace_once(s,'  const topFindings = report.topFindings\n    .filter((finding) => visibleIds.has(finding.id.replace(/^finding-/, "")))\n    .map((finding) => ({\n      ...finding,\n      publicLine: clean(finding.publicLine),\n      proLine: deliveredTier === "basic" ? clean(finding.publicLine) : clean(finding.proLine),\n      advancedAction: deliveredTier === "basic" ? safeLockedAction(report.locale) : clean(finding.advancedAction),\n      sourceFamily: clean(finding.sourceFamily, 100) || "evidence-bound-source",\n    }));\n  const advancedQueue: string[] = [];','  const topFindings = report.topFindings\n    .filter((finding) => visibleIds.has(finding.id.replace(/^finding-/, "")))\n    .map((finding) => ({\n      ...finding,\n      publicLine: clean(finding.publicLine),\n      proLine: deliveredTier === "basic" ? clean(finding.publicLine) : clean(finding.proLine),\n      advancedAction: deliveredTier === "basic" ? safeLockedAction(report.locale) : clean(finding.advancedAction),\n      sourceFamily: clean(finding.sourceFamily, 100) || "evidence-bound-source",\n    }));\n  const evidenceGaps = report.evidenceGaps\n    .filter((gap) => visibleIds.has(gap.id.replace(/^gap-/, "")))\n    .map((gap) => ({\n      ...gap,\n      publicLine: clean(gap.publicLine),\n      proLine: deliveredTier === "basic" ? clean(gap.publicLine) : clean(gap.proLine),\n      advancedAction: deliveredTier === "basic" ? safeLockedAction(report.locale) : clean(gap.advancedAction),\n      sourceFamily: clean(gap.sourceFamily, 100) || "evidence-bound-source",\n    }));\n  const advancedQueue: string[] = [];','projection:gaps')
s=replace_once(s,'    advancedQueue,\n    topFindings,\n    proPdfLines,','    advancedQueue,\n    topFindings,\n    evidenceGaps,\n    proPdfLines,','projection:return')
s=replace_once(s,'      sectionsHidden: report.sections.length - sections.length,\n    },','      sectionsHidden: report.sections.length - sections.length,\n      evidenceGapsHidden: report.evidenceGaps.length - evidenceGaps.length,\n    },','projection:hidden')
p.write_text(s,encoding='utf-8',newline='')

p=root/'lib/security/audit-account-customer-snapshot.ts'; s=p.read_text(encoding='utf-8')
s=replace_once(s,'  const projectedFindings = pipeline.projection.report.topFindings.slice(0, 8);\n  const findingLines = projectedFindings.map((finding) => {\n    const detail = pipeline.deliveredTier === "basic" ? finding.publicLine : finding.proLine;\n    return `Finding [${finding.severity.toUpperCase()}] ${finding.title}: ${detail} | source=${finding.sourceFamily}`;\n  });\n  const findingActions = pipeline.deliveredTier === "basic"\n    ? []\n    : projectedFindings.map((finding) => `Finding action - ${finding.title}: ${finding.advancedAction}`);','  const projectedFindings = pipeline.projection.report.topFindings.slice(0, 8);\n  const projectedEvidenceGaps = pipeline.projection.report.evidenceGaps.slice(0, 8);\n  const findingLines = projectedFindings.map((finding) => {\n    const detail = pipeline.deliveredTier === "basic" ? finding.publicLine : finding.proLine;\n    return `Verified finding [${finding.severity.toUpperCase()}] ${finding.title}: ${detail} | source=${finding.sourceFamily}`;\n  });\n  const evidenceGapLines = projectedEvidenceGaps.map((gap) => {\n    const detail = pipeline.deliveredTier === "basic" ? gap.publicLine : gap.proLine;\n    return `Evidence gap [priority=${gap.priority.toUpperCase()}] ${gap.title}: ${detail} | source=${gap.sourceFamily}`;\n  });\n  const findingActions = pipeline.deliveredTier === "basic"\n    ? []\n    : projectedFindings.map((finding) => `Verified finding action - ${finding.title}: ${finding.advancedAction}`);\n  const evidenceGapActions = pipeline.deliveredTier === "basic"\n    ? []\n    : projectedEvidenceGaps.map((gap) => `Evidence gap action - ${gap.title}: ${gap.advancedAction}`);','snapshot:render')
s=replace_once(s,'    ...decisionSections.map((section) => `${section.title}: ${section.summary}`),\n    ...findingLines,\n    ...sourceTruthLines,','    ...decisionSections.map((section) => `${section.title}: ${section.summary}`),\n    ...findingLines,\n    ...evidenceGapLines,\n    ...sourceTruthLines,','snapshot:sections')
s=replace_once(s,'  const nextSteps = unique([...decisionSections.flatMap((section) => section.actions), ...findingActions], 24);','  const nextSteps = unique([...decisionSections.flatMap((section) => section.actions), ...findingActions, ...evidenceGapActions], 24);','snapshot:actions')
p.write_text(s,encoding='utf-8',newline='')

p=root/'lib/security/audit-customer-report-pipeline.ts'; s=p.read_text(encoding='utf-8')
s=replace_once(s,'          findings: args.report.topFindings.map((finding) => ({\n            id: finding.id,\n            severity: finding.severity,\n            sourceFamily: finding.sourceFamily,\n          })),\n          strictUpstreamRoots: strictUpstreams,','          findings: args.report.topFindings.map((finding) => ({\n            id: finding.id,\n            truthClass: finding.truthClass,\n            severity: finding.severity,\n            sourceFamily: finding.sourceFamily,\n          })),\n          evidenceGaps: args.report.evidenceGaps.map((gap) => ({\n            id: gap.id,\n            truthClass: gap.truthClass,\n            priority: gap.priority,\n            state: gap.state,\n            sourceFamily: gap.sourceFamily,\n          })),\n          strictUpstreamRoots: strictUpstreams,','pipeline:graph')
p.write_text(s,encoding='utf-8',newline='')

p=root/'lib/server/security-route-modules/audit-report-assembler.ts'; s=p.read_text(encoding='utf-8')
s=replace_once(s,'    topFindings: customerPipeline.projection.report.topFindings,\n    visualMergeContract: customerPipeline.projection.report.visualMergeContract,','    topFindings: customerPipeline.projection.report.topFindings,\n    evidenceGaps: customerPipeline.projection.report.evidenceGaps,\n    visualMergeContract: customerPipeline.projection.report.visualMergeContract,','server:response')
p.write_text(s,encoding='utf-8',newline='')

for rel,(_,_,after_sha,after_bytes) in FILES.items():
    b=(root/rel).read_bytes()
    if len(b)!=after_bytes or sha(b)!=after_sha: raise SystemExit(f'P71 output file mismatch:{rel}:{len(b)}:{sha(b)}')
current=projection(root,manifest); current_no_files={k:v for k,v in current.items() if k!='files'}
if current_no_files != EXPECTED_OUTPUT: raise SystemExit(f'P71 output projection mismatch:{current_no_files}')
outm=dict(manifest); outm['files']=current.pop('files'); outm['projection']=current
outm['p71AuditFindingTruthBoundary']={'status':'PASS_CONTROLLED_PRODUCT_SOURCE_REPAIR_NO_PROMOTION','changedFiles':5,'verifiedFindingsFromEvidenceReadinessSections':0,'evidenceGapsSeparated':True,'truthBoundary':'Evidence readiness states are not vulnerability findings. Only future explicitly verified adverse findings may populate topFindings and vulnerability severity. Current section-derived issues are evidenceGaps with review priority only.','customerFinalOutputCredit':0,'auditFinalCustomerPdfCredit':0,'rightsCredit':0,'saleCredit':0,'live':False}
Path(a.output_manifest).write_text(json.dumps(outm,indent=2)+'\n',encoding='utf-8')
receipt={'schemaVersion':'velmere.p71.audit-finding-truth-source-repair.v1','status':'PASS_CONTROLLED_PRODUCT_SOURCE_REPAIR_NO_PROMOTION','parentProjection':EXPECTED_PARENT,'outputProjection':EXPECTED_OUTPUT,'changedFiles':[{'path':rel,'beforeSha256':v[0],'beforeBytes':v[1],'afterSha256':v[2],'afterBytes':v[3]} for rel,v in FILES.items()],'rootCause':'The Audit report assembler converted evidence readiness states (missing/blocked/partial) into topFindings with vulnerability-like severity. This could make an evidence gap look like an adverse security finding.','repair':'Keep verified adverse findings and evidence gaps as separate semantic classes. Section-derived readiness gaps now populate evidenceGaps with review priority, while topFindings remains reserved for explicitly verified adverse findings and is empty in the current assembler. Customer snapshots label gaps as Evidence gap, not Finding.','securityBoundary':'No entitlement, provider, risk, rights, or sale gate is relaxed. This is a fail-closed truthfulness repair.','customerFinalOutputCredit':0,'auditFinalCustomerPdfCredit':0,'rightsCredit':0,'saleCredit':0,'live':False}
Path(a.receipt).parent.mkdir(parents=True,exist_ok=True); Path(a.receipt).write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8'); print(json.dumps(receipt,indent=2))
