export const pass272HolderConcentrationGateDelta = {
  id: "PASS272",
  title: "Holder concentration gate for whale, CEX, LP, team, unknown and freshness lanes",
  touched: [
    {
      id: "L01",
      area: "Holder feed",
      previous: 44,
      current: 50,
      change: 6,
      note: "Token modal now exposes a holder concentration gate with whale, labels, LP/depth, team, unknown and freshness lanes while real chain/indexer integration remains the next adapter step.",
    },
    {
      id: "C06",
      area: "Risk scoring UI",
      previous: 72,
      current: 76,
      change: 4,
      note: "Holder score is no longer a hidden number; source gaps and wallet-label uncertainty are visible in the compact scoring rail.",
    },
    {
      id: "D13",
      area: "AI risk signal ontology",
      previous: 72,
      current: 74,
      change: 2,
      note: "Holder ontology is split into whales, wallet labels, LP/depth, team/treasury, unknown wallets and freshness instead of one generic holder label.",
    },
    {
      id: "D15",
      area: "Risk driver mapping",
      previous: 88,
      current: 89,
      change: 1,
      note: "Holder concentration, wallet labels, LP/depth and unknown clusters become explicit risk drivers.",
    },
    {
      id: "D16",
      area: "Source confidence lanes",
      previous: 92,
      current: 93,
      change: 1,
      note: "Holder live/proxy/missing counts are surfaced directly in the modal before any stronger readout.",
    },
    {
      id: "D17",
      area: "Missing-data semantics",
      previous: 95,
      current: 96,
      change: 1,
      note: "Missing holder labels and missing source freshness increase review pressure instead of creating a clean safety conclusion.",
    },
    {
      id: "M04",
      area: "Safe export wording",
      previous: 88,
      current: 89,
      change: 1,
      note: "Holder language stays framed as label/source review, not as an accusation, guarantee or investment signal.",
    },
  ],
  guardMarkers: [
    "data-pass272-holder-concentration-gate",
    "velmere_holder_concentration_v1_pass272",
    "holder concentration gate",
    "whales",
    "CEX/custody wallet labels",
    "LP/depth",
    "unknown wallets",
    "freshness",
  ],
} as const;
