export const pass276SourceAdapterQuorumGateDelta = {
  id: "PASS276",
  title: "Source adapter quorum circuit breaker for timeout/fallback/freshness policy",
  touched: [
    {
      id: "L06",
      area: "Adapter timeouts / fallbacks",
      previous: 64,
      current: 72,
      change: 8,
      note: "The token modal now exposes adapter quorum, timeout/error state, freshness TTL, fallback count, retry window and reviewer seal as a visible circuit breaker rail.",
    },
    {
      id: "K02",
      area: "Source freshness registry",
      previous: 54,
      current: 58,
      change: 4,
      note: "Freshness minutes, source TTL and stale/fallback pressure are prepared as structured fields for a future durable source registry.",
    },
    {
      id: "D16",
      area: "Source confidence lanes",
      previous: 93,
      current: 95,
      change: 2,
      note: "Source confidence is no longer just live/partial/demo: quorum, retry, fallback and reviewer seal are separate visible lanes.",
    },
    {
      id: "D17",
      area: "Missing-data semantics",
      previous: 96,
      current: 98,
      change: 2,
      note: "Missing chart source, orderbook, freshness or reviewer seal raises source-gap pressure instead of becoming confidence.",
    },
    {
      id: "C06",
      area: "Risk scoring UI",
      previous: 76,
      current: 78,
      change: 2,
      note: "Risk UI now shows whether the source backbone is healthy before stronger Basic/Pro/Advanced readouts are trusted.",
    },
    {
      id: "M04",
      area: "Safe export wording",
      previous: 92,
      current: 93,
      change: 1,
      note: "The adapter circuit breaker uses anti-FOMO review language and blocks safety, certainty and investment-signal wording.",
    },
  ],
  guardMarkers: [
    "data-pass276-source-adapter-quorum-gate",
    "velmere_source_adapter_quorum_gate_v1_pass276",
    "adapter circuit breaker active",
    "shield-pass276-source-quorum-gate",
  ],
} as const;
