export const pass269ChartDockAssetRegimeDelta = {
  id: "PASS269",
  title: "Compact mode dock + asset-regime reserve gate + direct chart drag correction",
  touched: [
    {
      id: "C07",
      area: "Chart engine",
      previous: 91,
      current: 92,
      change: 1,
      note: "Pointer drag math was corrected after screenshot QA: visible chart movement now follows the hand direction instead of feeling inverted.",
    },
    {
      id: "C08",
      area: "Token modal shell",
      previous: 94,
      current: 95,
      change: 1,
      note: "The VLM mode side panel is now a compact action dock without long description blocks or redundant OPIS UI.",
    },
    {
      id: "C09",
      area: "Stablecoin / pegged asset behavior",
      previous: 35,
      current: 40,
      change: 5,
      note: "A first asset-regime classifier now separates stable/pegged, commodity-backed, major and contract-token review gates before deeper live adapters exist.",
    },
    {
      id: "D18",
      area: "Basic / Pro / Advanced depth contract",
      previous: 91,
      current: 92,
      change: 1,
      note: "Basic/Pro/Advanced remain direct actions while the new compact regime strip explains which proof gate applies to the selected asset.",
    },
    {
      id: "J02",
      area: "Accessibility / ARIA",
      previous: 63,
      current: 64,
      change: 1,
      note: "Removing paragraph-heavy description sections lowers keyboard and visual scanning load in the modal side dock.",
    },
    {
      id: "M04",
      area: "Safe export wording",
      previous: 87,
      current: 88,
      change: 1,
      note: "Reserve/peg/custody language is framed as proof gates and source requirements, not a safety certificate or buy signal.",
    },
  ],
  guardMarkers: [
    "data-pass269-compact-mode-dock",
    "data-pass269-asset-regime-gate",
    "data-pass269-direct-drag-fix=visual-follows-hand",
    "velmere_asset_regime_v1_pass269",
  ],
} as const;
