export const pass277SourcePolicyAllowlistGateDelta = {
  id: "PASS277",
  title: "Source policy allowlist passport gate for trusted-source governance",
  touched: [
    {
      id: "L07",
      area: "Allowlists / source policy",
      previous: 44,
      current: 53,
      change: 9,
      note: "The token modal now exposes allowlist count, provenance, second-source class, conflict lanes, privacy boundary and a private proof passport before stronger readouts.",
    },
    {
      id: "K02",
      area: "Source freshness registry",
      previous: 58,
      current: 61,
      change: 3,
      note: "Trusted source classes, source owners and evidence-use labels are prepared for durable source registry storage.",
    },
    {
      id: "D16",
      area: "Source confidence lanes",
      previous: 95,
      current: 96,
      change: 1,
      note: "Source confidence now distinguishes trusted preview, second-source, operator-only and blocked-until-review policy lanes.",
    },
    {
      id: "D17",
      area: "Missing-data semantics",
      previous: 98,
      current: 99,
      change: 1,
      note: "Unknown, fallback or single-source inputs remain blockers and cannot become public confidence or safety language.",
    },
    {
      id: "K05",
      area: "Privacy redaction envelope",
      previous: 70,
      current: 73,
      change: 3,
      note: "The private proof passport adds an explicit no-raw-payload customer boundary and privacy-safe evidence-use language.",
    },
    {
      id: "M04",
      area: "Safe export wording",
      previous: 93,
      current: 94,
      change: 1,
      note: "The new source policy gate blocks urgency, safety-certification and investment-signal phrasing while preserving anti-FOMO review cues.",
    },
  ],
  guardMarkers: [
    "data-pass277-source-policy-allowlist-gate",
    "velmere_source_policy_allowlist_gate_v1_pass277",
    "source policy quarantine",
    "private source passport",
    "shield-pass277-source-policy-gate",
  ],
} as const;
