export const pass275OsintNarrativeGateDelta = {
  id: "PASS275",
  title: "OSINT narrative quarantine gate for social/news/KOL source pressure",
  touched: [
    {
      id: "L05",
      area: "OSINT feed",
      previous: 40,
      current: 48,
      change: 8,
      note: "The token modal now has an OSINT narrative quarantine gate separating attention, KOL disclosure, official proof, news context, cooldown and source freshness.",
    },
    {
      id: "E04",
      area: "Narrative Radar",
      previous: 30,
      current: 36,
      change: 6,
      note: "Narrative/social/hype is now a proof-halo review lane instead of a vague hype label.",
    },
    {
      id: "D13",
      area: "AI risk signal ontology",
      previous: 76,
      current: 78,
      change: 2,
      note: "OSINT attention, paid disclosure, official claims, news context and anti-FOMO cooldown become separate ontology cues.",
    },
    {
      id: "D17",
      area: "Missing-data semantics",
      previous: 98,
      current: 99,
      change: 1,
      note: "Missing OSINT source, disclosure, freshness or reviewer note increases source-gap pressure instead of lowering risk.",
    },
    {
      id: "L06",
      area: "Adapter timeouts / fallbacks",
      previous: 48,
      current: 50,
      change: 2,
      note: "OSINT freshness and reviewer metadata are prepared for a future source adapter TTL/fallback policy.",
    },
    {
      id: "M04",
      area: "Safe export wording",
      previous: 91,
      current: 92,
      change: 1,
      note: "The OSINT gate blocks rumor-to-verdict wording, unsupported accusations and investment-signal language.",
    },
  ],
  guardMarkers: [
    "data-pass275-osint-narrative-gate",
    "velmere_osint_narrative_gate_v1_pass275",
    "narrative quarantine active",
    "shield-pass275-osint-gate",
  ],
} as const;
