export const pass278DurableAuditReceiptVaultDelta = {
  id: "PASS278",
  title: "Durable audit receipt vault for redacted case proof and storage lock",
  touched: [
    {
      id: "K01",
      area: "Durable audit ledger",
      previous: 40,
      current: 48,
      change: 8,
      note: "The token modal now generates a redacted case receipt, deterministic receipt fingerprint, receipt lanes and storage-lock blocker before any durable ledger claim.",
    },
    {
      id: "K04",
      area: "Storage adapter contract",
      previous: 36,
      current: 40,
      change: 4,
      note: "The vault makes the missing server-side append adapter explicit instead of allowing UI proof theatre or local-only evidence claims.",
    },
    {
      id: "K05",
      area: "Privacy redaction envelope",
      previous: 73,
      current: 76,
      change: 3,
      note: "Raw wallet/IP/customer payloads are kept out of customer surfaces; the receipt exposes only redacted hashes and review state.",
    },
    {
      id: "K06",
      area: "Operator cases",
      previous: 46,
      current: 49,
      change: 3,
      note: "Case IDs, source passport state, identity envelope and next operator action now form a clear case workflow preview.",
    },
    {
      id: "D16",
      area: "Source confidence lanes",
      previous: 96,
      current: 97,
      change: 1,
      note: "Source policy output is preserved in the audit receipt so confidence remains traceable and review-gated.",
    },
    {
      id: "M05",
      area: "Redacted payload export",
      previous: 76,
      current: 78,
      change: 2,
      note: "The receipt vault adds a customer boundary for redacted-only export language while binary PDF/public export stays locked.",
    },
  ],
  guardMarkers: [
    "data-pass278-durable-audit-receipt-vault",
    "velmere_durable_audit_receipt_vault_v1_pass278",
    "audit ledger write blocked",
    "redacted receipt ready",
    "shield-pass278-audit-vault",
  ],
} as const;
