export const pass280AnalyticsEventTaxonomyGateDelta = {
  id: "PASS280",
  title: "Analytics event taxonomy gate for privacy-safe telemetry, anti-FOMO and Velvet Event Passport",
  touched: [
    {
      id: "K03",
      area: "Analytics event taxonomy",
      previous: 39,
      current: 49,
      change: 10,
      note: "Token modal now has a typed event taxonomy for chart gestures, tier switching, source-gate views, export intent and anti-FOMO cooldown without raw payload capture.",
    },
    {
      id: "K05",
      area: "Privacy redaction envelope",
      previous: 76,
      current: 79,
      change: 3,
      note: "Analytics lanes are aggregate-only, redacted operator or blocked raw payload; customer PII, wallet and raw query storage remain excluded.",
    },
    {
      id: "K06",
      area: "Operator cases",
      previous: 52,
      current: 55,
      change: 3,
      note: "Source repair, export intent and anti-FOMO interactions now produce operator-only review cues instead of public urgency signals.",
    },
    {
      id: "D17",
      area: "Missing-data semantics",
      previous: 100,
      current: 100,
      change: 0,
      note: "Missing identity/source/receipt context stays a telemetry blocker; the area remains capped at 100 while PASS280 adds regression coverage.",
    },
    {
      id: "M05",
      area: "Redacted payload export",
      previous: 80,
      current: 82,
      change: 2,
      note: "Export attempts are telemetry-classified as operator-only or blocked until durable receipt storage and redaction are present.",
    },
    {
      id: "M04",
      area: "Safe export wording",
      previous: 94,
      current: 95,
      change: 1,
      note: "The event taxonomy explicitly bans safety/profit/certification language and converts FOMO into cooldown friction.",
    },
  ],
  guardMarkers: [
    "data-pass280-analytics-event-taxonomy-gate",
    "data-pass280-analytics-event",
    "velmere_analytics_event_taxonomy_gate_v1_pass280",
    "Velvet Event Passport",
    "anti-FOMO cooldown",
    "shield-pass280-analytics-taxonomy",
  ],
} as const;
