export const pass271ContractTrapGateDelta = {
  id: "PASS271",
  title: "Contract-trap gate for owner / proxy / mint / pause / blacklist / tax behavior",
  touched: [
    {
      id: "C11",
      area: "Contract trap behavior",
      previous: 32,
      current: 43,
      change: 11,
      note: "Token modal now includes a compact contract-trap gate that separates address, owner/proxy, mint/pause, blacklist, tax and sell-path review cues.",
    },
    {
      id: "L03",
      area: "Contract analyzer",
      previous: 32,
      current: 35,
      change: 3,
      note: "The analyzer output envelope is now defined in UI, while real per-chain adapter wiring remains blocked until provider selection.",
    },
    {
      id: "D15",
      area: "Risk driver mapping",
      previous: 83,
      current: 85,
      change: 2,
      note: "Contract controls are mapped as explicit drivers rather than hidden inside a generic risk score.",
    },
    {
      id: "D16",
      area: "Source confidence lanes",
      previous: 88,
      current: 89,
      change: 1,
      note: "Missing address, analyzer freshness and tax simulator sources now become visible blockers.",
    },
    {
      id: "D17",
      area: "Missing-data semantics",
      previous: 89,
      current: 90,
      change: 1,
      note: "Missing contract source data increases review pressure and blocks safety-style language.",
    },
    {
      id: "M04",
      area: "Safe export wording",
      previous: 84,
      current: 85,
      change: 1,
      note: "Contract warnings are written as analyzer/review requirements, not allegations or guaranteed safety claims.",
    },
  ],
  guardMarkers: [
    "data-pass271-contract-trap-gate",
    "velmere_contract_trap_v1_pass271",
    "contract_trap_gate",
    "owner/proxy",
    "mint/pause",
    "blacklist",
    "sell path",
  ],
} as const;
