export const pass274UnlockVestingGateDelta = {
  id: "PASS274",
  title: "Unlock / vesting cliff radar gate for future-supply pressure",
  touched: [
    {
      id: "L04",
      area: "Unlock / vesting feed",
      previous: 22,
      current: 31,
      change: 9,
      note: "A dedicated unlock vesting gate now separates float, FDV gap, next cliff, team/advisor lane, cooldown and source proof instead of hiding supply pressure in generic market risk.",
    },
    {
      id: "C06",
      area: "Risk scoring UI",
      previous: 79,
      current: 81,
      change: 2,
      note: "The modal exposes future-supply pressure as a visible scoring rail next to holder, contract, pressure and exit-route gates.",
    },
    {
      id: "D13",
      area: "AI risk signal ontology",
      previous: 74,
      current: 76,
      change: 2,
      note: "Supply overhang, FDV gap, cliff timing, team/advisor vesting and source freshness are now separate ontology cues.",
    },
    {
      id: "D17",
      area: "Missing-data semantics",
      previous: 97,
      current: 98,
      change: 1,
      note: "Missing vesting calendars, unlock percent or supply source increase source-gap pressure instead of creating a clean verdict.",
    },
    {
      id: "L06",
      area: "Adapter timeouts / fallbacks",
      previous: 46,
      current: 48,
      change: 2,
      note: "Unlock source freshness is prepared as a future adapter lane with blocked/source-gap wording until live calendar proof is connected.",
    },
    {
      id: "M04",
      area: "Safe export wording",
      previous: 90,
      current: 91,
      change: 1,
      note: "The unlock gate explicitly avoids buy/sell calls and frames FOMO as a cooldown/review mechanism only.",
    },
  ],
  guardMarkers: [
    "data-pass274-unlock-vesting-gate",
    "velmere_unlock_vesting_gate_v1_pass274",
    "cliff radar gate",
    "shield-pass274-unlock-gate",
  ],
} as const;
