export const pass279SourceFreshnessRegistryGateDelta = {
  id: "PASS279",
  title: "Source freshness registry gate for TTL decay, stale lanes and private freshness seal",
  touched: [
    {
      id: "K02",
      area: "Source freshness registry",
      previous: 61,
      current: 69,
      change: 8,
      note: "The token modal now shows a dedicated freshness registry with chart/depth/policy/receipt/reviewer TTL lanes instead of hiding stale or missing source timestamps.",
    },
    {
      id: "D16",
      area: "Source confidence lanes",
      previous: 97,
      current: 98,
      change: 1,
      note: "Confidence now decays through visible TTL lanes and cannot be elevated when chart/depth/source policy is stale or missing.",
    },
    {
      id: "D17",
      area: "Missing-data semantics",
      previous: 99,
      current: 100,
      change: 1,
      note: "Missing timestamps become review pressure and customer-copy locks, not a clean status or silent fallback.",
    },
    {
      id: "K01",
      area: "Durable audit ledger",
      previous: 48,
      current: 50,
      change: 2,
      note: "The freshness registry links receipt freshness to durable audit status so proof remains storage-aware.",
    },
    {
      id: "K06",
      area: "Operator cases",
      previous: 49,
      current: 52,
      change: 3,
      note: "Operator review now has a clear next action for stale chart/depth/policy/receipt lanes and reviewer seal ownership.",
    },
    {
      id: "M05",
      area: "Redacted payload export",
      previous: 78,
      current: 80,
      change: 2,
      note: "Customer-facing export remains locked to review-pending language unless freshness lanes are inside TTL and redacted receipt proof is present.",
    },
  ],
  guardMarkers: [
    "data-pass279-source-freshness-registry-gate",
    "data-pass279-freshness-entry",
    "velmere_source_freshness_registry_gate_v1_pass279",
    "freshness registry expired",
    "private freshness seal",
    "shield-pass279-freshness-registry",
  ],
} as const;
