export type Pass577ProviderState = "closed" | "half_open" | "open" | "unknown";
export type Pass577ProviderSlo = { version: "pass577-provider-slo-console"; provider: string; state: Pass577ProviderState; retrySuccess: number | null; recoveryMs: number | null; freshnessSeconds: number | null; score: number; label: string; nextAction: string };
const clamp = (value: number) => Math.max(0, Math.min(100, Math.round(value)));
export function buildPass577ProviderSloConsole(input: { provider: string; status?: string | null; freshnessSeconds?: number | null; retrySuccess?: number | null; recoveryMs?: number | null; locale?: string }): Pass577ProviderSlo {
  const locale = input.locale === "de" || input.locale === "en" ? input.locale : "pl"; const status = String(input.status ?? "unknown").toLowerCase();
  const state: Pass577ProviderState = /healthy|live|ready|closed|source_bound/.test(status) ? "closed" : /recover|partial|half|rate_limited|compatibility_adapter/.test(status) ? "half_open" : /error|blocked|down|open|provider_error|unsupported/.test(status) ? "open" : "unknown";
  const retrySuccess = Number.isFinite(input.retrySuccess) ? clamp(Number(input.retrySuccess)) : null; const recoveryMs = Number.isFinite(input.recoveryMs) ? Math.max(0, Math.round(Number(input.recoveryMs))) : null; const freshnessSeconds = Number.isFinite(input.freshnessSeconds) ? Math.max(0, Math.round(Number(input.freshnessSeconds))) : null;
  const freshnessScore = freshnessSeconds === null ? 38 : freshnessSeconds <= 30 ? 100 : freshnessSeconds <= 90 ? 78 : freshnessSeconds <= 180 ? 54 : 22; const stateScore = state === "closed" ? 100 : state === "half_open" ? 62 : state === "open" ? 18 : 36; const retryScore = retrySuccess ?? 45; const recoveryScore = recoveryMs === null ? 45 : recoveryMs <= 1200 ? 100 : recoveryMs <= 5000 ? 72 : recoveryMs <= 15000 ? 44 : 18; const score = clamp(stateScore * .38 + freshnessScore * .27 + retryScore * .2 + recoveryScore * .15);
  const label = locale === "de" ? state === "closed" ? "stabil" : state === "half_open" ? "Erholung" : state === "open" ? "unterbrochen" : "nicht bestätigt" : locale === "en" ? state === "closed" ? "stable" : state === "half_open" ? "recovering" : state === "open" ? "circuit open" : "unconfirmed" : state === "closed" ? "stabilny" : state === "half_open" ? "odzyskiwanie" : state === "open" ? "obwód otwarty" : "brak potwierdzenia";
  const nextAction = locale === "de" ? state === "closed" ? "Freshness und Zweitquelle beobachten." : "Retry prüfen und starke Aussagen bis zur Erholung blockieren." : locale === "en" ? state === "closed" ? "Monitor freshness and the second source." : "Verify a retry and block strong claims until recovery." : state === "closed" ? "Monitoruj świeżość i drugi provider." : "Sprawdź retry i blokuj mocne wnioski do czasu odzyskania źródła.";
  return { version: "pass577-provider-slo-console", provider: input.provider, state, retrySuccess, recoveryMs, freshnessSeconds, score, label, nextAction };
}
