export type Pass575EvidenceSnapshot = { id: string; symbol: string; timestamp: string; sourceState: string; overallRisk: number; confidence: string; blockedBy: readonly string[] };
export type Pass575ShieldMapEvidenceDelta = { version: "pass575-shield-map-evidence-delta"; state: "baseline" | "unchanged" | "changed" | "material_change"; symbol: string; previousSnapshotId: string | null; currentSnapshotId: string | null; riskDelta: number; blockedDelta: number; sourceStateChanged: boolean; confidenceChanged: boolean; addedBlockers: string[]; resolvedBlockers: string[]; headline: string; nextTest: string; boundary: string };
const unique = (values: readonly string[]) => Array.from(new Set(values.map((value) => String(value ?? "").trim()).filter(Boolean))).slice(0, 12);
export function buildPass575ShieldMapEvidenceDelta(input: { previous?: Pass575EvidenceSnapshot | null; current?: Pass575EvidenceSnapshot | null; locale?: string }): Pass575ShieldMapEvidenceDelta {
  const locale = input.locale === "de" || input.locale === "en" ? input.locale : "pl";
  const previous = input.previous ?? null; const current = input.current ?? null; const symbol = current?.symbol || previous?.symbol || "VLM";
  const riskDelta = Math.round((current?.overallRisk ?? 0) - (previous?.overallRisk ?? 0));
  const previousBlocked = unique(previous?.blockedBy ?? []); const currentBlocked = unique(current?.blockedBy ?? []);
  const addedBlockers = currentBlocked.filter((item) => !previousBlocked.includes(item)); const resolvedBlockers = previousBlocked.filter((item) => !currentBlocked.includes(item));
  const blockedDelta = currentBlocked.length - previousBlocked.length; const sourceStateChanged = Boolean(previous && current && previous.sourceState !== current.sourceState); const confidenceChanged = Boolean(previous && current && previous.confidence !== current.confidence);
  const material = Math.abs(riskDelta) >= 12 || addedBlockers.length >= 2 || sourceStateChanged; const changed = material || riskDelta !== 0 || blockedDelta !== 0 || confidenceChanged || resolvedBlockers.length > 0;
  const state = !previous || !current ? "baseline" : material ? "material_change" : changed ? "changed" : "unchanged";
  const copy = locale === "de" ? { baseline: `${symbol}: Basis-Snapshot gespeichert; ein zweiter verifizierter Lauf aktiviert den Delta-Vergleich.`, unchanged: `${symbol}: Keine belastbare Evidenzänderung zwischen den Snapshots.`, changed: `${symbol}: Evidenz geändert; Risiko ${riskDelta >= 0 ? "+" : ""}${riskDelta}, Blocker ${blockedDelta >= 0 ? "+" : ""}${blockedDelta}.`, material_change: `${symbol}: Wesentliche Evidenzänderung; neue Blocker ${addedBlockers.length}.`, next: "Zeitstempel, Quellen-IDs und geänderte Blocker prüfen.", boundary: "Ein Delta beschreibt nur Änderungen zwischen Untersuchungen; kein Preis- oder Sicherheitsurteil." } : locale === "en" ? { baseline: `${symbol}: baseline stored; a second verified run unlocks comparison.`, unchanged: `${symbol}: no material evidence change between snapshots.`, changed: `${symbol}: evidence changed; risk ${riskDelta >= 0 ? "+" : ""}${riskDelta}, blockers ${blockedDelta >= 0 ? "+" : ""}${blockedDelta}.`, material_change: `${symbol}: material evidence change; new blockers ${addedBlockers.length}.`, next: "Verify timestamps, source IDs and changed blockers.", boundary: "A delta only describes change between investigations; it is not a price or safety verdict." } : { baseline: `${symbol}: zapisano snapshot bazowy; drugi zweryfikowany przebieg uruchomi porównanie.`, unchanged: `${symbol}: brak istotnej zmiany dowodów między snapshotami.`, changed: `${symbol}: dowody się zmieniły; ryzyko ${riskDelta >= 0 ? "+" : ""}${riskDelta}, blokery ${blockedDelta >= 0 ? "+" : ""}${blockedDelta}.`, material_change: `${symbol}: istotna zmiana dowodów; nowe blokery ${addedBlockers.length}.`, next: "Sprawdź timestampy, ID źródeł i zmienione blokery.", boundary: "Delta opisuje wyłącznie zmianę między analizami; nie jest prognozą ceny ani werdyktem bezpieczeństwa." };
  return { version: "pass575-shield-map-evidence-delta", state, symbol, previousSnapshotId: previous?.id ?? null, currentSnapshotId: current?.id ?? null, riskDelta, blockedDelta, sourceStateChanged, confidenceChanged, addedBlockers, resolvedBlockers, headline: copy[state], nextTest: copy.next, boundary: copy.boundary };
}
