export const PASS1454_1493_RUNTIME_ARCHITECTURE = {
  version: "pass1454-1493-runtime-architecture",
  releaseName: "mobile-performance-rectangular-terminal",
  standard: "sixty_plus_tasks_real_product_pass",
  publicModalRule:
    "Only the calm rectangular chart + attached Basic/Pro/Advanced rail may render on public Shield and Real Markets surfaces; public bubble/orbit overlay stays disabled until screenshot proof.",
  removedChaos: [
    "stale public bubble/orbit modal cascade",
    "dropdowns without viewport height budget",
    "cart drawer without bottom-sheet proof attributes",
    "chart wheel events escaping into modal/page scroll",
    "mobile one-column depth rail that pushes the chart away",
    "unguarded rectangular modal regressions",
  ],
  uiTasks: [
    "rectangular modal as the only public chart grammar",
    "attached three-button depth rail",
    "mobile compact depth rail",
    "readout row density guard",
    "chart owns wheel/touch/pointer bubbling",
    "modal shell exposes runtime proof attributes",
    "details tray kept secondary",
    "real markets hero stays simple",
    "shield modal stays above header",
    "cart remains bottom sheet",
    "dropdowns stay anchored and bounded",
    "focus rings stay visible",
  ],
  runtimeTasks: [
    "dropdown max-height computed from visual viewport",
    "fallback dropdown never starts at 0,0",
    "outside click returns focus only to visible anchors",
    "chart wheel containment",
    "touch containment for modal chart",
    "pointer move bubble containment",
    "modal scroll region remains single owner",
    "cart opening closes header surfaces",
    "header overlay open events are tagged",
    "reduced motion disables unnecessary transitions",
  ],
  mobileTasks: [
    "safe-area cart sheet",
    "compact chart min-height clamp",
    "three-button depth rail on phone",
    "short depth copy on narrow widths",
    "dropdown width no wider than viewport",
    "modal body padding reduced",
    "reader/table overflow containment",
    "tap targets remain above 44px",
  ],
  qualityTasks: [
    "new verifier checks real source strings, not only files",
    "older pass gates remain green",
    "no npm build is claimed inside timeout sandbox",
    "deploy zip excludes node_modules and .next",
    "progress doc lists remaining proof blockers",
  ],
  taskCount: 66,
  nextProofGate:
    "Run full Node 24 install/build and Playwright screenshots; fix only the failing visible flows before raising to 100%.",
} as const;
