

export const PASS2809_REAL_MARKETS_SERVER_SYMBOL_BUDGET = 12;

export const instruments = {
  btc: "BTC-USD",
  eth: "ETH-USD",
  sol: "SOL-USD",
  bnb: "BNB-USD",
  mx: "MX-USD",
  mexc: "MX-USD",
  okb: "OKB-USD",
  mnt: "MNT-USD",
  xrp: "XRP-USD",
  ada: "ADA-USD",
  aapl: "AAPL",
  nvda: "NVDA",
  msft: "MSFT",
  googl: "GOOGL",
  amzn: "AMZN",
  meta: "META",
  tsla: "TSLA",
  lvmh: "MC.PA",
  amd: "AMD",
  tsm: "TSM",
  avgo: "AVGO",
  gs: "GS",
  bac: "BAC",
  visa: "V",
  mastercard: "MA",
  nvo: "NVO",
  airbus: "AIR.PA",
  bmw: "BMW.DE",
  mercedes: "MBG.DE",
  vw: "VOW3.DE",
  adidas: "ADS.DE",
  loreal: "OR.PA",
  ferrari: "RACE",
  porsche: "P911.DE",
  sony: "SONY",
  shopify: "SHOP",
  doge: "DOGE-USD",
  link: "LINK-USD",
  avax: "AVAX-USD",
  dot: "DOT-USD",
  ltc: "LTC-USD",
  bch: "BCH-USD",
  xlm: "XLM-USD",
  uni: "UNI-USD",
  atom: "ATOM-USD",
  near: "NEAR-USD",
  aave: "AAVE-USD",
  etc: "ETC-USD",
  fil: "FIL-USD",
  icp: "ICP-USD",
  matic: "MATIC-USD",
  pol: "POL-USD",
  trx: "TRX-USD",
  shib: "SHIB-USD",
  pepe: "PEPE-USD",
  arb: "ARB-USD",
  op: "OP-USD",
  lseg: "LSEG.L",
  deutscheboerse: "DB1.DE",
  hkex: "0388.HK",
  eurusd: "EURUSD=X",
  eurpln: "EURPLN=X",
  usdpln: "USDPLN=X",
  usdjpy: "JPY=X",
  gbpusd: "GBPUSD=X",
  eurtry: "EURTRY=X",
  usdtry: "TRY=X",
  eurgbp: "EURGBP=X",
  usdchf: "CHF=X",
  spy: "SPY",
  qqq: "QQQ",
  tlt: "TLT",
  hyg: "HYG",
  efa: "EFA",
  gld: "GLD",
  vnq: "VNQ",
  iyr: "IYR",
  xlre: "XLRE",
  pld: "PLD",
  gold: "GC=F",
  silver: "SI=F",
  wti: "CL=F",
  brent: "BZ=F",
  copper: "HG=F",
  natgas: "NG=F",
  wheat: "ZW=F",
  coin: "COIN",
  cme: "CME",
  ice: "ICE",
  ndaq: "NDAQ",
  coinbase: "COIN",
  eurex: "DB1.DE",
  xetra: "DB1.DE",
  stoxx50: "^STOXX50E",
  nikkei: "^N225",
} as const;

export type InstrumentId = keyof typeof instruments;

export const rangeConfig = {
  "15m": { range: "5d", interval: "15m", maxCandles: 480 },
  "1h": { range: "1mo", interval: "1h", maxCandles: 720 },
  "4h": { range: "3mo", interval: "1h", maxCandles: 720 },
  "1d": { range: "1y", interval: "1d", maxCandles: 365 },
  "1w": { range: "5y", interval: "1wk", maxCandles: 260 },
  "1mo": { range: "10y", interval: "1mo", maxCandles: 180 },
} as const;

export const rangeMeta = {
  "15m": { label: "5D · 15m candles", uiLabel: "5D/15M", changeBasis: "Change is calculated from the first returned 15m candle to the latest close." },
  "1h": { label: "1M · hourly candles", uiLabel: "1M/1H", changeBasis: "Change is calculated from the first returned hourly candle to the latest close." },
  "4h": { label: "3M · hourly candles", uiLabel: "3M/1H", changeBasis: "Yahoo does not provide a native 4h interval here; Velmère shows hourly provider candles over a 3M range." },
  "1d": { label: "1Y · daily candles", uiLabel: "1Y/1D", changeBasis: "Change is calculated from the first returned daily candle to the latest close." },
  "1w": { label: "5Y · weekly macro candles", uiLabel: "5Y/1W", changeBasis: "This is macro weekly history, not the last seven days. Change is calculated from the first weekly candle to the latest close." },
  "1mo": { label: "10Y · monthly macro candles", uiLabel: "10Y/1M", changeBasis: "This is long-horizon monthly history. Change is calculated from the first monthly candle to the latest close." },
} as const;

export const safeSymbol = /^[A-Za-z0-9.^=-]{1,24}$/;
