export type UniversalAssetClass =
  | "crypto"
  | "exchange_token"
  | "stock"
  | "fx"
  | "real_estate"
  | "etf"
  | "commodity";

export type UniversalAssetRow = {
  id: string;
  rank: number;
  symbol: string;
  name: string;
  assetClass: UniversalAssetClass;
  sourceRhythm: string;
  priceLane: string;
  volumeLane: string;
  proofOrDisclosureLane: string;
  secondSourceLane: string;
  riskPressure: number;
  confidenceFloor: number;
  adapterState: "live_first" | "provider_required" | "slow_macro" | "historical_context" | "operator_review" | "daily_reference" | "provider_ready_no_fake_live";
  humanCopy: string;
  nextAdapterStep: string;
  sparkTone: "down" | "up" | "flat" | "watch" | "volatile";
};

export type UniversalAssetMetricContract = {
  id: string;
  label: string;
  appliesTo: UniversalAssetClass[];
  publicLabel: string;
  sourceRequirement: string;
  notAllowed: string;
};

export type UniversalAssetMarketMatrix = {
  version: "PASS345.universal_asset_market_matrix";
  headline: string;
  boundary: string;
  rows: UniversalAssetRow[];
  metricContracts: UniversalAssetMetricContract[];
  botRules: string[];
};

const rows: UniversalAssetRow[] = [
  {
    id: "btc",
    rank: 1,
    symbol: "BTC",
    name: "Bitcoin",
    assetClass: "crypto",
    sourceRhythm: "fast live · 10s–60s",
    priceLane: "Binance/MEXC/Coinbase/Kraken candles + ticker",
    volumeLane: "spot volume + cross-venue spread",
    proofOrDisclosureLane: "orderbook/depth freshness",
    secondSourceLane: "Coinbase/Kraken comparison before confidence rises",
    riskPressure: 32,
    confidenceFloor: 74,
    adapterState: "live_first",
    humanCopy:
      "BTC może działać jak główny punkt odniesienia rynku, ale bot nadal pokazuje świeżość źródeł i porównanie venue zamiast pewnego werdyktu.",
    nextAdapterStep: "Wire Binance/MEXC depth + Coinbase/Kraken second-source candles.",
    sparkTone: "down",
  },
  {
    id: "eth",
    rank: 2,
    symbol: "ETH",
    name: "Ethereum",
    assetClass: "crypto",
    sourceRhythm: "fast live · 10s–60s",
    priceLane: "spot candles + book ticker",
    volumeLane: "venue volume + spread drift",
    proofOrDisclosureLane: "network/token context separate from venue health",
    secondSourceLane: "Coinbase/Kraken comparison",
    riskPressure: 35,
    confidenceFloor: 69,
    adapterState: "live_first",
    humanCopy:
      "ETH wymaga osobnego kontekstu sieci i płynności. Widoczność rynku nie usuwa potrzeby świeżych źródeł.",
    nextAdapterStep: "Normalize ETH pairs across Binance/MEXC/Coinbase/Kraken.",
    sparkTone: "down",
  },
  {
    id: "bnb",
    rank: 3,
    symbol: "BNB",
    name: "BNB",
    assetClass: "exchange_token",
    sourceRhythm: "fast live + exchange-token review",
    priceLane: "candles + exchange-linked token lane",
    volumeLane: "liquidity + venue concentration",
    proofOrDisclosureLane: "native-token dependency review",
    secondSourceLane: "second venue price/depth + reserve/liability boundary",
    riskPressure: 44,
    confidenceFloor: 58,
    adapterState: "operator_review",
    humanCopy:
      "Token powiązany z giełdą musi mieć dodatkową kontrolę zależności. To nie jest oskarżenie — to osobny pas dowodowy.",
    nextAdapterStep: "Add native-token dependency lane and compare with exchange health table.",
    sparkTone: "watch",
  },
  {
    id: "usdt",
    rank: 4,
    symbol: "USDT",
    name: "Tether",
    assetClass: "crypto",
    sourceRhythm: "fast live + reserve reference",
    priceLane: "peg spread across venues",
    volumeLane: "stablecoin depth + venue spread",
    proofOrDisclosureLane: "reserve/disclosure context + timestamp",
    secondSourceLane: "USDC/FX bridge + multi-venue peg",
    riskPressure: 39,
    confidenceFloor: 62,
    adapterState: "operator_review",
    humanCopy:
      "Stablecoin wymaga innego skanu: peg, głębokość rynku i źródła rezerw są ważniejsze niż zwykły wykres ceny.",
    nextAdapterStep: "Build stablecoin peg bridge and reserve timestamp parser.",
    sparkTone: "flat",
  },
  {
    id: "aapl",
    rank: 5,
    symbol: "AAPL",
    name: "Apple",
    assetClass: "stock",
    sourceRhythm: "market provider + SEC disclosure",
    priceLane: "stock candles after provider key",
    volumeLane: "daily/15m volume + gap check",
    proofOrDisclosureLane: "SEC filings / corporate events",
    secondSourceLane: "price provider ↔ SEC event timestamp",
    riskPressure: 28,
    confidenceFloor: 52,
    adapterState: "provider_required",
    humanCopy:
      "Apple czytamy przez cenę, wolumen, eventy produktowe i filing — bez klucza providera pokazujemy tylko spokojny preview, nie świeżą cenę.",
    nextAdapterStep: "Attach market data provider, SEC company facts/submissions lane and product-event calendar.",
    sparkTone: "flat",
  },
  {
    id: "nvda",
    rank: 6,
    symbol: "NVDA",
    name: "Nvidia",
    assetClass: "stock",
    sourceRhythm: "market provider + SEC disclosure",
    priceLane: "stock candles after provider key",
    volumeLane: "volume spike + sector basket",
    proofOrDisclosureLane: "earnings/filing timestamp",
    secondSourceLane: "price provider ↔ SEC disclosure lane",
    riskPressure: 42,
    confidenceFloor: 50,
    adapterState: "provider_required",
    humanCopy:
      "Nvidia wymaga osobnej kontroli sektora AI/semis: bot rozdziela hype, wolumen, peer basket i filing/event timestamp.",
    nextAdapterStep: "Add semiconductor peer basket, earnings-event parser and provider timestamp.",
    sparkTone: "watch",
  },
  {
    id: "mc-pa",
    rank: 7,
    symbol: "MC.PA",
    name: "LVMH proxy watch",
    assetClass: "stock",
    sourceRhythm: "EU stock provider + company disclosure",
    priceLane: "EU equity candles after provider key",
    volumeLane: "luxury sector peer context",
    proofOrDisclosureLane: "issuer disclosure / earnings calendar",
    secondSourceLane: "price provider ↔ issuer/news disclosure",
    riskPressure: 31,
    confidenceFloor: 48,
    adapterState: "provider_required",
    humanCopy:
      "LVMH/luxury proxy jest tłem dla rynku premium: sektor, disclosure i rhythm brandu — bez sygnału kupna lub sprzedaży.",
    nextAdapterStep: "Attach EU equity provider, issuer news/disclosure and luxury peer basket.",
    sparkTone: "flat",
  },
  {
    id: "eur-usd",
    rank: 8,
    symbol: "EUR/USD",
    name: "Euro / US Dollar",
    assetClass: "fx",
    sourceRhythm: "daily reference + future intraday",
    priceLane: "ECB reference + intraday FX provider later",
    volumeLane: "FX volatility band, not exchange volume",
    proofOrDisclosureLane: "reference-rate timestamp",
    secondSourceLane: "ECB ↔ intraday FX provider",
    riskPressure: 30,
    confidenceFloor: 56,
    adapterState: "provider_required",
    humanCopy:
      "Waluty są tłem płynności. Kurs referencyjny nie jest ceną transakcyjną, więc bot pokazuje rytm źródła przed wnioskiem.",
    nextAdapterStep: "Add intraday FX provider and stablecoin peg bridge.",
    sparkTone: "flat",
  },
  {
    id: "dxy-proxy",
    rank: 9,
    symbol: "DXY",
    name: "US Dollar pressure proxy",
    assetClass: "fx",
    sourceRhythm: "daily/intraday provider required",
    priceLane: "dollar pressure proxy",
    volumeLane: "macro liquidity context",
    proofOrDisclosureLane: "source timestamp + methodology",
    secondSourceLane: "FX provider ↔ macro series",
    riskPressure: 37,
    confidenceFloor: 44,
    adapterState: "provider_required",
    humanCopy:
      "Silniejszy dolar może tłumaczyć presję na crypto i akcje, ale bot nie zrobi z tego samodzielnego alarmu.",
    nextAdapterStep: "Wire dollar index proxy and macro liquidity rules.",
    sparkTone: "watch",
  },
  {
    id: "reit-vnq",
    rank: 10,
    symbol: "VNQ",
    name: "REIT basket proxy",
    assetClass: "real_estate",
    sourceRhythm: "daily ETF proxy + slow macro",
    priceLane: "REIT/ETF price provider later",
    volumeLane: "REIT volume + credit stress proxy",
    proofOrDisclosureLane: "macro release date / REIT holdings boundary",
    secondSourceLane: "REIT proxy ↔ FRED/FHFA macro series",
    riskPressure: 41,
    confidenceFloor: 48,
    adapterState: "slow_macro",
    humanCopy:
      "Nieruchomości to wolniejsze tło makro. Bot może pokazać presję otoczenia, ale nie sekundowy alarm.",
    nextAdapterStep: "Attach REIT proxy + FRED/FHFA release calendar.",
    sparkTone: "watch",
  },
  {
    id: "spy",
    rank: 11,
    symbol: "SPY",
    name: "S&P 500 ETF proxy",
    assetClass: "etf",
    sourceRhythm: "market provider + holdings cadence",
    priceLane: "ETF candles after provider key",
    volumeLane: "broad market volume",
    proofOrDisclosureLane: "holdings/fund disclosure cadence",
    secondSourceLane: "ETF price ↔ equity basket stress",
    riskPressure: 36,
    confidenceFloor: 50,
    adapterState: "provider_required",
    humanCopy:
      "ETF-y pokażą, czy ruch jest lokalny czy szeroki. To warstwa kontekstu, nie porada inwestycyjna.",
    nextAdapterStep: "Attach ETF price/holdings provider and sector basket.",
    sparkTone: "flat",
  },
  {
    id: "xau-usd",
    rank: 12,
    symbol: "XAU/USD",
    name: "Gold",
    assetClass: "commodity",
    sourceRhythm: "commodity provider required",
    priceLane: "gold spot/futures provider later",
    volumeLane: "macro hedge context",
    proofOrDisclosureLane: "provider timestamp + contract/source method",
    secondSourceLane: "commodity provider ↔ FX/rates context",
    riskPressure: 34,
    confidenceFloor: 42,
    adapterState: "provider_required",
    humanCopy:
      "Surowce będą tłem makro. Bez źródła live bot nie udaje mocnego wniosku ani ceny transakcyjnej.",
    nextAdapterStep: "Attach commodity provider and normalize XAU/XAG/OIL symbols.",
    sparkTone: "flat",
  },
  {
    id: "msft",
    rank: 13,
    symbol: "MSFT",
    name: "Microsoft",
    assetClass: "stock",
    sourceRhythm: "market provider + SEC disclosure",
    priceLane: "stock candles after provider key",
    volumeLane: "AI/cloud sector basket",
    proofOrDisclosureLane: "SEC filings / earnings timestamp",
    secondSourceLane: "price provider ↔ filing/news timestamp",
    riskPressure: 29,
    confidenceFloor: 52,
    adapterState: "provider_required",
    humanCopy: "Microsoft czytamy przez cloud/AI basket, wolumen i SEC filings; karta ma być użyteczna bez udawania live ceny.",
    nextAdapterStep: "Add equity provider, earnings calendar, cloud/AI peer basket and source timestamp.",
    sparkTone: "flat",
  },
  {
    id: "coin",
    rank: 14,
    symbol: "COIN",
    name: "Coinbase Global",
    assetClass: "stock",
    sourceRhythm: "market provider + SEC disclosure + exchange exposure",
    priceLane: "stock candles after provider key",
    volumeLane: "equity volume + crypto beta context",
    proofOrDisclosureLane: "SEC filings / exchange operator disclosure",
    secondSourceLane: "equity price ↔ crypto venue health",
    riskPressure: 45,
    confidenceFloor: 49,
    adapterState: "operator_review",
    humanCopy: "Spółki powiązane z rynkiem crypto idą do osobnego pasa: cena akcji, filing i stres giełd nie są mieszane w jeden werdykt.",
    nextAdapterStep: "Add public-company exposure lane and exchange-operator peer basket.",
    sparkTone: "watch",
  },
  {
    id: "jpm",
    rank: 15,
    symbol: "JPM",
    name: "JPMorgan Chase",
    assetClass: "stock",
    sourceRhythm: "market provider + SEC/bank disclosure",
    priceLane: "stock candles after provider key",
    volumeLane: "banking sector stress proxy",
    proofOrDisclosureLane: "filing/disclosure lane",
    secondSourceLane: "price provider ↔ sector/credit stress",
    riskPressure: 33,
    confidenceFloor: 50,
    adapterState: "provider_required",
    humanCopy: "JPM pokazuje bankowo-płynnościowe tło rynku: filing, sektor i credit stress proxy, bez prostego werdyktu o rynku.",
    nextAdapterStep: "Add bank sector basket, credit stress proxy and filing-event parser.",
    sparkTone: "flat",
  },
  {
    id: "eur-pln",
    rank: 16,
    symbol: "EUR/PLN",
    name: "Euro / Polish Zloty",
    assetClass: "fx",
    sourceRhythm: "daily reference + future intraday",
    priceLane: "reference + FX provider later",
    volumeLane: "FX volatility band",
    proofOrDisclosureLane: "reference-rate timestamp",
    secondSourceLane: "reference ↔ intraday FX provider",
    riskPressure: 31,
    confidenceFloor: 54,
    adapterState: "provider_required",
    humanCopy: "Waluty regionalne pokazują tło kosztów, płynności i cen importu, ale nie są sekundowym alarmem giełdowym.",
    nextAdapterStep: "Add intraday FX provider and holiday calendar.",
    sparkTone: "flat",
  },
  {
    id: "usd-jpy",
    rank: 17,
    symbol: "USD/JPY",
    name: "Dollar / Yen",
    assetClass: "fx",
    sourceRhythm: "daily/intraday provider required",
    priceLane: "FX provider later",
    volumeLane: "macro risk-on/risk-off context",
    proofOrDisclosureLane: "source timestamp + methodology",
    secondSourceLane: "FX provider ↔ rates/macro context",
    riskPressure: 39,
    confidenceFloor: 47,
    adapterState: "provider_required",
    humanCopy: "USD/JPY może pokazać stres makro, ale bot oddziela go od token-specific risk.",
    nextAdapterStep: "Add FX volatility bands and macro correlation rules.",
    sparkTone: "watch",
  },
  {
    id: "xag-usd",
    rank: 18,
    symbol: "XAG/USD",
    name: "Silver",
    assetClass: "commodity",
    sourceRhythm: "commodity provider required",
    priceLane: "silver spot/futures provider later",
    volumeLane: "macro/industrial demand proxy",
    proofOrDisclosureLane: "provider timestamp + contract/source method",
    secondSourceLane: "commodity provider ↔ FX/rates context",
    riskPressure: 37,
    confidenceFloor: 42,
    adapterState: "provider_required",
    humanCopy: "Srebro dostaje wiersz jak crypto, ale live ceny wymagają providera i second-source boundary.",
    nextAdapterStep: "Attach commodity feed and normalize XAG symbols.",
    sparkTone: "watch",
  },
  {
    id: "wti",
    rank: 19,
    symbol: "WTI",
    name: "Crude oil proxy",
    assetClass: "commodity",
    sourceRhythm: "commodity provider required",
    priceLane: "oil futures/spot provider later",
    volumeLane: "inflation/energy stress proxy",
    proofOrDisclosureLane: "provider timestamp + contract/source method",
    secondSourceLane: "commodity provider ↔ macro context",
    riskPressure: 40,
    confidenceFloor: 41,
    adapterState: "provider_required",
    humanCopy: "Ropa jest tłem makro dla inflacji i ryzyka rynku, nie samodzielnym werdyktem Shield.",
    nextAdapterStep: "Attach energy commodity provider and macro stress rules.",
    sparkTone: "watch",
  },
  {
    id: "usd-pln",
    rank: 20,
    symbol: "USD/PLN",
    name: "Dollar / Polish Zloty",
    assetClass: "fx",
    sourceRhythm: "daily reference + future intraday",
    priceLane: "reference + FX provider later",
    volumeLane: "FX volatility band",
    proofOrDisclosureLane: "reference-rate timestamp",
    secondSourceLane: "reference ↔ intraday FX provider",
    riskPressure: 34,
    confidenceFloor: 53,
    adapterState: "provider_required",
    humanCopy: "USD/PLN dodaje kontekst kosztów importu i presji dolara dla użytkowników w Polsce; to nie jest sygnał transakcyjny.",
    nextAdapterStep: "Add official reference timestamp and intraday FX provider comparison.",
    sparkTone: "watch",
  },
  {
    id: "qqq",
    rank: 21,
    symbol: "QQQ",
    name: "Nasdaq 100 ETF proxy",
    assetClass: "etf",
    sourceRhythm: "market provider + holdings cadence",
    priceLane: "ETF candles after provider key",
    volumeLane: "tech/growth volume context",
    proofOrDisclosureLane: "fund/holdings cadence",
    secondSourceLane: "ETF price ↔ mega-cap basket",
    riskPressure: 39,
    confidenceFloor: 49,
    adapterState: "provider_required",
    humanCopy: "QQQ pokazuje, czy presja jest szeroka w tech/growth, zanim bot przypisze ją jednemu tokenowi lub jednej giełdzie.",
    nextAdapterStep: "Add ETF provider and mega-cap basket comparator.",
    sparkTone: "watch",
  },
  {
    id: "gld",
    rank: 22,
    symbol: "GLD",
    name: "Gold ETF proxy",
    assetClass: "etf",
    sourceRhythm: "market provider + holdings cadence",
    priceLane: "ETF proxy after provider key",
    volumeLane: "safe-haven flow proxy",
    proofOrDisclosureLane: "fund disclosure cadence",
    secondSourceLane: "ETF proxy ↔ XAU commodity lane",
    riskPressure: 33,
    confidenceFloor: 46,
    adapterState: "provider_required",
    humanCopy: "GLD pomaga oddzielić ruch złota jako surowca od zachowania funduszu ETF i szerokiego sentymentu makro.",
    nextAdapterStep: "Add ETF/commodity bridge and method tag.",
    sparkTone: "flat",
  },
  {
    id: "brent",
    rank: 23,
    symbol: "BRENT",
    name: "Brent oil proxy",
    assetClass: "commodity",
    sourceRhythm: "commodity provider required",
    priceLane: "oil futures/spot provider later",
    volumeLane: "energy/inflation stress proxy",
    proofOrDisclosureLane: "contract/source method timestamp",
    secondSourceLane: "commodity provider ↔ macro energy context",
    riskPressure: 39,
    confidenceFloor: 41,
    adapterState: "provider_required",
    humanCopy: "Brent dodaje drugi punkt energii obok WTI, żeby bot nie budował makro narracji na jednym kontrakcie.",
    nextAdapterStep: "Normalize Brent/WTI symbols and source method.",
    sparkTone: "watch",
  },
];

const metricContracts: UniversalAssetMetricContract[] = [
  {
    id: "price_change_lanes",
    label: "1H / 24H / 7D / 30D",
    appliesTo: ["crypto", "exchange_token", "stock", "fx", "real_estate", "etf", "commodity"],
    publicLabel: "Ruch ceny z rytmem źródła",
    sourceRequirement: "provider timestamp, stale/fallback flag and second-source comparison when available",
    notAllowed: "showing simulated numbers as live, buy/sell direction, guaranteed trend",
  },
  {
    id: "liquidity_depth_or_volume",
    label: "Liquidity / depth / volume",
    appliesTo: ["crypto", "exchange_token", "stock", "etf", "commodity"],
    publicLabel: "Płynność i jakość wolumenu",
    sourceRequirement: "orderbook/depth for crypto; market volume provider for stocks/ETFs/commodities",
    notAllowed: "guaranteed exit liquidity or safety claim",
  },
  {
    id: "disclosure_or_proof",
    label: "Disclosure / proof lane",
    appliesTo: ["exchange_token", "stock", "fx", "real_estate", "etf"],
    publicLabel: "Źródło formalne / ujawnienia",
    sourceRequirement: "SEC/issuer filing, ECB/FRED release date, reserve/liability timestamp or holdings cadence",
    notAllowed: "proof of safety, solvency certificate, investment recommendation",
  },
  {
    id: "cross_market_context",
    label: "Cross-market context",
    appliesTo: ["crypto", "stock", "fx", "real_estate", "etf", "commodity"],
    publicLabel: "Czy ruch jest lokalny czy szeroki",
    sourceRequirement: "compare at least one adjacent market lane before stronger copy",
    notAllowed: "single-source panic, next FTX claim, instant macro crash alert",
  },
];

export function buildUniversalAssetMarketMatrix(): UniversalAssetMarketMatrix {
  return {
    version: "PASS345.universal_asset_market_matrix",
    headline:
      "Każda waluta, stock, ETF, real estate proxy i commodity dostaje ten sam czytelny szkielet jak crypto; PASS345 rozszerza watchlistę do 23 instrumentów i wymusza provider-state przed każdym mocniejszym opisem AI.",
    boundary:
      "Universal Asset Matrix is a scanner contract. It can prepare advanced rows for every asset class, but it must not pretend that provider-pending data is live.",
    rows,
    metricContracts,
    botRules: [
      "Każdy asset może mieć zaawansowany wiersz jak crypto, ale live liczby pojawiają się dopiero po podpięciu providera i timestampu.",
      "Stability score w giełdach oznacza wyżej = lepiej; review pressure oznacza wyżej = więcej ostrożności. UI musi to rozdzielać.",
      "Stocki używają ceny, wolumenu i filingów; FX używa reference/intraday; real estate używa wolnego macro + REIT proxy.",
      "Bot może pokazać ryzyko i braki, ale nie może robić porad inwestycyjnych, paniki ani oskarżeń o niewypłacalność.",
    ],
  };
}
