import type { VlmBrainAdapterOrchestrationPlan } from "./vlm-brain-adapter-orchestration-plan";
import type { VlmBrainAuditTrailIndex } from "./vlm-brain-audit-trail-index";
import type { VlmBrainCustomerReadinessPreflight } from "./vlm-brain-customer-readiness-preflight";
import type { VlmBrainGovernancePolicyMemo } from "./vlm-brain-governance-policy-memo";
import type { VlmBrainRendererComparisonPlan } from "./vlm-brain-renderer-comparison-plan";
export type VlmBrainMegaBranchControlTower = { schemaVersion:"vlm-brain-mega-branch-control-tower-v1-pass242"; towerMode:"pass233_242_operator_release_control_preview"; towerId:string; createdAt:string; token:{symbol:string;name:string}; towerDecision:"blocked"|"operator_review_required"; publicExportReady:false; binaryPdfReady:false; walletAccessReady:false; rawPayloadAllowed:false; branches:Array<{id:string;label:string;state:"blocked"|"review";score:number;nextAction:string}>; operatorSummary:string; customerBoundary:string; };
const SCHEMA="vlm-brain-mega-branch-control-tower-v1-pass242" as const;
function c(v:unknown,f="mega branch control review required",l=280){return String(v??f).replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,l)||f}
function id(v:string){return c(v,"VLM-MEGA-BRANCH",250).toUpperCase().replace(/[^A-Z0-9-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")}
function score(blocked:boolean,base:number){return Math.max(0,Math.min(100,blocked?base-30:base))}
export function buildVlmBrainMegaBranchControlTower(adapter:VlmBrainAdapterOrchestrationPlan,renderer:VlmBrainRendererComparisonPlan,governance:VlmBrainGovernancePolicyMemo,auditIndex:VlmBrainAuditTrailIndex,customer:VlmBrainCustomerReadinessPreflight): VlmBrainMegaBranchControlTower{
 const createdAt=customer.createdAt??auditIndex.createdAt??new Date().toISOString();
 const branches=[{id:"adapter",label:"Adapter orchestration",state:adapter.orchestrationDecision==="blocked"?"blocked" as const:"review" as const,score:score(adapter.orchestrationDecision==="blocked",58),nextAction:"Connect live feeds and durable server adapters."},{id:"renderer",label:"Renderer comparison",state:renderer.comparisonDecision==="blocked"?"blocked" as const:"review" as const,score:score(renderer.comparisonDecision==="blocked",64),nextAction:"Attach DOM/WebGL QA traces before renderer switch."},{id:"governance",label:"Governance policy",state:governance.memoDecision==="blocked"?"blocked" as const:"review" as const,score:score(governance.memoDecision==="blocked",62),nextAction:"Keep forbidden claim and source policy gate active."},{id:"audit",label:"Audit trail index",state:auditIndex.indexDecision==="blocked"?"blocked" as const:"review" as const,score:score(auditIndex.indexDecision==="blocked",66),nextAction:"Persist durable audit trail and source refs."},{id:"customer",label:"Customer readiness",state:customer.preflightDecision==="blocked"?"blocked" as const:"review" as const,score:score(customer.preflightDecision==="blocked",55),nextAction:"Keep customer/PDF/wallet routes blocked until gates are real."}];
 return {schemaVersion:SCHEMA,towerMode:"pass233_242_operator_release_control_preview",towerId:id(`VLM-MEGA-BRANCH-${customer.token.symbol}-${customer.preflightId}-${createdAt}`),createdAt,token:customer.token,towerDecision:branches.some(b=>b.state==="blocked")?"blocked":"operator_review_required",publicExportReady:false,binaryPdfReady:false,walletAccessReady:false,rawPayloadAllowed:false,branches,operatorSummary:"PASS233–PASS242 control tower combines trace, adapter, access, PDF, missing-data, renderer, governance, audit and customer preflight gates.",customerBoundary:"Control tower is internal release readiness only; no customer export, binary PDF or wallet access is ready until production gates pass."};
}
export const PASS242_VLM_BRAIN_MEGA_BRANCH_CONTROL_TOWER_CONTRACT = true;
