import type { VlmBrainAccessCopyFirewall } from "./vlm-brain-access-copy-firewall";
import type { VlmBrainMissingDataEscalationQueue } from "./vlm-brain-missing-data-escalation-queue";
import type { VlmBrainPdfStorageRedactionBridge } from "./vlm-brain-pdf-storage-redaction-bridge";
export type VlmBrainCustomerReadinessPreflight = { schemaVersion:"vlm-brain-customer-readiness-preflight-v1-pass241"; preflightMode:"customer_route_locked_preview"; preflightId:string; createdAt:string; token:{symbol:string;name:string}; preflightDecision:"blocked"|"review_required"; customerRouteReady:false; pdfDownloadReady:false; walletAccessReady:false; rawPayloadAllowed:false; checks:Array<{id:string;label:string;state:"blocked"|"review";nextAction:string}>; operatorSummary:string; customerBoundary:string; };
const SCHEMA="vlm-brain-customer-readiness-preflight-v1-pass241" as const;
function c(v:unknown,f="customer readiness preflight review required",l=260){return String(v??f).replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,l)||f}
function id(v:string){return c(v,"VLM-CUSTOMER-PREFLIGHT",240).toUpperCase().replace(/[^A-Z0-9-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")}
export function buildVlmBrainCustomerReadinessPreflight(access:VlmBrainAccessCopyFirewall,missing:VlmBrainMissingDataEscalationQueue,pdfBridge:VlmBrainPdfStorageRedactionBridge): VlmBrainCustomerReadinessPreflight{
 const createdAt=access.createdAt??missing.createdAt??pdfBridge.createdAt??new Date().toISOString();
 const checks=[{id:"access_copy",label:"Access/copy firewall",state:access.firewallDecision==="blocked"?"blocked" as const:"review" as const,nextAction:"Keep access and copy locked until entitlement and legal-safe copy pass."},{id:"missing_data",label:"Missing data escalation",state:missing.queueDecision==="blocked"?"blocked" as const:"review" as const,nextAction:"Resolve missing holder/orderbook/contract/OSINT evidence before customer copy."},{id:"pdf_storage",label:"PDF/storage/redaction",state:pdfBridge.bridgeDecision==="blocked"?"blocked" as const:"review" as const,nextAction:"Keep PDF download disabled until storage/redaction/generator exists."}];
 return {schemaVersion:SCHEMA,preflightMode:"customer_route_locked_preview",preflightId:id(`VLM-CUSTOMER-PREFLIGHT-${access.token.symbol}-${access.firewallId}-${createdAt}`),createdAt,token:access.token,preflightDecision:checks.some(c=>c.state==="blocked")?"blocked":"review_required",customerRouteReady:false,pdfDownloadReady:false,walletAccessReady:false,rawPayloadAllowed:false,checks,operatorSummary:"Customer readiness preflight keeps all customer routes locked until access, source, PDF and redaction blockers are closed.",customerBoundary:"Customer route remains locked; output is not a certificate, investment advice or final verdict."};
}
export const PASS241_VLM_BRAIN_CUSTOMER_READINESS_PREFLIGHT_CONTRACT = true;
