#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any, Iterable

from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

PAGE_W, PAGE_H = A4
MARGIN_X = 42
TOP_Y = PAGE_H - 42
BOTTOM_Y = 62
FONT_NAME = "VelmereManrope"

COPY = {
    "pl": {
        "title": "Velmère Security — automatyczna analiza bezpieczeństwa",
        "automated": "Automatyczna analiza informacyjna",
        "overview": "Podsumowanie",
        "methodology": "Metodyka",
        "evidence": "Rejestr dowodów",
        "findings": "Ustalenia",
        "remediation": "Bezpieczne działania naprawcze",
        "conflicts": "Sprzeczności i pewność",
        "provenance": "Pochodzenie i wartość poziomu",
        "boundary": "Granica claimów i następny krok",
        "no_findings": "W ograniczonym pakiecie dowodów nie potwierdzono findingu. Nie jest to dowód bezpieczeństwa.",
        "footer": "Issued by Velmère Security · automatycznie: Velmère Security Engine · integralność dokumentu zweryfikowana · nie jest niezależną certyfikacją ani human-review",
        "next": "Następny bezpieczny krok",
        "limitations": "Ograniczenia",
        "issuer_statement": "Issued by Velmère Security. Wygenerowano automatycznie przez Velmère Security Engine. Integralność dokumentu zweryfikowana przez Velmère.",
        "boundary_statement": "Ten raport nie jest niezależną certyfikacją ani human-review.",
    },
    "en": {
        "title": "Velmère Security — automated security analysis",
        "automated": "Automated informational analysis",
        "overview": "Executive overview",
        "methodology": "Methodology",
        "evidence": "Evidence registry",
        "findings": "Findings",
        "remediation": "Safe remediation",
        "conflicts": "Contradictions and confidence",
        "provenance": "Provenance and tier value",
        "boundary": "Claim boundary and next step",
        "no_findings": "No finding was confirmed in the bounded evidence packet. This is not proof of safety.",
        "footer": "Issued by Velmère Security · generated by Velmère Security Engine · document integrity verified · not an independent certification or human review",
        "next": "Next safe check",
        "limitations": "Limitations",
        "issuer_statement": "Issued by Velmère Security. Generated automatically by the Velmère Security Engine. Document integrity verified by Velmère.",
        "boundary_statement": "This report is not an independent certification or human review.",
    },
    "de": {
        "title": "Velmère Security — automatisierte Sicherheitsanalyse",
        "automated": "Automatisierte Informationsanalyse",
        "overview": "Kurzüberblick",
        "methodology": "Methodik",
        "evidence": "Evidenzregister",
        "findings": "Feststellungen",
        "remediation": "Sichere Abhilfe",
        "conflicts": "Widersprüche und Konfidenz",
        "provenance": "Provenienz und Tier-Wert",
        "boundary": "Claim-Grenze und nächster Schritt",
        "no_findings": "Im begrenzten Evidenzpaket wurde kein Finding bestätigt. Dies ist kein Sicherheitsnachweis.",
        "footer": "Issued by Velmère Security · automatisch: Velmère Security Engine · Dokumentintegrität geprüft · keine unabhängige Zertifizierung und kein Human Review",
        "next": "Nächster sicherer Prüfschritt",
        "limitations": "Einschränkungen",
        "issuer_statement": "Issued by Velmère Security. Automatisch durch die Velmère Security Engine erzeugt. Dokumentintegrität durch Velmère geprüft.",
        "boundary_statement": "Dieser Bericht ist keine unabhängige Zertifizierung und kein Human Review.",
    },
}


FIELD_LABELS = {
    "pl": {
        "case": "Przypadek", "category": "Kategoria", "source": "Źródło", "source_sha": "SHA-256 źródła",
        "analysis_mode": "Tryb analizy", "status": "Status", "severity": "Najwyższa waga", "confidence": "Pewność",
        "verdict": "Ocena", "commercial_rights": "Prawa komercyjne", "entitlement": "Uprawnienie",
        "provenance": "Receipt pochodzenia", "remediation": "Działanie naprawcze", "evidence_coverage": "Pokrycie dowodowe",
        "output_packet": "SHA-256 pakietu wynikowego", "tier_value": "WARTOŚĆ POZIOMU / ZAKRES",
        "material_additions": "Materialne rozszerzenia", "excluded": "Jawnie wyłączone", "claim_boundary": "Granica deklaracji",
        "families": "rodziny", "rationale": "Uzasadnienie", "no_contradiction": "Brak sprzeczności w ograniczonym pakiecie dowodów.",
    },
    "en": {
        "case": "Case", "category": "Category", "source": "Source", "source_sha": "Source SHA-256",
        "analysis_mode": "Analysis mode", "status": "Status", "severity": "Highest severity", "confidence": "Confidence",
        "verdict": "Assessment", "commercial_rights": "Commercial rights", "entitlement": "Entitlement",
        "provenance": "Provenance receipt", "remediation": "Remediation", "evidence_coverage": "Evidence coverage",
        "output_packet": "Output packet SHA-256", "tier_value": "TIER VALUE / SCOPE",
        "material_additions": "Material additions", "excluded": "Explicitly excluded", "claim_boundary": "Claim boundary",
        "families": "families", "rationale": "Rationale", "no_contradiction": "No contradiction row in this bounded evidence packet.",
    },
    "de": {
        "case": "Fall", "category": "Kategorie", "source": "Quelle", "source_sha": "Quellen-SHA-256",
        "analysis_mode": "Analysemodus", "status": "Status", "severity": "Höchster Schweregrad", "confidence": "Konfidenz",
        "verdict": "Bewertung", "commercial_rights": "Kommerzielle Rechte", "entitlement": "Berechtigung",
        "provenance": "Provenienz-Receipt", "remediation": "Abhilfe", "evidence_coverage": "Evidenzabdeckung",
        "output_packet": "SHA-256 des Ausgabepakets", "tier_value": "TIER-WERT / UMFANG",
        "material_additions": "Materielle Erweiterungen", "excluded": "Explizit ausgeschlossen", "claim_boundary": "Claim-Grenze",
        "families": "Familien", "rationale": "Begründung", "no_contradiction": "Keine Widerspruchszeile im begrenzten Evidenzpaket.",
    },
}

TOKEN_COPY = {
    "pl": {
        "automated_informational": "automatyczna analiza informacyjna", "passed": "zaliczono", "blocked": "zablokowano", "failed": "błąd",
        "none": "brak", "informational": "informacyjna", "low": "niska", "medium": "średnia", "high": "wysoka", "critical": "krytyczna",
        "verified": "zweryfikowane", "not_required": "niewymagane", "unverified": "niezweryfikowane",
    },
    "en": {
        "automated_informational": "automated informational analysis", "passed": "passed", "blocked": "blocked", "failed": "failed",
        "none": "none", "informational": "informational", "low": "low", "medium": "medium", "high": "high", "critical": "critical",
        "verified": "verified", "not_required": "not required", "unverified": "unverified",
    },
    "de": {
        "automated_informational": "automatisierte Informationsanalyse", "passed": "bestanden", "blocked": "blockiert", "failed": "fehlgeschlagen",
        "none": "keine", "informational": "informativ", "low": "niedrig", "medium": "mittel", "high": "hoch", "critical": "kritisch",
        "verified": "verifiziert", "not_required": "nicht erforderlich", "unverified": "nicht verifiziert",
    },
}

TECHNICAL_TERM_COPY = {
    "source_bound_identity": {"pl": "tożsamość związana ze źródłem", "en": "source-bound identity", "de": "quellengebundene Identität"},
    "bounded_finding_summary": {"pl": "ograniczone podsumowanie ustaleń", "en": "bounded finding summary", "de": "begrenzte Finding-Zusammenfassung"},
    "limitations": {"pl": "ograniczenia", "en": "limitations", "de": "Einschränkungen"},
    "next_safe_check": {"pl": "następny bezpieczny krok", "en": "next safe check", "de": "nächster sicherer Prüfschritt"},
    "full_evidence_table": {"pl": "pełna tabela dowodów", "en": "full evidence table", "de": "vollständige Evidenztabelle"},
    "cross_family_contradiction_analysis": {"pl": "analiza sprzeczności między rodzinami", "en": "cross-family contradiction analysis", "de": "familienübergreifende Widerspruchsanalyse"},
    "human_review_claim": {"pl": "deklaracja przeglądu przez człowieka", "en": "human-review claim", "de": "Human-Review-Claim"},
    "human_review_claim_without_receipt": {"pl": "deklaracja human-review bez receiptu", "en": "human-review claim without receipt", "de": "Human-Review-Claim ohne Receipt"},
    "independent_certification": {"pl": "niezależna certyfikacja", "en": "independent certification", "de": "unabhängige Zertifizierung"},
    "personalised_advice": {"pl": "spersonalizowana porada", "en": "personalised advice", "de": "personalisierte Beratung"},
    "security_guarantee": {"pl": "gwarancja bezpieczeństwa", "en": "security guarantee", "de": "Sicherheitsgarantie"},
    "multi_family_evidence_table": {"pl": "wielorodzinna tabela dowodów", "en": "multi-family evidence table", "de": "Evidenztabelle mit mehreren Familien"},
    "severity_rationale": {"pl": "uzasadnienie wagi", "en": "severity rationale", "de": "Begründung des Schweregrads"},
    "remediation_map": {"pl": "mapa działań naprawczych", "en": "remediation map", "de": "Abhilfekarte"},
    "freshness_and_rights_receipts": {"pl": "receipty świeżości i praw", "en": "freshness and rights receipts", "de": "Aktualitäts- und Rechte-Receipts"},
    "three_family_evidence_floor": {"pl": "minimum trzech rodzin dowodów", "en": "three-family evidence floor", "de": "Mindestgrenze von drei Evidenzfamilien"},
    "contradiction_register": {"pl": "rejestr sprzeczności", "en": "contradiction register", "de": "Widerspruchsregister"},
    "confidence_basis": {"pl": "podstawa pewności", "en": "confidence basis", "de": "Konfidenzbasis"},
    "provenance_receipt": {"pl": "receipt pochodzenia", "en": "provenance receipt", "de": "Provenienz-Receipt"},
    "automated_advanced_methodology": {"pl": "metodyka automatycznej analizy Advanced", "en": "automated Advanced methodology", "de": "Methodik der automatisierten Advanced-Analyse"},
    "automated": {"pl": "automatyczna", "en": "automated", "de": "automatisiert"},
    "human review included": {"pl": "przegląd człowieka uwzględniony", "en": "human review included", "de": "Human Review enthalten"},
    "independent certification": {"pl": "niezależna certyfikacja", "en": "independent certification", "de": "unabhängige Zertifizierung"},
    "personalised advice": {"pl": "spersonalizowana porada", "en": "personalised advice", "de": "personalisierte Beratung"},
    "access_control": {"pl": "kontrola dostępu", "en": "access control", "de": "Zugriffskontrolle"},
    "accounting": {"pl": "księgowanie", "en": "accounting", "de": "Abrechnung"},
    "ambiguous_control": {"pl": "niejednoznaczna kontrola", "en": "ambiguous control", "de": "mehrdeutige Kontrolle"},
    "authorization": {"pl": "autoryzacja", "en": "authorization", "de": "Autorisierung"},
    "clean_control": {"pl": "czysty przypadek kontrolny", "en": "clean control", "de": "saubere Kontrollprobe"},
    "cross_chain": {"pl": "operacje międzyłańcuchowe", "en": "cross-chain", "de": "Cross-Chain"},
    "delegatecall": {"pl": "wywołanie delegowane", "en": "delegatecall", "de": "Delegatecall"},
    "destruction": {"pl": "niszczenie kontraktu", "en": "contract destruction", "de": "Vertragszerstörung"},
    "dos": {"pl": "odmowa usługi", "en": "denial of service", "de": "Dienstverweigerung"},
    "external_call": {"pl": "wywołanie zewnętrzne", "en": "external call", "de": "externer Aufruf"},
    "frontrun": {"pl": "wyprzedzanie transakcji", "en": "front-running", "de": "Front-Running"},
    "governance": {"pl": "zarządzanie", "en": "governance", "de": "Governance"},
    "initialization": {"pl": "inicjalizacja", "en": "initialization", "de": "Initialisierung"},
    "operational_control": {"pl": "kontrola operacyjna", "en": "operational control", "de": "Betriebskontrolle"},
    "oracle": {"pl": "wyrocznia danych", "en": "oracle", "de": "Datenorakel"},
    "randomness": {"pl": "losowość", "en": "randomness", "de": "Zufälligkeit"},
    "reentrancy": {"pl": "ponowne wejście", "en": "reentrancy", "de": "Reentrancy"},
    "rounding": {"pl": "zaokrąglenia", "en": "rounding", "de": "Rundung"},
    "signature": {"pl": "podpis", "en": "signature", "de": "Signatur"},
    "solvency": {"pl": "wypłacalność", "en": "solvency", "de": "Solvenz"},
    "time_dependency": {"pl": "zależność czasowa", "en": "time dependency", "de": "Zeitabhängigkeit"},
    "token_accounting": {"pl": "księgowanie tokenów", "en": "token accounting", "de": "Token-Abrechnung"},
    "token_hook": {"pl": "hook tokena", "en": "token hook", "de": "Token-Hook"},
    "transfer_policy": {"pl": "polityka transferów", "en": "transfer policy", "de": "Transfer-Richtlinie"},
    "upgradeability": {"pl": "możliwość aktualizacji", "en": "upgradeability", "de": "Upgrade-Fähigkeit"},
    "bounded_official_tool_summary": {"pl": "ograniczone podsumowanie wyników narzędzi oficjalnych", "en": "bounded official-tool summary", "de": "begrenzte Zusammenfassung offizieller Werkzeuge"},
    "four_official_tool_receipts": {"pl": "receipty czterech narzędzi oficjalnych", "en": "four official-tool receipts", "de": "Receipts von vier offiziellen Werkzeugen"},
    "all_tool_signals": {"pl": "wszystkie sygnały narzędzi", "en": "all tool signals", "de": "alle Werkzeugsignale"},
    "expanded_evidence_scenarios": {"pl": "rozszerzone scenariusze dowodowe", "en": "expanded evidence scenarios", "de": "erweiterte Evidenzszenarien"},
    "abstention_and_claim_boundary": {"pl": "abstencja i granica deklaracji", "en": "abstention and claim boundary", "de": "Abstention und Claim-Grenze"},
    "real_deployed_contract_claim": {"pl": "deklaracja audytu realnie wdrożonego kontraktu", "en": "real deployed-contract audit claim", "de": "Claim eines Audits eines bereitgestellten Vertrags"},
    "compiler_metadata": {"pl": "metadane kompilatora", "en": "compiler metadata", "de": "Compiler-Metadaten"},
    "static_analysis": {"pl": "analiza statyczna", "en": "static analysis", "de": "statische Analyse"},
    "pattern_analysis": {"pl": "analiza wzorców", "en": "pattern analysis", "de": "Musteranalyse"},
    "build_reproduction": {"pl": "odtworzenie buildu", "en": "build reproduction", "de": "Build-Reproduktion"},
    "cross_tool_consensus": {"pl": "konsensus między narzędziami", "en": "cross-tool consensus", "de": "werkzeugübergreifender Konsens"},
    "compiler_artifact_diff": {"pl": "różnica artefaktów kompilatora", "en": "compiler artifact diff", "de": "Compiler-Artefakt-Differenz"},
    "comparative_control_analysis": {"pl": "porównawcza analiza kontroli", "en": "comparative control analysis", "de": "vergleichende Kontrollanalyse"},
    "blind_adjudication_packet": {"pl": "ślepy pakiet adjudykacyjny", "en": "blind adjudication packet", "de": "blindes Adjudikationspaket"},
    "independent_adjudication": {"pl": "niezależna adjudykacja", "en": "independent adjudication", "de": "unabhängige Adjudikation"},
    "risk_to_mitigation_pair": {"pl": "para ryzyko-remediacja", "en": "risk-to-mitigation pair", "de": "Risiko-Abhilfe-Paar"},
    "benign_control_baseline": {"pl": "bazowa kontrola benign", "en": "benign control baseline", "de": "gutartige Kontrollbasis"},
    "ambiguous_external_dependency_boundary": {"pl": "granica niejednoznacznej zależności zewnętrznej", "en": "ambiguous external dependency boundary", "de": "Grenze einer mehrdeutigen externen Abhängigkeit"},
    "official_semgrep_status_summary": {"pl": "podsumowanie statusu oficjalnego Semgrep", "en": "official Semgrep status summary", "de": "Statusübersicht des offiziellen Semgrep"},
    "official_semgrep_finding_details": {"pl": "szczegóły ustaleń oficjalnego Semgrep", "en": "official Semgrep finding details", "de": "Details der offiziellen Semgrep-Feststellungen"},
    "blocked_tool_register": {"pl": "rejestr zablokowanych narzędzi", "en": "blocked-tool register", "de": "Register blockierter Werkzeuge"},
    "official_tool_coverage_gap_analysis": {"pl": "analiza braków pokrycia narzędzi oficjalnych", "en": "official-tool coverage-gap analysis", "de": "Analyse der Abdeckungslücken offizieller Werkzeuge"},
    "official_tool_retest_plan": {"pl": "plan ponownego testu narzędzi oficjalnych", "en": "official-tool retest plan", "de": "Wiederholungsplan offizieller Werkzeuge"},
    "officialToolMatrix": {"pl": "macierz narzędzi oficjalnych", "en": "official-tool matrix", "de": "Matrix offizieller Werkzeuge"},
    "officialSuccessfulExecutions": {"pl": "udane wykonania oficjalne", "en": "successful official executions", "de": "erfolgreiche offizielle Ausführungen"},
    "officialRequiredExecutions": {"pl": "wymagane wykonania oficjalne", "en": "required official executions", "de": "erforderliche offizielle Ausführungen"},
    "official_semgrep_pattern_analysis": {"pl": "oficjalna analiza wzorców Semgrep", "en": "official Semgrep pattern analysis", "de": "offizielle Semgrep-Musteranalyse"},
}


def humanize_token(value: Any, locale: str) -> str:
    text = clean_text(value)
    if text in TOKEN_COPY[locale]:
        return TOKEN_COPY[locale][text]
    if text in TECHNICAL_TERM_COPY:
        return TECHNICAL_TERM_COPY[text][locale]
    return text.replace("_", " ")


def confidence_summary(model: Any, locale: str) -> str:
    if not isinstance(model, dict):
        return {"pl": "nieskalibrowana", "en": "not calibrated", "de": "nicht kalibriert"}[locale]
    coverage = model.get("evidenceCompleteness") or {}
    valid = coverage.get("officialReceiptsValid", 0)
    required = coverage.get("officialReceiptsRequired", 4)
    finding = {
        "pl": "pewność ustalenia: nieskalibrowana",
        "en": "finding confidence: not calibrated",
        "de": "Finding-Konfidenz: nicht kalibriert",
    }[locale]
    evidence = {
        "pl": f"kompletność dowodów: {valid}/{required}",
        "en": f"evidence completeness: {valid}/{required}",
        "de": f"Evidenzvollständigkeit: {valid}/{required}",
    }[locale]
    review = {
        "pl": "przegląd niezależny: niewykonany",
        "en": "independent review: not performed",
        "de": "unabhängige Prüfung: nicht durchgeführt",
    }[locale]
    return f"{finding}; {evidence}; {review}"


def confidence_detail_lines(model: Any, locale: str) -> list[str]:
    if not isinstance(model, dict):
        return [confidence_summary(model, locale)]
    coverage = model.get("evidenceCompleteness") or {}
    labels = {
        "pl": {"finding":"Pewność ustalenia","evidence":"Kompletność dowodów","identity":"Tożsamość źródła","deployment":"Reprodukcja wdrożenia","agreement":"Stan sygnałów narzędzi","review":"Przegląd","adjudication":"Adjudykacja","uncertainty":"Niepewność"},
        "en": {"finding":"Finding confidence","evidence":"Evidence completeness","identity":"Source identity","deployment":"Deployment reproduction","agreement":"Tool signal state","review":"Review","adjudication":"Adjudication","uncertainty":"Uncertainty"},
        "de": {"finding":"Finding-Konfidenz","evidence":"Evidenzvollständigkeit","identity":"Quellidentität","deployment":"Deployment-Reproduktion","agreement":"Werkzeugsignalstatus","review":"Review","adjudication":"Adjudikation","uncertainty":"Unsicherheit"},
    }[locale]
    values = {
        "NOT_CALIBRATED": {"pl":"nieskalibrowana","en":"not calibrated","de":"nicht kalibriert"},
        "AUTOMATED_UNREVIEWED": {"pl":"automatyczny, bez przeglądu","en":"automated, unreviewed","de":"automatisiert, ungeprüft"},
        "NOT_PERFORMED": {"pl":"niewykonana","en":"not performed","de":"nicht durchgeführt"},
    }
    def local(v: Any) -> str:
        t=str(v or "none")
        return values.get(t, {}).get(locale, humanize_token(t, locale))
    valid=coverage.get("officialReceiptsValid",0); required=coverage.get("officialReceiptsRequired",4)
    lines=[
        f"{labels['finding']}: {local(model.get('findingConfidence'))}",
        f"{labels['evidence']}: {valid}/{required}",
        f"{labels['identity']}: {humanize_token(model.get('sourceIdentityConfidence'), locale)}",
        f"{labels['deployment']}: {humanize_token(model.get('deploymentReproductionConfidence'), locale)}",
        f"{labels['agreement']}: {humanize_token(model.get('toolAgreementState'), locale)}",
        f"{labels['review']}: {local(model.get('reviewStatus'))}",
        f"{labels['adjudication']}: {local(model.get('adjudicationStatus'))}",
    ]
    uncertainty=model.get("uncertainty") or []
    if uncertainty:
        lines.append(f"{labels['uncertainty']}: " + ", ".join(humanize_token(x, locale) for x in uncertainty))
    return lines


def format_value(value: Any, locale: str) -> str:
    if isinstance(value, bool):
        return {"pl": "tak" if value else "nie", "en": "yes" if value else "no", "de": "ja" if value else "nein"}[locale]
    if value is None:
        return {"pl": "brak", "en": "none", "de": "keine"}[locale]
    if isinstance(value, list):
        return ", ".join(format_value(item, locale) for item in value) or {"pl": "brak", "en": "none", "de": "keine"}[locale]
    if isinstance(value, dict):
        return "; ".join(f"{humanize_token(key, locale)}={format_value(item, locale)}" for key, item in sorted(value.items()))
    return humanize_token(value, locale)

TIER_PAGES = {"basic": 2, "pro": 4, "advanced": 8}
LOCALE_ROTATION = ("pl", "en", "de")


def stable_json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def clean_text(value: Any) -> str:
    text = str(value or "").replace("\x00", " ")
    return re.sub(r"\s+", " ", text).strip()


def wrap_text(text: str, max_chars: int = 92) -> list[str]:
    words = clean_text(text).split(" ")
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = word if not current else f"{current} {word}"
        if len(candidate) <= max_chars:
            current = candidate
        else:
            if current:
                lines.append(current)
            while len(word) > max_chars:
                lines.append(word[:max_chars])
                word = word[max_chars:]
            current = word
    if current:
        lines.append(current)
    return lines or [""]


def draw_wrapped(c: canvas.Canvas, text: str, x: float, y: float, *, size: float = 9.2, leading: float = 13, max_chars: int = 92, max_lines: int | None = None) -> float:
    c.setFont(FONT_NAME, size)
    lines = wrap_text(text, max_chars)
    if max_lines is not None:
        lines = lines[:max_lines]
    for line in lines:
        if y < BOTTOM_Y + 20:
            break
        c.drawString(x, y, line)
        y -= leading
    return y


def draw_kv(c: canvas.Canvas, key: str, value: Any, y: float) -> float:
    c.setFont(FONT_NAME, 8.5)
    c.drawString(MARGIN_X, y, f"{key}:")
    return draw_wrapped(c, clean_text(value), MARGIN_X + 125, y, size=8.5, leading=11.5, max_chars=76, max_lines=4) - 3


def footer(c: canvas.Canvas, copy: dict[str, str], page_number: int, page_count: int, report_id: str, packet_sha: str) -> None:
    c.setLineWidth(0.35)
    c.line(MARGIN_X, 48, PAGE_W - MARGIN_X, 48)
    c.setFont(FONT_NAME, 5.4)
    footer_lines = wrap_text(copy["footer"], 105)[:2]
    y = 39
    for line in footer_lines:
        c.drawString(MARGIN_X, y, line)
        y -= 7
    c.drawRightString(PAGE_W - MARGIN_X, 38, f"{page_number}/{page_count}")
    c.drawRightString(PAGE_W - MARGIN_X, 30, f"{report_id[:42]} · {packet_sha[:16]}…")


def page_header(c: canvas.Canvas, copy: dict[str, str], tier: str, section: str, report_id: str) -> float:
    c.setFillColorRGB(0.04, 0.04, 0.04)
    c.rect(0, PAGE_H - 88, PAGE_W, 88, fill=1, stroke=0)
    c.setFillColorRGB(1, 1, 1)
    c.setFont(FONT_NAME, 16)
    c.drawString(MARGIN_X, PAGE_H - 42, copy["title"])
    c.setFont(FONT_NAME, 9)
    c.drawString(MARGIN_X, PAGE_H - 60, f"{tier.upper()} · {section}")
    c.drawRightString(PAGE_W - MARGIN_X, PAGE_H - 60, report_id)
    c.setFillColorRGB(0.05, 0.05, 0.05)
    return PAGE_H - 112


def tool_status_lines(packet: dict[str, Any], locale: str) -> list[str]:
    labels = {
        "pl": {"header": "NARZĘDZIA OFICJALNE", "coverage": "Pokrycie", "boundary": "Granica"},
        "en": {"header": "OFFICIAL TOOLS", "coverage": "Coverage", "boundary": "Boundary"},
        "de": {"header": "OFFIZIELLE WERKZEUGE", "coverage": "Abdeckung", "boundary": "Grenze"},
    }[locale]
    official_families = {"compiler_metadata", "static_analysis", "pattern_analysis", "build_reproduction"}
    rows = packet.get("officialToolReceiptRefs") or [row for row in packet.get("evidenceTable") or [] if row.get("family") in official_families]
    valid = [row for row in rows if re.fullmatch(r"[0-9a-f]{64}", str(row.get("receiptSha256") or "")) and str(row.get("terminalStatus") or "").startswith("EXECUTED_")]
    unique = {str(row.get("sourceId") or "").split("-", 1)[0]: row for row in valid}
    completed = len(unique)
    lines = [labels["header"], f"{labels['coverage']}: {completed}/4 actual hash-bound executions", f"OFFICIAL_TOOL_EXECUTIONS: {completed}/4"]
    for tool in ("solc", "slither", "semgrep", "forge"):
        row = unique.get(tool)
        if row:
            lines.append(f"{tool}: {row.get('terminalStatus')} · receipt={str(row.get('receiptSha256'))[:16]}…")
        else:
            lines.append(f"{tool}: MISSING_OR_INVALID_RECEIPT")
    lines.append(f"{labels['boundary']}: project-owned benchmark evidence; no external-customer, independent-review, LIVE or sale credit")
    return lines

def findings_lines(packet: dict[str, Any], locale: str) -> Iterable[str]:
    findings = packet.get("findings") or []
    if not findings:
        yield "NO_CONFIRMED_FINDING"
        return
    for finding in findings:
        families = ", ".join(finding.get("analyzerFamilies") or [])
        yield f"[{humanize_token(finding.get('severity', 'informational'), locale).upper()}] {humanize_token(finding.get('title') or finding.get('id'), locale)} · {FIELD_LABELS[locale]['families']}: {format_value(finding.get('analyzerFamilies') or [], locale)}"
        yield f"{FIELD_LABELS[locale]['rationale']}: {finding.get('rationale', '')}"


def render_packet(packet: dict[str, Any], output: Path, font_path: Path) -> dict[str, Any]:
    tier = packet["tier"]
    locale = packet["locale"]
    copy = COPY[locale]
    pages = TIER_PAGES[tier]
    packet_sha = sha256_text(stable_json(packet))
    report_id = f"VLM-AUTO-{packet['caseId'].split('-')[2].upper()}-{tier.upper()}-{locale.upper()}-{packet_sha[:10].upper()}"
    output.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(output), pagesize=A4, pageCompression=1, invariant=1)
    c.setTitle(f"{copy['title']} — {packet['caseId']} — {tier}")
    c.setAuthor("Velmère Security")
    c.setSubject("Automated informational security analysis; not independent certification or human review")
    c.setCreator("Velmère Security Engine")
    c.setKeywords("Velmère Security, automated analysis, informational, evidence-bound")

    sections: list[tuple[str, list[tuple[str, Any]] | list[str]]] = []
    sections.append((copy["overview"], [
        (FIELD_LABELS[locale]["case"], packet["caseId"]),
        (FIELD_LABELS[locale]["category"], humanize_token(packet.get("category"), locale)),
        (FIELD_LABELS[locale]["source"], packet.get("sourcePath")),
        (FIELD_LABELS[locale]["source_sha"], packet.get("sourceSha256")),
        (FIELD_LABELS[locale]["analysis_mode"], humanize_token(packet.get("analysisMode"), locale)),
        (FIELD_LABELS[locale]["status"], humanize_token(packet.get("status"), locale)),
        (FIELD_LABELS[locale]["severity"], humanize_token(packet.get("highestSeverity"), locale)),
        (FIELD_LABELS[locale]["confidence"], confidence_summary(packet.get("confidenceModel"), locale)),
        (FIELD_LABELS[locale]["verdict"], packet.get("customerVerdict")),
    ]))
    if tier == "basic":
        sections.append((copy["boundary"], tool_status_lines(packet, locale) + list(findings_lines(packet, locale)) + [copy["issuer_statement"], copy["boundary_statement"], copy["limitations"] + ": " + " ".join(packet.get("limitations") or []), copy["next"] + ": " + clean_text(packet.get("nextSafeCheck"))]))
    elif tier == "pro":
        sections.extend([
            (copy["evidence"], tool_status_lines(packet, locale) + [f"{row.get('sourceId')} · {row.get('family')} · findings={','.join(row.get('findingIds') or []) or 'none'} · {row.get('payloadSha256')}" for row in packet.get("evidenceTable") or []]),
            (copy["findings"], list(findings_lines(packet, locale)) + [f"{FIELD_LABELS[locale]['remediation']}: {row.get('guidance')}" for row in packet.get("findings") or []]),
            (copy["boundary"], [copy["issuer_statement"], copy["boundary_statement"], copy["limitations"] + ": " + " ".join(packet.get("limitations") or []), f"{FIELD_LABELS[locale]['commercial_rights']}: {format_value(packet.get('commercialRights'), locale)}", f"{FIELD_LABELS[locale]['entitlement']}: {format_value(packet.get('entitlementStatus'), locale)}", f"{FIELD_LABELS[locale]['provenance']}: {packet.get('provenanceReceipt')}", copy["next"] + ": " + clean_text(packet.get("nextSafeCheck"))]),
        ])
    else:
        method = packet.get("methodology") or {}
        sections.extend([
            (copy["methodology"], [(humanize_token(str(k), locale), format_value(v, locale)) for k, v in method.items()]),
            (copy["evidence"], tool_status_lines(packet, locale) + [f"{row.get('sourceId')} · {row.get('family')} · controls={','.join(row.get('controls') or [])} · {row.get('payloadSha256')}" for row in packet.get("evidenceTable") or []]),
            (copy["findings"], list(findings_lines(packet, locale))),
            (copy["remediation"], [
                f"{humanize_token('comparative_control_analysis', locale)}: {format_value((packet.get('advancedEvidence') or {}).get('comparativeControlAnalysis'), locale)}",
                *[f"{row.get('id')}: {row.get('remediation')}" for row in packet.get("findings") or []],
            ] or [copy["no_findings"]]),
            (copy["conflicts"], [
                *confidence_detail_lines(packet.get("confidenceModel"), locale),
                f"{FIELD_LABELS[locale]['evidence_coverage']}: {format_value(packet.get('evidenceCoverage'), locale)}",
                f"{humanize_token('cross_tool_consensus', locale)}: {format_value((packet.get('advancedEvidence') or {}).get('crossToolConsensus'), locale)}",
                *[format_value(row, locale) for row in packet.get("contradictions") or []],
            ] or [FIELD_LABELS[locale]["no_contradiction"]]),
            (copy["provenance"], [
                f"{FIELD_LABELS[locale]['provenance']}: {packet.get('provenanceReceipt')}",
                f"{FIELD_LABELS[locale]['tier_value']}: {format_value(packet.get('tierValue'), locale)}",
                f"{humanize_token('compiler_artifact_diff', locale)}: {format_value((packet.get('advancedEvidence') or {}).get('compilerArtifactDiff'), locale)}",
                f"{humanize_token('blind_adjudication_packet', locale)}: {format_value((packet.get('advancedEvidence') or {}).get('adjudicationReadiness'), locale)}",
                f"{FIELD_LABELS[locale]['output_packet']}: {packet.get('outputSha256')}",
            ]),
            (copy["boundary"], [copy["issuer_statement"], copy["boundary_statement"], f"{FIELD_LABELS[locale]['claim_boundary']}: {format_value(packet.get('claimBoundary'), locale)}", copy["limitations"] + ": " + " ".join(packet.get("limitations") or []), copy["next"] + ": " + clean_text(packet.get("nextSafeCheck"))]),
        ])

    assert len(sections) == pages, (tier, len(sections), pages)
    for index, (section, content) in enumerate(sections, start=1):
        y = page_header(c, copy, tier, section, report_id)
        c.setFont(FONT_NAME, 11)
        c.drawString(MARGIN_X, y, section)
        y -= 22
        if content and isinstance(content[0], tuple):
            for key, value in content:  # type: ignore[misc]
                y = draw_kv(c, key, value, y)
        else:
            for row in content:  # type: ignore[assignment]
                y = draw_wrapped(c, str(row), MARGIN_X, y, size=8.7, leading=12.2, max_chars=96, max_lines=9) - 7
        if index == 1:
            tier_value = packet.get("tierValue") or {}
            y = min(y - 8, PAGE_H - 420)
            c.setFillColorRGB(0.94, 0.94, 0.94)
            c.roundRect(MARGIN_X, max(BOTTOM_Y + 80, y - 145), PAGE_W - 2 * MARGIN_X, 145, 6, fill=1, stroke=0)
            c.setFillColorRGB(0.05, 0.05, 0.05)
            c.setFont(FONT_NAME, 10)
            c.drawString(MARGIN_X + 14, y - 20, FIELD_LABELS[locale]["tier_value"])
            draw_wrapped(c, f"{FIELD_LABELS[locale]['material_additions']}: {format_value(tier_value.get('materialAdditions') or [], locale)}", MARGIN_X + 14, y - 42, size=8.2, leading=11, max_chars=88, max_lines=4)
            draw_wrapped(c, f"{FIELD_LABELS[locale]['excluded']}: {format_value(tier_value.get('explicitlyExcluded') or [], locale)}", MARGIN_X + 14, y - 91, size=8.2, leading=11, max_chars=88, max_lines=4)
            draw_wrapped(c, f"{FIELD_LABELS[locale]['claim_boundary']}: {format_value({'automated': packet.get('claimBoundary', {}).get('automated'), 'human review included': packet.get('claimBoundary', {}).get('humanReviewIncluded'), 'independent certification': packet.get('claimBoundary', {}).get('independentCertificationClaimAllowed'), 'personalised advice': packet.get('claimBoundary', {}).get('personalisedAdviceAllowed')}, locale)}", MARGIN_X + 14, y - 126, size=7.4, leading=9.5, max_chars=105, max_lines=3)
        footer(c, copy, index, pages, report_id, packet_sha)
        c.showPage()
    c.save()
    return {
        "schemaVersion": "velmere.pass36.a102r44p8.audit-pdf-manifest-row.v1",
        "path": output.as_posix(),
        "caseId": packet["caseId"],
        "tier": tier,
        "locale": locale,
        "pageCount": pages,
        "reportId": report_id,
        "packetSha256": packet_sha,
        "outputPacketSha256": packet["outputSha256"],
        "pdfSha256": hashlib.sha256(output.read_bytes()).hexdigest(),
        "byteLength": output.stat().st_size,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--packets", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--font", default="public/fonts/velmere/manrope-pdf-latin-plus-ext.ttf")
    args = parser.parse_args()
    packets = [json.loads(line) for line in Path(args.packets).read_text(encoding="utf-8").splitlines() if line.strip()]
    by_key = {(row["caseId"], row["tier"], row["locale"]): row for row in packets}
    cases = sorted({row["caseId"] for row in packets})
    selected: list[dict[str, Any]] = []
    for index, case_id in enumerate(cases):
        locale = LOCALE_ROTATION[index % len(LOCALE_ROTATION)]
        for tier in ("basic", "pro", "advanced"):
            selected.append(by_key[(case_id, tier, locale)])
    output_dir = Path(args.output_dir).resolve()
    source_root = Path.cwd().resolve()
    if source_root == output_dir or source_root in output_dir.parents:
        raise SystemExit("output directory must be outside source root")
    font_path = Path(args.font).resolve()
    pdfmetrics.registerFont(TTFont(FONT_NAME, str(font_path)))
    rows = []
    for packet in selected:
        index = int(packet["caseId"].split("-")[1])
        slug = re.sub(r"[^a-z0-9-]+", "-", packet["caseId"].lower()).strip("-")
        output = output_dir / packet["tier"] / f"{index:02d}-{slug}-{packet['tier']}-{packet['locale']}.pdf"
        row = render_packet(packet, output, font_path)
        manifest_root = Path(args.manifest).resolve().parent
        row["path"] = output.resolve().relative_to(manifest_root).as_posix()
        rows.append(row)
    envelope = {
        "schemaVersion": "velmere.pass36.a102r44p8.audit-pdf-corpus-manifest.v1",
        "status": "LOCAL_CUSTOMER_LIKE_PDF_CORPUS_NO_REAL_CUSTOMER_CREDIT",
        "documents": len(rows),
        "pages": sum(row["pageCount"] for row in rows),
        "byTier": {tier: sum(1 for row in rows if row["tier"] == tier) for tier in TIER_PAGES},
        "byLocale": {locale: sum(1 for row in rows if row["locale"] == locale) for locale in COPY},
        "rows": rows,
        "realCustomerPdfCredit": 0,
        "paidReleaseCredit": False,
        "truthBoundary": "Generated from 450 automated informational packets bound to 200 official-tool receipts and three deterministic Advanced-only derived evidence families. These are technical PDF tests, not deployed-contract, customer, human-review, independent-adjudication, Windows, staging, LIVE or sale evidence.",
    }
    Path(args.manifest).write_text(json.dumps(envelope, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({k: envelope[k] for k in ["status", "documents", "pages", "byTier", "byLocale", "realCustomerPdfCredit", "paidReleaseCredit"]}, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
