#!/usr/bin/env node
import fs from "node:fs";
import { A87_REVISION, evaluateA87RealIntake, runA87FixtureHarness, verifyA87Runtime } from "../../lib/worldclass/pass36-a87-market-impact-whale-watch-runtime.ts";
const policy = JSON.parse(fs.readFileSync("config/pass36/a87-market-impact-whale-watch-policy.json", "utf8"));
const receipt = JSON.parse(fs.readFileSync("config/pass36/a87-test-receipt.json", "utf8"));
const currentState = JSON.parse(fs.readFileSync("config/pass36/a87-current-state.json", "utf8"));
const runtime = await runA87FixtureHarness(process.cwd(), policy);
const real = evaluateA87RealIntake(JSON.parse(fs.readFileSync(policy.realIntakeIndex.path, "utf8")));
const checks: Array<{ id: string; passed: boolean; detail?: unknown }> = [];
const check = (id: string, passed: unknown, detail: unknown = null) => checks.push({ id, passed: Boolean(passed), detail });
check("receipt:schema", receipt.schemaVersion === "velmere.pass36.a87.market-impact-whale-watch-test-receipt.v1", receipt.schemaVersion);
check("receipt:revision", receipt.revisionId === A87_REVISION, receipt.revisionId);
check("receipt:status", receipt.status === "PASS_A87_LOCAL_COMMON_DENOMINATOR_NO_PROMOTION", receipt.status);
check("receipt:checks", receipt.summary?.failed === 0 && receipt.summary?.checks >= 30, receipt.summary);
check("runtime:verified", verifyA87Runtime(runtime, policy, receipt.runtimeIntegritySha256), runtime.denominators);
check("runtime:digest", runtime.integrity.digest === receipt.runtimeIntegritySha256, { runtime: runtime.integrity.digest, receipt: receipt.runtimeIntegritySha256 });
check("runtime:denominators", runtime.denominators.activeAssets === 318 && runtime.denominators.tierPackets === 1908 && runtime.denominators.channelProjections === 7632 && runtime.denominators.semanticMutations === 34344 && runtime.denominators.mutationKilled === 34344, runtime.denominators);
check("runtime:readiness", JSON.stringify(runtime.readiness) === JSON.stringify(receipt.readiness), { runtime: runtime.readiness, receipt: receipt.readiness });
check("runtime:market", runtime.readiness.market_impact.basic.functionalReadyOffline === 307 && runtime.readiness.market_impact.pro.functionalReadyOffline === 290 && runtime.readiness.market_impact.advanced.functionalReadyOffline === 245, runtime.readiness.market_impact);
check("runtime:whale", runtime.readiness.whale_watch.basic.functionalReadyOffline === 230 && runtime.readiness.whale_watch.pro.functionalReadyOffline === 150 && runtime.readiness.whale_watch.advanced.functionalReadyOffline === 85, runtime.readiness.whale_watch);
check("runtime:mutations", Object.values(runtime.mutationFamilyStats).every((row) => row.survived === 0), runtime.mutationFamilyStats);
check("runtime:invariants", Object.values(runtime.invariants).every((value) => value === 0), runtime.invariants);
check("runtime:locks", runtime.packets.every((row) => row.currentPublicNetworkExecuted === false && row.providerRightsApproved === false && row.realizedExecutionValidated === false && row.continuousMonitoringExecuted === false && row.paidGateEligible === false && row.liveProven === false && row.saleEnabled === false), null);
check("real:blocked", real.decision === "BLOCKED_REAL_MARKET_IMPACT_WHALE_EVIDENCE" && real.rows === 0, real);
check("state:revision", currentState.revisionId === A87_REVISION, currentState.revisionId);
check("state:truth", currentState.closedGaps === policy.closedByA87.length && currentState.activeAssets === 318 && currentState.tierPackets === 1908 && currentState.semanticMutations === 34344 && currentState.realEvidenceRows === 0 && currentState.providerRightsApproved === false && currentState.liveProven === false && currentState.saleEnabled === false, currentState);
check("policy:gaps", policy.closedByA87.length === 33, policy.closedByA87.length);
check("policy:real-index", policy.realIntakeIndex.path === "config/pass36/a87-real-evidence-index.json", policy.realIntakeIndex);
check("truth:no-promotion", receipt.exactA80CandidateBound === false && receipt.currentProviderEvidenceVerified === false && receipt.providerRightsApproved === false && receipt.realizedExecutionValidated === false && receipt.continuousMonitoringExecuted === false && receipt.customerValueProven === false && receipt.paidGateEligible === false && receipt.liveProven === false && receipt.saleEnabled === false, null);
const failed = checks.filter((row) => !row.passed);
const verdict = { schemaVersion: "velmere.pass36.a87.verifier.v1", revisionId: A87_REVISION, status: failed.length ? "FAIL_A87_VERIFIER" : "PASS_A87_LOCAL_MATRIX_NO_PROMOTION", summary: { checks: checks.length, passed: checks.length - failed.length, failed: failed.length }, failures: failed, checks };
console.log(JSON.stringify(verdict, null, 2));
if (failed.length) process.exit(1);
