#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
MASTER='VELMERE_ULTIMATE_WORLD_CLASS_CONTINUOUS_CLOSURE_FINAL_CANDIDATE_MASTER_DIRECTIVE_V2_COMPLETE_2026-08-20.txt'
V17='VELMERE_CANONICAL_OWNER_DIRECTIVE_V17_TRUE_TOPOLOGY_AUTOMATED_ADVANCED_CURRENT_WORLD_CLASS_2026-08-17.txt'

def sha(p:Path):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for c in iter(lambda:f.read(4*1024*1024),b''):h.update(c)
 return h.hexdigest()
def load(rel):return json.loads((ROOT/rel).read_text())
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--package-verification',required=True);ap.add_argument('--output',required=True);a=ap.parse_args()
 pv=json.loads(Path(a.package_verification).read_text());out=Path(a.output)
 auth=load('artifacts/closure/p89r1/P89R1_AUTHORITY_BINDING.json');prod=load('artifacts/closure/p89r1/P89R1_CURRENT_PRODUCT_PROJECTION_MANIFEST.json');tests=load('artifacts/closure/p89r1/P89R1_TEST_AGGREGATE.json');hist=load('artifacts/closure/p89r1/P89R1_HISTORICAL_RECEIPT_IMMUTABILITY.json');block=load('artifacts/closure/p89r1/P89R1_CURRENT_BLOCKER_QUEUE.json');runtime=load('receipts/p89/P89_AUDIT_PROVIDER_EVIDENCE_DIMENSIONS_RUNTIME.json');pdf=load('receipts/p89/P89_AUDIT_PDF_EVIDENCE_DIMENSIONS_RUNTIME.json');fail=load('artifacts/closure/p89r1/P89R1_FAILURE_ADJUDICATION.json')
 p=prod['currentCandidateProjection'];parent=prod['parentProjection'];final=pv['final']
 lines=[]
 A=lines.append
 A('VELMÈRE CURRENT STATE & PASS DELTA LEDGER — P89R1 / V17 + COMPLETE MASTER DIRECTIVE V2')
 A('DATE: 2026-08-20')
 A('CLASSIFICATION: PASS_BOUNDED_P89R1_AUDIT_PROVIDER_EVIDENCE_DIMENSION_SEPARATION_ANTI_DUPLICATION')
 A('GLOBAL: NO_GO / STOP_SELL')
 A('LIVE: false')
 A('SALE_ENABLED: false')
 A('PRODUCTION_APPROVED: false')
 A('WORLD_CLASS_PROVEN: false')
 A('')
 A('======================================================================')
 A('TABLE 0 — PRODUCT TOPOLOGY TRUTH')
 A('======================================================================')
 A('Family | Customer-facing rows | P89 result')
 for family,rows in [('Audit','Basic / Pro / Advanced'),('Browser','Basic / Pro / Advanced'),('Shield','Basic / Pro / Advanced'),('Shield Pro','Basic / Pro / Advanced'),('Real Markets','Basic / Pro / Advanced'),('Shield Map','standalone'),('Market Impact','standalone FREE'),('Whale Watch','standalone FREE'),('Angel','standalone AI brain/chat'),('Risk Indicator','standalone')]:A(f'{family} | {rows} | UNCHANGED / V17 BOUND')
 A('Canonical denominator: 10 families / 20 customer-facing rows / 20 execution profiles / 10 material paid transitions.')
 A('PDF remains an artifact, not a product family.')
 A('')
 A('======================================================================')
 A('TABLE 1 — CUSTOMER-FACING CLOSURE')
 A('======================================================================')
 A('Product/SKU | Customer FINAL | P89 current truth | Sale eligibility | Hard blocker')
 rows=[
 ('Audit Basic','WITHHELD','no new FINAL; P88 storage path preserved','false','real deployed customer chain absent'),
 ('Audit Pro','WITHHELD','structural contract can represent 4 strict + 5 successful live; no real P89 providers executed','false','rights/currentness/provider execution + deployed chain absent'),
 ('Audit Advanced','WITHHELD','current architecture shape 4 strict + 5 live; positive control 5 + 6 only','false','one additional independent strict-capable direct provider plus real rights/currentness'),
 ('Browser Basic / Pro / Advanced','WITHHELD','no P89 FINAL promotion','false','complete current end-to-end proof absent'),
 ('Shield Basic / Pro / Advanced','WITHHELD','no P89 FINAL promotion','false','complete current evidence/value chain absent'),
 ('Shield Pro Basic / Pro / Advanced','WITHHELD','no P89 FINAL promotion','false','complete functional/customer/value proof absent'),
 ('Real Markets Basic / Pro / Advanced','WITHHELD','P87 exact-PDF regression preserved','false','real rights/current customer chain absent'),
 ('Shield Map','WITHHELD','no P89 FINAL promotion','false','complete current customer chain absent'),
 ('Market Impact FREE','WITHHELD','no P89 FINAL promotion','false','lawful/current order-book evidence not closed'),
 ('Whale Watch FREE','WITHHELD','no P89 FINAL promotion','false','chain/finality/customer proof absent'),
 ('Angel','WITHHELD','no P89 FINAL promotion','false','final AI evaluation/governance absent'),
 ('Risk Indicator','WITHHELD','no P89 FINAL promotion','false','versioned/calibrated final customer chain absent'),
 ]
 for r in rows:A(' | '.join(r))
 A('Customer FINAL: 0/20.')
 A('Audit FINAL PDF: 0/3.')
 A('')
 A('======================================================================')
 A('TABLE 2 — CURRENT P89 EXECUTION / EVIDENCE')
 A('======================================================================')
 A('Lane | Result | Credit boundary')
 A('P89 provider evidence dimensions runtime | 36/36 PASS | controlled local fixtures only')
 A('P89 current/legacy PDF schema runtime | 32/32 PASS | controlled Basic artifact + paid gate objects only')
 A('P89 provider dimensions static | 81/81 PASS | source/contract proof only')
 A('P89 runtime repeatability | 11/11 PASS | two byte-identical runs/receipts')
 A('P89 changed production/customer-path imports | 12/12 PASS | local import reachability')
 A('P89 targeted strict TypeScript | 1/1 PASS | new self-contained dimension module only')
 A('P89/P88 compatibility/history | 40/40 PASS | P88 storage/migration/routes and old model semantics preserved')
 A('Current segmented regression | 29 lanes / 1,302 checks PASS | overlapping local/static/runtime checks')
 A('Historical parent receipts/artifacts | 1,628 exact / 0 mismatches | P88 history byte-identical')
 A('IMPORTANT: 1,302 is not accuracy, provider independence, customer count, FINAL, rights, database, deployment or release proof.')
 A('')
 A('======================================================================')
 A('TABLE 3 — P88 → P89 SEMANTIC CORRECTION')
 A('======================================================================')
 A('Dimension | P88 behavior | P89 behavior')
 A('Strict evidence receipts | also used to satisfy live-lane floor through max()/shared count | exact-response matched receipts counted separately')
 A('Successful live executions | not independently represented in paid readiness/PDF | successful bounded direct-provider calls counted separately')
 A('Evidence rows | present in tier contract but not consistently enforced in PDF gate | separate current-model floor')
 A('Provider duplication | retries/aliases risked ambiguous counting | one canonical providerId occupies at most one slot per dimension')
 A('Partial direct provider | could be conflated with strict readiness | may count successful live execution only; never strict evidence')
 A('Submitted/human lanes | non-direct lanes | never count as live provider execution')
 A('P88 receipts | risk of inheriting later semantics | retain old stricter combined rule; no retroactive promotion')
 A('Thresholds were not lowered: Pro remains 4 strict / 3 families / 5 live / 6 evidence rows; Advanced remains 5 / 4 / 6 / 10.')
 A('')
 A('======================================================================')
 A('TABLE 4 — CONTROLLED ARCHITECTURE RESULTS')
 A('======================================================================')
 c=runtime['controlledResults']
 A(f"Pro controlled shape | strict {c['pro']['strictReceipts']} | live {c['pro']['successfulLiveProviders']} | structural gate met={str(c['pro']['met']).lower()}")
 ac=c['advancedCurrentArchitectureShape']
 A(f"Advanced current architecture shape | strict {ac['strictReceipts']} | live {ac['successfulLiveProviders']} | met={str(ac['met']).lower()} | blockers={','.join(ac['blockers'])}")
 ap=c['advancedPositiveControl']
 A(f"Advanced positive control | strict {ap['strictReceipts']} | live {ap['successfulLiveProviders']} | met={str(ap['met']).lower()}")
 art=pdf['currentControlledArtifact']
 A(f"Current controlled Basic PDF | {art['pdfByteLength']} B | {art['pdfDigest']} | LOCAL FIXTURE / NOT FINAL")
 A('No real provider execution, rights, currentness or paid-readiness credit is granted by these fixtures.')
 A('')
 A('======================================================================')
 A('TABLE 5 — PRODUCT SOURCE PROJECTION')
 A('======================================================================')
 A(f"Metric | P88 parent | P89 current | Delta")
 A(f"Files | {parent['fileCount']} | {p['fileCount']} | {p['fileCount']-parent['fileCount']:+d}")
 A(f"Payload | {parent['payloadBytes']} B | {p['payloadBytes']} B | {p['payloadBytes']-parent['payloadBytes']:+d} B")
 A(f"Path-set SHA-256 | {parent['pathSetSha256']} | {p['pathSetSha256']} | changed")
 A(f"Aggregate SHA-256 | {parent['sourceContentAggregateSha256']} | {p['sourceContentAggregateSha256']} | changed")
 A('Build-relevant files: 6 (one new dimension module, five modified consumers).')
 A('Database schema/migrations: unchanged from P88; authorized runtime remains WITHHELD.')
 A('')
 A('======================================================================')
 A('TABLE 6 — GLOBAL DENOMINATORS')
 A('======================================================================')
 for row in [('Master Directive V2','38,471 B / sections 0–88 exact','OWNER AUTHORITY'),('V17','66,416 B exact / unchanged','CANONICAL TOPOLOGY'),('Customer FINAL','0/20','WITHHELD'),('Audit FINAL PDF','0/3','WITHHELD'),('Rights','2/203 inherited only','WITHHELD'),('Paid value','0/10','WITHHELD'),('Sale eligible','0/20','WITHHELD'),('PILOT_READY','false','WITHHELD'),('GO_PAID','false','WITHHELD'),('LIVE','false','WITHHELD'),('WORLD_CLASS_PROVEN','false','WITHHELD')]:A(' | '.join(row))
 A('')
 A('======================================================================')
 A('1. PHYSICAL P89 PRODUCT CHANGES')
 A('======================================================================')
 for path in prod['changedBuildRelevantFiles']:A(f"- {path['path']} ({path['change']})")
 A('P89 introduces a versioned evidence-dimension boundary and propagates it through readiness, immutable receipt packet, runtime summary, confidence logic and customer PDF schema.')
 A('P88 exact render-once/store-first PDF bytes, migration, snapshot store, settle routes and download route remain byte-identical where not explicitly versioned.')
 A('')
 A('======================================================================')
 A('2. FAILURE / FLAKINESS ADJUDICATION')
 A('======================================================================')
 for r in fail['rows']:A(f"- {r['id']}: {r['state']} / credit {r['credit']} / {r['rootCause']}")
 A('No partial credit was taken from nonzero or incomplete harnesses. The repeated monolithic orchestration stall was replaced by process-bounded segmented execution and independent log verification, not brute-force retries.')
 A('')
 A('======================================================================')
 A('3. RIGHTS / CURRENTNESS / SECURITY BOUNDARY')
 A('======================================================================')
 A('P89 executed no external provider network request and added no field-level rights credit.')
 A('A public endpoint, configured URL or successful fixture is not commercial permission or current customer evidence.')
 A('No transaction, state change, live exploit, weaponized PoC, authorization bypass or external-system scan was performed.')
 A('')
 A('======================================================================')
 A('4. TYPE / LINT / BUILD / EXACT WINDOWS')
 A('======================================================================')
 A('Local: Node v22.16.0 / npm 10.9.2 / TypeScript 5.8.3 / Linux x86_64.')
 A('Targeted strict TypeScript: PASS for the new evidence-dimension core.')
 A('12 changed/current customer-path module imports: PASS.')
 A('Whole-project TypeScript, ESLint, Webpack, Turbopack and exact Windows Server 2025 on P89 bytes: WITHHELD_DEPENDENCY_ENVIRONMENT_MISSING.')
 A('No P88/P77 exact-Windows result is inherited onto P89 changed bytes.')
 A('')
 A('======================================================================')
 A('5. DETERMINISTIC SOURCE_ONLY')
 A('======================================================================')
 A(f"Output: {pv['output']}")
 A(f"Entries: {final['entryCount']}")
 A(f"Bytes: {final['bytes']}")
 A(f"SHA-256: {final['sha256']}")
 A('Deterministic rebuild: 2/2 BYTE_IDENTICAL')
 A('CRC: PASS for both builds')
 A('Clean unpack: PASS_PATH_AND_CONTENT_IDENTITY')
 A('Ordering: lexicographic; timestamp: 1980-01-01T00:00:00Z; directory entries: 0; createSystem: 0.')
 A('Full private-key/credential scan: 0 matches. Current P89 unexpected binary scan: 0 matches.')
 A('')
 A('======================================================================')
 A('6. NEXT HIGHEST-VALUE EXECUTION')
 A('======================================================================')
 for r in block['rows']:A(f"{r['priority']}. {r['id']} — {r['state']} — {r['nextSafeAction']}")
 A('Pro is no longer structurally impossible, but remains WITHHELD until four distinct strict receipts and five successful rights-bound direct providers physically execute on current input. Advanced remains structurally short at 4 strict / 5 live and requires one additional genuinely independent strict-capable direct provider.')
 A('')
 A('======================================================================')
 A('7. CURRENT VERDICT')
 A('======================================================================')
 A('P89R1: PASS_BOUNDED for the local evidence-dimension correction, anti-duplication, version separation and customer PDF schema binding.')
 A('Customer FINAL remains 0/20. Audit FINAL PDF remains 0/3. Global remains NO_GO / STOP_SELL.')
 A('END OF LEDGER')
 out.write_text('\n'.join(lines)+'\n',encoding='utf-8')
 print(json.dumps({'status':'PASS','output':str(out),'bytes':out.stat().st_size,'sha256':sha(out),'package':final},indent=2))
if __name__=='__main__':main()
