create table if not exists velmere_private.r7_shield_pro_paid_release_authority_v1(
 tier text primary key check(tier in('pro','advanced')),
 customer_ordinal integer not null check(customer_ordinal in(11,12)),
 customer_slug text not null check(customer_slug in('shield-pro-pro','shield-pro-advanced')),
 paid_ordinal integer not null check(paid_ordinal in(7,8)),
 paid_slug text not null check(paid_slug in('shield-pro-pro','shield-pro-advanced')),
 github_run_id text not null check(github_run_id~'^[1-9][0-9]{0,19}$'),github_artifact_id text not null check(github_artifact_id~'^[1-9][0-9]{1,20}$'),github_sha text not null check(github_sha~'^[a-f0-9]{40}$'),
 workflow_sha256 text not null check(workflow_sha256~'^[a-f0-9]{64}$'),artifact_digest_sha256 text not null check(artifact_digest_sha256~'^[a-f0-9]{64}$'),bridge_sha256 text not null check(bridge_sha256~'^[a-f0-9]{64}$'),helper_sha256 text not null check(helper_sha256~'^[a-f0-9]{64}$'),finalizer_edge_sha256 text not null check(finalizer_edge_sha256~'^[a-f0-9]{64}$'),engine_sql_sha256 text not null check(engine_sql_sha256~'^[a-f0-9]{64}$'),finalizer_sql_sha256 text not null check(finalizer_sql_sha256~'^[a-f0-9]{64}$'),
 full_source_aggregate_sha256 text not null,execution_slice_aggregate_sha256 text not null,execution_slice_manifest_sha256 text not null,execution_bundle_sha256 text not null,
 workspace_function_sha256 text not null,entitlement_function_sha256 text not null,finalizer_function_sha256 text not null,created_at timestamptz not null default clock_timestamp()
);
create or replace function velmere_private.block_r7_shield_pro_paid_release_authority_v1_mutation() returns trigger language plpgsql set search_path=pg_catalog as $f$ begin raise exception 'shield_pro_paid_release_authority_append_only' using errcode='42501'; end $f$;
drop trigger if exists r7_shield_pro_paid_release_authority_v1_append_only on velmere_private.r7_shield_pro_paid_release_authority_v1;
create trigger r7_shield_pro_paid_release_authority_v1_append_only before update or delete on velmere_private.r7_shield_pro_paid_release_authority_v1 for each row execute function velmere_private.block_r7_shield_pro_paid_release_authority_v1_mutation();
revoke all on table velmere_private.r7_shield_pro_paid_release_authority_v1 from public,anon,authenticated;grant select on table velmere_private.r7_shield_pro_paid_release_authority_v1 to service_role;

create or replace function public.velmere_r7_finalize_shield_pro_paid_tier_v1(
 p_tier text,p_github_run_id text,p_github_artifact_id text,p_github_sha text,p_workflow_sha256 text,p_artifact_digest_sha256 text,
 p_bridge_sha256 text,p_helper_sha256 text,p_finalizer_edge_sha256 text,p_engine_sql_sha256 text,p_finalizer_sql_sha256 text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,velmere_private,extensions
as $f$
declare
 v_source velmere_private.r7_source_authority%rowtype;v_release velmere_private.r7_shield_pro_paid_release_authority_v1%rowtype;
 v_customer_ordinal integer;v_customer_slug text;v_paid_ordinal integer;v_paid_slug text;v_asset_limit integer;
 v_workspace_sha text;v_entitlement_sha text;v_finalizer_sha text;v_grants integer;v_revokes integer;v_creates integer;v_locales integer;v_deletes integer;v_restores integer;v_assets integer;
 v_customer jsonb;v_paid jsonb;v_paid_result jsonb;v_evidence jsonb;
begin
 if p_tier not in('pro','advanced') then raise exception 'shield_pro_paid_tier_invalid' using errcode='22023'; end if;
 v_customer_ordinal:=case when p_tier='pro' then 11 else 12 end;v_customer_slug:=case when p_tier='pro' then 'shield-pro-pro' else 'shield-pro-advanced' end;
 v_paid_ordinal:=case when p_tier='pro' then 7 else 8 end;v_paid_slug:=v_customer_slug;v_asset_limit:=case when p_tier='pro' then 3 else 6 end;
 if p_github_run_id!~'^[1-9][0-9]{0,19}$' or p_github_artifact_id!~'^[1-9][0-9]{1,20}$' or p_github_sha!~'^[a-f0-9]{40}$'
 or p_workflow_sha256!~'^[a-f0-9]{64}$' or p_artifact_digest_sha256!~'^[a-f0-9]{64}$' or p_bridge_sha256!~'^[a-f0-9]{64}$' or p_helper_sha256!~'^[a-f0-9]{64}$' or p_finalizer_edge_sha256!~'^[a-f0-9]{64}$' or p_engine_sql_sha256!~'^[a-f0-9]{64}$' or p_finalizer_sql_sha256!~'^[a-f0-9]{64}$' then raise exception 'shield_pro_paid_identity_invalid' using errcode='22023'; end if;
 select * into strict v_source from velmere_private.r7_source_authority where singleton=true;
 if v_source.exact_windows_status is distinct from 'PASS' or v_source.test_denominator is distinct from 52 or v_source.source_aggregate_sha256 is distinct from '50d59f5f028ef73b279fa3930889fcbf2ab5bc5e36ab4e8cec97be5ed49be67e' or v_source.execution_slice_aggregate_sha256 is distinct from 'f83f28de6add73eee70d9086f2705241243661d64b5c9fd579b17b359050a221' or v_source.execution_slice_manifest_sha256 is distinct from 'b947314bb696fb8f9153c34d46ba825c5897e9f8cc8cf911a5f31113aa5fc01f' or v_source.execution_bundle_sha256 is distinct from '8e3c66471d534310e1142c3671d43bb556e35b6901c847c9596eea14e8815967' or v_source.github_sha is distinct from '50840bb5a2cdc4384a557114e64a115828f97143' or v_source.exact_windows_run_id is distinct from '33056763944' or v_source.exact_windows_run_attempt is distinct from 1 then raise exception 'shield_pro_paid_source_authority_not_satisfied' using errcode='23514'; end if;
 v_workspace_sha:=encode(extensions.digest(pg_get_functiondef('public.velmere_r7_shield_pro_paid_workspace_v1(text,text,text,uuid)'::regprocedure),'sha256'),'hex');
 v_entitlement_sha:=encode(extensions.digest(pg_get_functiondef('public.velmere_r7_shield_pro_has_paid_entitlement_v1(text)'::regprocedure),'sha256'),'hex');
 v_finalizer_sha:=encode(extensions.digest(pg_get_functiondef('public.velmere_r7_finalize_shield_pro_paid_tier_v1(text,text,text,text,text,text,text,text,text,text,text)'::regprocedure),'sha256'),'hex');
 select * into v_release from velmere_private.r7_shield_pro_paid_release_authority_v1 where tier=p_tier;
 if not found then insert into velmere_private.r7_shield_pro_paid_release_authority_v1(tier,customer_ordinal,customer_slug,paid_ordinal,paid_slug,github_run_id,github_artifact_id,github_sha,workflow_sha256,artifact_digest_sha256,bridge_sha256,helper_sha256,finalizer_edge_sha256,engine_sql_sha256,finalizer_sql_sha256,full_source_aggregate_sha256,execution_slice_aggregate_sha256,execution_slice_manifest_sha256,execution_bundle_sha256,workspace_function_sha256,entitlement_function_sha256,finalizer_function_sha256)
 values(p_tier,v_customer_ordinal,v_customer_slug,v_paid_ordinal,v_paid_slug,p_github_run_id,p_github_artifact_id,p_github_sha,p_workflow_sha256,p_artifact_digest_sha256,p_bridge_sha256,p_helper_sha256,p_finalizer_edge_sha256,p_engine_sql_sha256,p_finalizer_sql_sha256,v_source.source_aggregate_sha256,v_source.execution_slice_aggregate_sha256,v_source.execution_slice_manifest_sha256,v_source.execution_bundle_sha256,v_workspace_sha,v_entitlement_sha,v_finalizer_sha) returning * into v_release;end if;
 if v_release.github_run_id<>p_github_run_id or v_release.github_artifact_id<>p_github_artifact_id or v_release.github_sha<>p_github_sha or v_release.workflow_sha256<>p_workflow_sha256 or v_release.artifact_digest_sha256<>p_artifact_digest_sha256 or v_release.bridge_sha256<>p_bridge_sha256 or v_release.helper_sha256<>p_helper_sha256 or v_release.finalizer_edge_sha256<>p_finalizer_edge_sha256 or v_release.engine_sql_sha256<>p_engine_sql_sha256 or v_release.finalizer_sql_sha256<>p_finalizer_sql_sha256 or v_release.workspace_function_sha256<>v_workspace_sha or v_release.entitlement_function_sha256<>v_entitlement_sha or v_release.finalizer_function_sha256<>v_finalizer_sha then raise exception 'shield_pro_paid_release_authority_mismatch' using errcode='23514';end if;
 select count(*) filter(where event_kind='GRANT'),count(*) filter(where event_kind='REVOKE') into v_grants,v_revokes from velmere_private.r7_shield_pro_paid_entitlement_events where tier=p_tier and authority='E2E_TEST_NO_PAYMENT_CREDIT' and evidence->>'githubRunId'=p_github_run_id;
 if v_grants<>1 or v_revokes<>1 then raise exception 'shield_pro_paid_entitlement_lifecycle_not_satisfied' using errcode='23514';end if;
 select count(*) filter(where event_kind='CREATE'),count(distinct locale) filter(where event_kind='CREATE'),count(*) filter(where event_kind='DELETE'),count(*) filter(where event_kind='RESTORE') into v_creates,v_locales,v_deletes,v_restores from velmere_private.r7_shield_pro_paid_workspace_events where tier=p_tier and e2e_run_id=p_github_run_id;
 if v_creates<3 or v_locales<>3 or v_deletes<1 or v_restores<1 or not exists(select 1 from velmere_private.r7_shield_pro_paid_workspace_events d join velmere_private.r7_shield_pro_paid_workspace_events r on r.workspace_id=d.workspace_id and r.account_id=d.account_id and r.payload_digest_sha256=d.payload_digest_sha256 and r.event_kind='RESTORE' where d.tier=p_tier and d.e2e_run_id=p_github_run_id and d.event_kind='DELETE') then raise exception 'shield_pro_paid_workspace_lifecycle_not_satisfied' using errcode='23514';end if;
 select count(*) into v_assets from(select e.asset_id from public.velmere_risk_history_events e where e.publication_state='PUBLIC' and e.customer_publishable=true and e.observed_at>=clock_timestamp()-interval '7 days' group by e.asset_id having count(*)>=2 limit v_asset_limit)s;
 if v_assets<>v_asset_limit then raise exception 'shield_pro_paid_asset_denominator_not_satisfied' using errcode='23514';end if;
 v_evidence:=jsonb_build_object('schemaVersion','velmere.r7.shield-pro-paid-final-evidence.v1','tier',p_tier,'githubRunId',p_github_run_id,'githubArtifactId',p_github_artifact_id,'githubHeadSha',p_github_sha,'workflowSha256',p_workflow_sha256,'artifactDigestSha256',p_artifact_digest_sha256,'bridgeSha256',p_bridge_sha256,'helperSha256',p_helper_sha256,'finalizerEdgeSha256',p_finalizer_edge_sha256,'engineSqlSha256',p_engine_sql_sha256,'finalizerSqlSha256',p_finalizer_sql_sha256,'sourceAuthorityRunId',v_source.exact_windows_run_id,'sourceAuthorityHeadSha',v_source.github_sha,'exactWindows','PASS_52_X2','testDenominator',52,'realEntitlement',true,'entitlementLifecycleGrantRevoke',true,'testEntitlementNoPaymentCredit',true,'basicCannotAccess',true,'paidUserCanAccess',true,'crossAccountDenied',true,'materialPaidValue',true,'materialDelta',case when p_tier='pro' then 'THREE_TARGET_PERSISTENT_MONITORING_HISTORY' else 'SIX_TARGET_PRIORITY_CORRELATION_TEAM_AUTOMATION_WORKFLOW' end,'customerVisibleTiles',true,'coverageAssets',v_asset_limit,'historyEventsPerAsset',2,'workspaceCreateDeleteRestoreExactDigest',true,'locales',jsonb_build_array('pl','en','de'),'rightsValid',true,'sourceClass','VELMERE_GENERATED_PUBLIC_EVIDENCE_FROM_DIRECT_CHAIN_BOUND_SOURCE','customerDisplayRightsBasis','FIRST_PARTY_DERIVED_CUSTOMER_PUBLISHABLE_EVIDENCE_NO_EXTERNAL_PROVIDER_PAYLOAD','providerNetworkCalls',0,'failClosed',true,'paymentTransactionClaimed',false);
 select to_jsonb(l) into v_customer from public.velmere_r7_customer_final_ledger l where l.product_slug=v_customer_slug;
 if v_customer is null then insert into public.velmere_r7_customer_final_ledger(product_ordinal,product_slug,final_status,full_source_aggregate_sha256,execution_slice_aggregate_sha256,evidence) values(v_customer_ordinal,v_customer_slug,'FINAL',v_source.source_aggregate_sha256,v_source.execution_slice_aggregate_sha256,v_evidence||jsonb_build_object('paidValueCredit',true)) returning to_jsonb(public.velmere_r7_customer_final_ledger) into v_customer;end if;
 select public.velmere_r7_finalize_paid_value_transition_v1(v_paid_ordinal,v_paid_slug,v_evidence,v_source.source_aggregate_sha256,v_source.execution_slice_aggregate_sha256) into v_paid_result;
 select to_jsonb(l) into v_paid from public.velmere_r7_paid_value_final_ledger l where l.transition_slug=v_paid_slug;
 if v_paid is null then raise exception 'shield_pro_paid_ledger_re_read_failed' using errcode='23514';end if;
 return jsonb_build_object('ok',true,'tier',p_tier,'customer',v_customer,'paid',v_paid,'paidFinalizerResult',v_paid_result,'customerFinalCount',(select count(*) from public.velmere_r7_customer_final_ledger),'paidFinalCount',(select count(*) from public.velmere_r7_paid_value_final_ledger));
end $f$;
revoke all on function public.velmere_r7_finalize_shield_pro_paid_tier_v1(text,text,text,text,text,text,text,text,text,text,text) from public,anon,authenticated;grant execute on function public.velmere_r7_finalize_shield_pro_paid_tier_v1(text,text,text,text,text,text,text,text,text,text,text) to service_role;