#!/usr/bin/env python3
"""Build external P85R1 ledger from closure and package receipts."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path

def sha(p:Path):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for c in iter(lambda:f.read(4*1024*1024),b''): h.update(c)
 return h.hexdigest()
def load(p:Path): return json.loads(p.read_text(encoding='utf-8'))
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--root',required=True); ap.add_argument('--zip',required=True); ap.add_argument('--verification',required=True); ap.add_argument('--output',required=True); a=ap.parse_args()
 root=Path(a.root).resolve(); zp=Path(a.zip).resolve(); ver=load(Path(a.verification).resolve()); out=Path(a.output).resolve(); c=root/'artifacts/closure/p85r1'
 ck=load(c/'P85R1_CHECKPOINT_RECEIPT.json'); pr=load(c/'P85R1_CURRENT_PRODUCT_PROJECTION_MANIFEST.json'); src=load(c/'P85R1_SOURCE_CHANGE_MANIFEST.json'); tests=load(c/'P85R1_TEST_AGGREGATE.json'); hist=load(c/'P85R1_HISTORICAL_RECEIPT_IMMUTABILITY.json')
 rt=load(root/'receipts/p85/P85_OWNER_VISIBLE_CUSTOMER_ARTIFACT_RUNTIME.json'); rep=load(root/'receipts/p85/P85_OWNER_VISIBLE_CUSTOMER_ARTIFACT_REPEATABILITY.json'); st=load(root/'receipts/p85/P85_OWNER_VISIBLE_CUSTOMER_ARTIFACT_STATIC.json'); c84=load(root/'receipts/p85/P85_P84_OWNER_READ_COMPATIBILITY.json'); c80=load(root/'receipts/p85/P85_P80_IMMUTABLE_ARTIFACT_COMPATIBILITY.json')
 z=ver['final']; product=pr['currentCandidateProjection']
 if z['sha256']!=sha(zp) or z['bytes']!=zp.stat().st_size: raise RuntimeError('ledger_package_identity_mismatch')
 rows20=['Audit Basic','Audit Pro','Audit Advanced','Browser Basic','Browser Pro','Browser Advanced','Shield Basic','Shield Pro','Shield Advanced','Shield Pro Basic','Shield Pro Pro','Shield Pro Advanced','Real Markets Basic','Real Markets Pro','Real Markets Advanced','Shield Map','Market Impact FREE','Whale Watch FREE','Angel','Risk Indicator']
 L=[
 'VELMÈRE CURRENT STATE & PASS DELTA LEDGER — P85R1 / V17','DATE: 2026-08-20','CLASSIFICATION: PASS_BOUNDED_P85R1_AUDIT_DATABASE_ENFORCED_PUBLICATION_VISIBILITY_OWNER_RPC','GLOBAL: NO_GO / STOP_SELL','LIVE: false','SALE_ENABLED: false','PRODUCTION_APPROVED: false','WORLD_CLASS_PROVEN: false','',
 'TABLE 0 — PRODUCT TOPOLOGY TRUTH','Family group | Customer rows | Current truth | P85 change','Tiered: Audit / Browser / Shield / Shield Pro / Real Markets | 15 | Basic/Pro/Advanced only | Audit delivery read boundary repaired; topology unchanged','Standalone: Shield Map / Market Impact / Whale Watch / Angel / Risk Indicator | 5 | one profile each; Market Impact and Whale Watch free | unchanged','TOTAL | 20 rows / 20 profiles / 10 paid transitions | V17 binding preserved | PASS_TOPOLOGY_UNCHANGED','PDF | artifact obligation, not family/SKU | Audit 3 + Browser where promised | no denominator inflation','',
 'TABLE 1 — CUSTOMER-FACING CLOSURE, CURRENT 20-ROW DENOMINATOR','Product/SKU | P84 FINAL | P85 FINAL | Current P85 evidence | Hard blocker | Sale']
 for row in rows20:
  if row.startswith('Audit '): ev='database-enforced publication visibility implemented; static/local mocked RPC proof'; bl='authorized PostgreSQL/RLS/JWT/PostgREST/deployed-byte proof'
  else: ev='not re-executed or promoted in P85'; bl='unchanged product-specific closure gates'
  L.append(f'{row} | 0/1 | 0/1 | {ev} | {bl} | STOP_SELL')
 L += ['','TABLE 2 — CURRENT 20-PROFILE EXECUTION','Profile | Previous exact current execution | P85 execution | Exact customer bytes/hash | Credit']
 for row in rows20: L.append(f"{row} | no inherited current-byte FINAL | {'LOCAL_MOCKED_OWNER_RPC_ONLY' if row.startswith('Audit ') else 'NOT_EXECUTED_IN_P85'} | WITHHELD | no FINAL/profile closure credit")
 L += ['','TABLE 3 — CURRENT → TARGET → GAP','Area | P84 current | P85 target | Action completed | Result | Remaining gap',
 'Audit snapshot/PDF visibility | owner RLS accepted any owner-bound row | only fully published exact Audit artifact visible | P85 RLS requires immutable P84 link and exact owner/snapshot/artifact/PDF digest bindings | 86/86 static + 45/45 local RPC runtime | real PostgreSQL/RLS/PostgREST execution',
 'Artifact list | fetch up to 50 then N+1 link filtering in route | filter publication before LIMIT | one SECURITY INVOKER owner RPC, no caller account id | local/runtime/static PASS | staging query plan and >50-orphan runtime proof',
 'Artifact get | route and direct REST boundaries could diverge | one database-enforced owner-visible result | owner derived from auth binding; closed 14-field projection | tamper/extra/missing/order/duplicate cases rejected | two real owner JWTs and cross-account non-disclosure',
 'Preview identity | durable helper initially accepted preview:* | preview cannot enter durable RPC | preview rejected before RPC | runtime PASS | deployed account routes',
 'PDF delivery | immutable bytes exist | published-only owner read + route parity | no PDF re-render introduced | PDF 22/22 + 55/55 PASS | preview/download/account real bytes','',
 'TABLE 4 — DATA / RIGHTS / FRESHNESS','Field/source | Product | Rights/currentness | P85 result | Blocker',
 'Customer-owned Audit snapshot/PDF/publication link | Audit | Velmère-owned derived artifact; object authorization required | publication visibility boundary repaired in source | staging RLS/JWT/PostgREST proof',
 'Historical public-chain incident metadata | Audit | inherited bounded historical record | unchanged | no current-risk promotion',
 'Current BSC deployment state | Audit | NOT PROVEN | not executed in P85 | independent rights-bound provider quorum',
 'Raw external Solidity/ABI/trace/state | Audit | private / redistribution blocked | remains excluded | no raw customer redistribution',
 'Rights numerator | all products | 2/203 inherited only | unchanged | field-level rights/currentness program','',
 'TABLE 5 — GLOBAL DENOMINATORS','Metric | P84R1 | P85R1 | Delta | Credit class',
 'Canonical authority binding | V17 bound | V17 bound | 0 | PASS_BYTE_IDENTICAL',
 f"Source/package reproducibility | P84 {ck['canonicalBinding']['parentSourceOnlyEntries']} entries | P85 {z['entryCount']} entries | {z['entryCount']-ck['canonicalBinding']['parentSourceOnlyEntries']:+d} | 2/2 BYTE_IDENTICAL + CRC + clean unpack",
 'Customer FINAL | 0/20 | 0/20 | 0 | WITHHELD','Audit FINAL PDF | 0/3 | 0/3 | 0 | WITHHELD','Rights | 2/203 inherited | 2/203 inherited | 0 | no expansion','Paid value | 0/10 | 0/10 | 0 | no expansion','Sale eligible | 0/20 | 0/20 | 0 | STOP_SELL','Convergence rounds | 0/3 final RC rounds | 0/3 | 0 | not started','FINAL_AI_VALIDATION | not ready | not ready | 0 | not started','REAL_EXTERNAL_PROOF | none credited | none credited | 0 | not started','',
 '0. CANONICAL BINDING','', 'Canonical owner directive:',ck['canonicalBinding']['directiveFile'],f"Bytes: {(root/ck['canonicalBinding']['directiveFile']).stat().st_size:,}",f"SHA-256: {ck['canonicalBinding']['directiveSha256']}",'Directive changed in P85R1: NO','Reason: V17 already requires object-level authorization, immutable stored bytes and fail-closed delivery. P85 closes implementation gaps without authority churn.','',
 'Parent current checkpoint: P84R1',f"Parent ledger SHA-256: {ck['canonicalBinding']['parentLedgerSha256']}",f"Parent ledger bytes: {ck['canonicalBinding']['parentLedgerBytes']:,}",f"Parent SOURCE_ONLY SHA-256: {ck['canonicalBinding']['parentSourceOnlySha256']}",f"Parent SOURCE_ONLY bytes: {ck['canonicalBinding']['parentSourceOnlyBytes']:,}",f"Parent SOURCE_ONLY entries: {ck['canonicalBinding']['parentSourceOnlyEntries']:,}",'',
 'Current P85R1 SOURCE_ONLY:',zp.name,f"Bytes: {z['bytes']:,}",f"Entries: {z['entryCount']:,}",f"SHA-256: {z['sha256']}",f"Deterministic package rebuild: {ver['deterministicRebuild']}",f"ZIP CRC: {z['crc']}",f"Clean unpack: {z['cleanUnpack']}",'ZIP ordering: lexicographic','ZIP timestamp: fixed 1980-01-01T00:00:00Z','Directory entries: 0','ZIP createSystem: 0','Private-key/credential scan: PASS / 0 matches','',
 '1. REAL DEFECTS FOUND AND PHYSICALLY REPAIRED','']
 for d in st['discoveredDefects']:
  L += [f"{d['id']} — {d['severity']}:",f"- {d['description']}",f"- status: {d['status']}",'']
 L += ['Implementation result:','- Audit snapshot RLS now requires the immutable P84 publication link plus exact owner, snapshot digest, artifact digest and PDF digest.','- Audit PDF blob RLS applies the same publication/digest boundary, closing direct PostgREST orphan-blob visibility in source.','- list/get use SECURITY INVOKER functions; caller supplies no account id and cannot obtain service-role bypass.','- publication visibility is filtered in PostgreSQL before ORDER/LIMIT, eliminating N+1 and hidden-orphan starvation in the route.','- TypeScript parser accepts an exact 14-field row and rejects extra/missing fields, duplicates, out-of-order results, ambiguous get rows and every tested digest/owner tamper.','- durable helper rejects preview:* identities before any RPC call.','',
 '2. CURRENT LOCAL DEFENSIVE PROOF','',f"P85 owner-visible runtime: {rt['checks']['passed']}/{rt['checks']['total']} {rt['status']}",f"P85 repeatability: {rep['checks']['passed']}/{rep['checks']['total']} PASS; receipt/stdout byte-identical",f"P85 migration/customer-path static: {st['checks']['passed']}/{st['checks']['total']} PASS",f"P85/P84 compatibility: {c84['checks']['passed']}/{c84['checks']['total']} PASS",f"P85/P80 compatibility: {c80['checks']['passed']}/{c80['checks']['total']} PASS",'Changed production module imports: 3/3 PASS','Targeted strict TypeScript: PASS','Authorized PostgreSQL/Supabase execution: WITHHELD_NO_SERVER_BINARY_OR_NETWORK_RETRIEVAL','Real service_role/authenticated/anon grants: WITHHELD','Two-owner JWT RLS isolation: WITHHELD','Direct PostgREST orphan denial: WITHHELD','Deployed HTTP/account proof: WITHHELD','',
 'The local mocked-owner-RPC proof validates closed client parsing, one-RPC control flow, no caller account parameter, no direct-table helper reads, fail-closed errors, exact publication-link cross-binding and deterministic output. It does not prove PostgreSQL syntax/execution, RLS policy evaluation, grants, JWT claims, PostgREST behavior, query plans or deployed routes.','',
 '3. CURRENT GREEN RECEIPTS ON P85R1 BYTES','']
 for x in tests['controls']: L.append(f"- {x['label']}: {x['checks']}/{x['checks']} PASS")
 L += ['',f"Aggregate executed checks across overlapping harnesses: {tests['aggregateExecutedChecksAcrossOverlappingHarnesses']}",'IMPORTANT: 1161 is not an independent-evidence count, detector-accuracy statistic, provider count, customer count or FINAL numerator.','',
 'Superseded historical harness boundary:','- the frozen P84 static harness still expects the P84 migration to remain the newest migration; P85 does not relabel that historical ordering assertion as PASS;','- P85/P84 compatibility 34/34 proves the retained P84 write and owner-link guarantees on the new tree;','- P85/P80 compatibility 10/10 replaces five weaker historical route/multi-write assertions while restoring frozen P80 receipts byte-for-byte;','- current P85 module imports and targeted TypeScript replace the P84 current-module lanes.','',
 'Historical receipt immutability:',f"- verified historical files: {hist['verifiedHistoricalFiles']}",f"- mismatches: {hist['mismatchCount']}",'- result: PASS_BYTE_IDENTICAL.','',
 'Recovery integrity:','- an earlier temporary P85 work directory disappeared after a completed rerun; no result from that lost tree was credited;','- P85 was reconstructed from the verified P84 ZIP/tree and the complete stack was rerun on the surviving current tree;','- the final command receipt records 22/22 successful commands and restoration of rewritten historical outputs from the exact P84 parent.','',
 '4. CURRENT PRODUCT SOURCE PROJECTION CANDIDATE','',f"Parent P84R1 product files: {pr['parentProjection']['fileCount']:,}",f"Parent P84R1 payload: {pr['parentProjection']['payloadBytes']:,} B",f"P85R1 product files: {product['fileCount']:,}",f"P85R1 payload: {product['payloadBytes']:,} B",f"Delta files: {pr['delta']['fileCount']:+d}",f"Delta payload: {pr['delta']['payloadBytes']:+,} B",f"Changed build-relevant files: {pr['delta']['changedBuildRelevantFiles']}",f"Path-set SHA-256: {product['pathSetSha256']}",f"Source aggregate SHA-256: {product['sourceContentAggregateSha256']}",'Projection classification: LOCAL_DETERMINISTIC_SOURCE_IDENTITY_ONLY','Exact-Windows credit on P85R1 current bytes: WITHHELD','', 'Build-relevant changes:']
 for x in pr['changedBuildRelevantFiles']: L.append(f"- {x['path']} — {x['change']} — {x['afterBytes']:,} B — {x['afterSha256']}")
 L += ['','Database closure-critical changes outside the historical product projection:','- lib/db/schema.sql','- supabase/migrations/20260820000003_p85_audit_customer_artifact_publication_visibility_rls.sql','',
 '5. TYPE / LINT / ENVIRONMENT TRUTH','',f"Current local Node: {ck['environment']['localNode']}",f"Current local npm: {ck['environment']['localNpm']}",f"Current local TypeScript: {ck['environment']['localTsc']}",f"Platform: {ck['environment']['platform']}",'Targeted strict TypeScript: PASS','Changed production module imports: 3/3 PASS','Whole-project semantic TypeScript: WITHHELD_DEPENDENCY_ENVIRONMENT_MISSING','ESLint: WITHHELD_DEPENDENCY_ENVIRONMENT_MISSING','Webpack/Turbopack: WITHHELD_DEPENDENCY_ENVIRONMENT_MISSING','PostgreSQL/Supabase runtime: WITHHELD_NO_SERVER_BINARY_OR_NETWORK_RETRIEVAL','Exact Windows Server 2025 / Node 24.18.0 / npm 11.16.0: WITHHELD','',
 '6. SECURITY / PRIVACY / SAFETY BOUNDARY','', '- no blockchain transaction, signature or external state change was sent;','- no live exploit, authorization bypass or weaponized PoC was performed;','- no external system was scanned;','- raw Solidity, ABI, runtime bytecode, trace and state remain outside customer objects;','- the full internal Audit message ledger remains service-role-only;','- customer-visible Audit reads require the minimal immutable link and exact cross-binding in source;','- current exploitability remains unproven.','',
 '7. RIGHTS / CURRENTNESS','', 'P85R1 changes no external source license or redistribution decision.','Rights remain 2/203 inherited only.','Current deployment/trusted-forwarder/exploitability currentness remains NOT PROVEN.','No staging account-authorization credit exists until real RLS/JWT/PostgREST execution.','',
 '8. ZERO-FAKE-CREDIT NUMERATORS','', 'Customer FINAL: 0/20','Audit FINAL PDF: 0/3','Rights: 2/203 inherited only','Paid value: 0/10','Sale eligible: 0/20','LIVE: false','Global: NO_GO / STOP_SELL','P85 database-enforced publication visibility source sub-scope: GREEN_BOUNDED','P85 overall: NOT FINAL','',
 '9. NEXT BLOCKER — SHORTEST HONEST PATH','', '1. Apply ordered P83, P84 and P85 migrations on an authorized staging PostgreSQL/Supabase project.','2. Verify publication RPC execution is service-role-only; anon/authenticated publication calls must fail.','3. Use two real owner JWTs and prove own snapshot/PDF/link visibility plus cross-account non-disclosure.','4. Insert owner-bound orphan Audit snapshot/PDF records through authorized fixtures and prove direct PostgREST reads return no row until exact link commit.','5. Create more than 50 newer hidden orphan rows and prove an older valid artifact remains returned because visibility filtering precedes LIMIT.','6. Mutate owner/hash/snapshot/artifact/PDF/link bindings and prove trigger/RLS rejection and complete transaction rollback.','7. Retrieve one published artifact through preview, download and account endpoints and independently compare actual bytes and SHA-256.','8. Separately execute rights-bound current BSC quorum and authorized offline archival replay without live transactions.','9. Run whole-project type/lint/dual-build and exact Windows on the exact successor bytes.','',
 'Only a row satisfying all applicable evidence, rights/currentness, immutable artifact, deployed authorization and exact-runtime gates may move Customer FINAL 0/20 -> 1/20. Audit FINAL PDF may move 0/3 -> 1/3 only for the corresponding independently verified immutable PDF.','',
 '10. CURRENT VERDICT','', 'P85R1 materially strengthens the real Audit customer-delivery boundary:','- an owner can no longer be considered entitled to an unpublished Audit snapshot/PDF merely because the row carries their account binding;','- the immutable publication link becomes part of database visibility in source;','- one owner-scoped RPC replaces N+1 reads and limit-before-filter starvation;','- client parsing fails closed on structural and cryptographic binding inconsistencies.','',
 'The result remains bounded and honest:','- source/static/local mocked-owner-RPC path: green;','- P84 atomic publication/write boundary: byte-frozen and compatible;','- PostgreSQL/RLS/JWT/PostgREST/deployed HTTP: withheld;','- Customer FINAL: 0/20;','- Audit FINAL PDF: 0/3.','',f"Exact parent delta files outside self-generated closure: {src['changeCount']}",'','END OF LEDGER']
 out.parent.mkdir(parents=True,exist_ok=True); out.write_text('\n'.join(L)+'\n',encoding='utf-8'); print(json.dumps({'status':'PASS','output':out.name,'bytes':out.stat().st_size,'sha256':sha(out),'packageSha256':z['sha256']},indent=2))
if __name__=='__main__': main()
