#!/usr/bin/env python3
import hashlib,json,platform
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; MANIFEST=ROOT/'artifacts/closure/p84r1/P84R1_SOURCE_CHANGE_MANIFEST.json'; AGG=ROOT/'artifacts/closure/p84r1/P84R1_TEST_AGGREGATE.json'; M=ROOT/'supabase/migrations/20260820000003_p85_audit_customer_artifact_publication_visibility_rls.sql'; OUT=ROOT/'receipts/p85/P85_P84_OWNER_READ_COMPATIBILITY.json'
FROZEN=['supabase/migrations/20260820000002_p84_audit_customer_artifact_owner_read_path.sql','lib/account/audit-account-messages.ts','lib/reporting/audit-exact-artifact-owner-readable-publisher.ts','scripts/p84/test-p84-audit-customer-artifact-owner-read-runtime.mjs','scripts/p84/test-p84-audit-customer-artifact-owner-read-static.py','scripts/p84/verify-p84-runtime-repeatability.py','receipts/p84/P84_AUDIT_CUSTOMER_ARTIFACT_OWNER_READ_RUNTIME.json','receipts/p84/P84_AUDIT_CUSTOMER_ARTIFACT_OWNER_READ_STATIC.json','receipts/p84/P84_AUDIT_CUSTOMER_ARTIFACT_OWNER_READ_REPEATABILITY.json']
h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest(); checks=[]
def check(i,c,d=None): checks.append({'id':i,'status':'PASS' if c else 'FAIL',**({} if d is None else {'detail':d})})
manifest=json.loads(MANIFEST.read_text()); expected={r['path']:r.get('afterSha256') for r in manifest['changes'] if r.get('afterSha256')}; agg=json.loads(AGG.read_text()); text=M.read_text()
check('p85_p84_manifest_status',manifest.get('status')=='PASS_EXACT_PARENT_DELTA',manifest.get('status')); check('p85_p84_aggregate_status',agg.get('status')=='PASS',agg.get('status'))
for rel in FROZEN:
 p=ROOT/rel; check(f'p85_p84_frozen_exists:{rel}',p.is_file()); check(f'p85_p84_frozen_hash_recorded:{rel}',rel in expected,expected.get(rel));
 if p.is_file() and rel in expected: check(f'p85_p84_frozen_byte_identical:{rel}',h(p)==expected[rel],{'expected':expected[rel],'actual':h(p)})
migs=sorted((ROOT/'supabase/migrations').glob('*.sql')); check('p85_is_latest_ordered_migration',migs[-1].name==M.name,migs[-1].name); check('p84_migration_remains_immediate_parent',migs[-2].name=='20260820000002_p84_audit_customer_artifact_owner_read_path.sql',migs[-2].name); check('p84_historical_latest_migration_assertion_explicitly_superseded','p85' in M.name.lower() and M.name>migs[-2].name)
check('p85_adds_read_boundary_without_replacing_p84_write_boundary','velmere_list_owner_visible_customer_artifacts_v1' in text and 'velmere_get_owner_visible_customer_artifact_v1' in text and 'create or replace function public.velmere_publish_audit_exact_artifact_v2' not in text)
check('p85_p84_customer_final_not_promoted',json.loads((ROOT/'receipts/p84/P84_AUDIT_CUSTOMER_ARTIFACT_OWNER_READ_RUNTIME.json').read_text())['zeroFakeCredit']['customerFinal']=='0/20')
payload={'schemaVersion':'velmere.p85.p84-owner-read-compatibility.v1','status':'PASS' if all(r['status']=='PASS' for r in checks) else 'FAIL','runtime':{'python':platform.python_version()},'frozenFiles':FROZEN,'checks':{'total':len(checks),'passed':sum(r['status']=='PASS' for r in checks),'failed':sum(r['status']=='FAIL' for r in checks),'rows':checks},'supersededHistoricalAssertion':{'assertion':'P84 migration is latest ordered migration','historicalStatus':'VALID_ON_P84R1_BYTES','currentStatus':'EXPECTED_SUPERSEDED_BY_P85_ORDERED_MIGRATION','creditRule':'No P84 receipt is rewritten; P85 current static proof owns the new latest-migration assertion.'},'truthBoundary':'P84 write/publication semantics and historical receipts remain byte-identical. P85 only tightens owner-visible database reads. PostgreSQL, JWT/RLS, deployed HTTP and exact Windows remain WITHHELD.'}
OUT.write_text(json.dumps(payload,indent=2)+'\n'); print(json.dumps(payload,indent=2)); raise SystemExit(0 if payload['status']=='PASS' else 1)
