#!/usr/bin/env python3
import hashlib,json,platform,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; STATIC=ROOT/'receipts/p80/P80_AUDIT_EXACT_IMMUTABLE_ACCOUNT_ARTIFACT_STATIC.json'; RUNTIME=ROOT/'receipts/p80/P80_AUDIT_EXACT_IMMUTABLE_ACCOUNT_ARTIFACT_RUNTIME.json'; M=ROOT/'supabase/migrations/20260820000003_p85_audit_customer_artifact_publication_visibility_rls.sql'; READ=ROOT/'lib/reporting/account-customer-artifact-owner-visible-read.ts'; ROUTE=ROOT/'lib/server/lazy-route-modules/account--customer-artifact.ts'; PUB=ROOT/'lib/reporting/audit-exact-artifact-owner-readable-publisher.ts'; OUT=ROOT/'receipts/p85/P85_P80_IMMUTABLE_ARTIFACT_COMPATIBILITY.json'; LOG=ROOT/'artifacts/p85/logs/P80_STATIC_P85_SUPERSEDED_EXPECTATIONS.log'
EXPECTED={'p80_watch_stores_pdf_bytes_not_metadata_only','p80_watch_orders_store_bind_message','p80_audit_message_link_lookup_owner_and_snapshot_scoped','p80_generic_account_route_hides_unlinked_audit_direct_reads','p80_generic_account_route_hides_unlinked_audit_list_rows'}
original=STATIC.read_bytes()
try:
 result=subprocess.run(['python3','scripts/p80/test-p80-audit-exact-immutable-artifact-static.py'],cwd=ROOT,stdout=subprocess.PIPE,stderr=subprocess.STDOUT); LOG.write_bytes(result.stdout); current=json.loads(STATIC.read_text())
finally: STATIC.write_bytes(original)
rows=current['checks']; failed={r['id'] for r in rows if r['status']=='FAIL'}; runtime=json.loads(RUNTIME.read_text()); m=M.read_text(); read=READ.read_text(); route=ROUTE.read_text(); pub=PUB.read_text(); checks=[]
def check(i,c,d=None): checks.append({'id':i,'status':'PASS' if c else 'FAIL',**({} if d is None else {'detail':d})})
check('p85_p80_legacy_static_fails_only_five_superseded_assertions',result.returncode==1 and failed==EXPECTED,{'returnCode':result.returncode,'failed':sorted(failed)}); check('p85_p80_legacy_static_remaining_98_green',len(rows)==103 and sum(r['status']=='PASS' for r in rows)==98); check('p85_p80_runtime_exact_artifact_67_of_67',runtime['checks']['passed']==67 and runtime['checks']['total']==67)
check('p85_replacement_database_rls_requires_exact_link','p85_customer_artifact_snapshot_owner_published_select' in m and 'p85_customer_artifact_pdf_owner_published_select' in m); check('p85_replacement_filters_before_limit',m.index("and (s.surface <> 'audit' or l.snapshot_id is not null)")<m.index('limit p_limit;')); check('p85_replacement_list_and_get_use_owner_rpc','listP85OwnerVisibleCustomerArtifacts' in route and 'getP85OwnerVisibleCustomerArtifact' in route); check('p85_replacement_has_no_direct_table_read_in_helper','.from(' not in read and read.count('.rpc(')==2); check('p85_replacement_cross_binds_snapshot_artifact_pdf',all(x in read for x in ['link.artifactSnapshotDigest !== snapshot.snapshotDigest','link.artifactDigest !== snapshot.canonicalArtifact.artifactDigest','link.pdfDigest !== snapshot.canonicalArtifact.pdfDigest'])); check('p85_preserves_p84_atomic_single_write_boundary','await supabase.rpc(P84_AUDIT_EXACT_ARTIFACT_OWNER_READABLE_PUBLICATION_RPC' in pub and pub.count('.rpc(')==1); check('p85_restored_historical_p80_static_receipt_byte_for_byte',STATIC.read_bytes()==original,hashlib.sha256(original).hexdigest())
payload={'schemaVersion':'velmere.p85.p80-immutable-artifact-compatibility.v1','status':'PASS' if all(r['status']=='PASS' for r in checks) else 'FAIL','runtime':{'python':platform.python_version()},'legacyHarness':{'status':current.get('status'),'passed':sum(r['status']=='PASS' for r in rows),'total':len(rows),'supersededAssertions':sorted(EXPECTED)},'checks':{'total':len(checks),'passed':sum(r['status']=='PASS' for r in checks),'failed':sum(r['status']=='FAIL' for r in checks),'rows':checks},'truthBoundary':'P80 exact immutable PDF runtime remains green. Five historical static assertions describe pre-P83/P84/P85 plumbing. P85 validates stricter atomic publication plus database-enforced owner visibility without rewriting the frozen P80 receipt.'}
OUT.write_text(json.dumps(payload,indent=2)+'\n'); print(json.dumps(payload,indent=2)); raise SystemExit(0 if payload['status']=='PASS' else 1)
