$ErrorActionPreference='Stop'
function Sha256HexBytes([byte[]]$Bytes){$H=[Security.Cryptography.SHA256]::HashData($Bytes);return([BitConverter]::ToString($H)).Replace('-','').ToLowerInvariant()}
function Sha256HexText([string]$Text){return Sha256HexBytes([Text.Encoding]::UTF8.GetBytes($Text))}
function PostJson([string]$Uri,[hashtable]$Headers,[object]$Body){$Json=$Body|ConvertTo-Json -Depth 40 -Compress;$R=Invoke-WebRequest -Uri $Uri -Method Post -Headers $Headers -ContentType 'application/json' -Body $Json -SkipHttpErrorCheck -TimeoutSec 30;$P=$null;try{$P=$R.Content|ConvertFrom-Json -Depth 50}catch{};return[pscustomobject]@{Status=[int]$R.StatusCode;Body=$P;Raw=[string]$R.Content}}
if(-not$env:ACTIONS_ID_TOKEN_REQUEST_URL-or-not$env:ACTIONS_ID_TOKEN_REQUEST_TOKEN){throw'github_oidc_environment_missing'}
$Sep=if($env:ACTIONS_ID_TOKEN_REQUEST_URL.Contains('?')){'&'}else{'?'}
$Oidc=[string](Invoke-RestMethod -Uri($env:ACTIONS_ID_TOKEN_REQUEST_URL+$Sep+'audience='+[Uri]::EscapeDataString($env:AUDIT_OIDC_AUDIENCE))-Headers@{Authorization='Bearer '+$env:ACTIONS_ID_TOKEN_REQUEST_TOKEN}-TimeoutSec20).value
if(-not$Oidc){throw'oidc_missing'}
$OidcUrl=$env:SUPABASE_URL+'/functions/v1/r7-audit-basic-e2e-oidc';$Bridge=$env:SUPABASE_URL+'/functions/v1/r7-audit-basic-customer-bridge';$Life=$env:SUPABASE_URL+'/functions/v1/r7-audit-basic-lifecycle-bridge';$OH=@{Authorization='Bearer '+$Oidc;Accept='application/json'}
$A=$null;$B=$null;$CaseRef='';$BackupId='';$ReportId=''
try{
 $Prov=PostJson $OidcUrl $OH @{action='provision'};if($Prov.Status-ne200-or$Prov.Body.ok-ne$true){throw('provision_failed:'+$Prov.Raw)};$A=$Prov.Body.a;$B=$Prov.Body.b;$Cap=[string]$Prov.Body.auditServerCapability
 $AH=@{Authorization='Bearer '+[string]$A.accessToken;'x-velmere-audit-server-capability'=$Cap;Accept='application/json'};$BH=@{Authorization='Bearer '+[string]$B.accessToken;'x-velmere-audit-server-capability'=$Cap;Accept='application/json'}
 $Target='0x3333333333333333333333333333333333333333';$TargetHash='sha256:'+(Sha256HexText('velmere-audit-contract-target-v1:56:'+$Target));$Req='audit-life-'+$env:GITHUB_RUN_ID+'-'+$env:GITHUB_RUN_ATTEMPT
 $Create=PostJson $Bridge $AH @{schemaVersion='velmere.r7.audit-basic-customer-bridge-request.v1';action='create_case';caseInput=@{requestId=$Req;targetPrivate=$Target;targetHash=$TargetHash;targetKind='contract';targetChainId='56';targetChainName='BSC';tier='basic';locale='en';status='queued_basic_prescreen';entitlementRequired=$false;entitlementVerified=$false;analysisStarted=$false;accountId=[string]$A.accountId;sourceCandidatesProtected=@{}}};if($Create.Status-ne200-or$Create.Body.ok-ne$true){throw('create_failed:'+$Create.Raw)};$CaseRef=[string]$Create.Body.data.caseRef
 $Claim=PostJson $OidcUrl $OH @{action='claim';caseRef=$CaseRef};if($Claim.Status-ne200-or$Claim.Body.ok-ne$true){throw('claim_failed:'+$Claim.Raw)};$Worker=[string]$Claim.Body.workerPrincipal;$Lease=[string]$Claim.Body.leaseToken
 $Created=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ',[Globalization.CultureInfo]::InvariantCulture);$Pdf=[Text.Encoding]::UTF8.GetBytes('%PDF-1.4'+"`n"+('L'*1800)+"`n%%EOF`n");$PdfDigest='sha256:'+(Sha256HexBytes $Pdf);$PdfLen=$Pdf.Length;$AccountHash=Sha256HexText('velmere-account-binding-v1:'+[string]$A.accountId);$ReportId='audit-life-report-'+$env:GITHUB_RUN_ID+'-'+$env:GITHUB_RUN_ATTEMPT;$Version='sha256:'+(Sha256HexText('ver:'+$CaseRef));$Snap='sha256:'+(Sha256HexText('snap:'+$CaseRef));$Root='sha256:'+(Sha256HexText('root:'+$CaseRef));$Snapshot=@{requestId=$Req;tier='basic';digest=$Snap;sourceReceiptRoot=$Root;generatedAt=$Created;renderContract=@{id='pass4808-deterministic-latin-extended-pagination-v1';pdfDigest=$PdfDigest;pdfByteLength=$PdfLen};auditExecutionRelease=@{expectedTier='basic';caseRef=$CaseRef;decision='ALLOW_COMPLETE';completionAllowed=$true;persistAllowed=$true;packetDigest='sha256:'+(Sha256HexText('pkt:'+$CaseRef));currentDeploymentReceiptDigest='sha256:'+(Sha256HexText('dep:'+$CaseRef));matchedInputDigest='sha256:'+(Sha256HexText('in:'+$CaseRef));releaseBindingDigest='sha256:'+(Sha256HexText('rel:'+$CaseRef))};customerEligibility=@{commercialUseReady=$true}}
 $Mat=@('velmere.audit-basic-exact-immutable-pdf-artifact.v1',$ReportId,$CaseRef,$Req,$AccountHash,$TargetHash,$Version,$Snap,$Root,$PdfDigest,[string]$PdfLen,'pass4808-deterministic-latin-extended-pagination-v1',$Created)-join"`n";$Record='sha256:'+(Sha256HexText $Mat)
 $Complete=PostJson $Bridge $AH @{schemaVersion='velmere.r7.audit-basic-customer-bridge-request.v1';action='complete_pdf';payload=@{caseRef=$CaseRef;workerPrincipal=$Worker;leaseToken=$Lease;reasonCode='worker_result';reportId=$ReportId;requestId=$Req;accountIdHash=$AccountHash;targetHash=$TargetHash;reportVersionHash=$Version;snapshotDigest=$Snap;sourceReceiptRoot=$Root;pdfDigest=$PdfDigest;pdfByteLength=$PdfLen;renderContractId='pass4808-deterministic-latin-extended-pagination-v1';recordDigest=$Record;pdfBase64=[Convert]::ToBase64String($Pdf);snapshotJson=$Snapshot;createdAt=$Created}};if($Complete.Status-ne200-or$Complete.Body.data.state-ne'completed'){throw('complete_failed:'+$Complete.Raw)}
 $Read=PostJson $Bridge $AH @{schemaVersion='velmere.r7.audit-basic-customer-bridge-request.v1';action='read_report';reportId=$ReportId};if($Read.Status-ne200-or$Read.Body.pdfDigest-ne$PdfDigest){throw('prelife_read_failed:'+$Read.Raw)};$BeforeBytes=[Convert]::FromBase64String([string]$Read.Body.pdfBase64);if((Sha256HexBytes $BeforeBytes)-ne$PdfDigest.Replace('sha256:','')){throw'prelife_pdf_sha_mismatch'}
 $BE=PostJson $Life $AH @{schemaVersion='velmere.r7.audit-basic-lifecycle-bridge-request.v1';action='backup_erase_report';reportId=$ReportId};if($BE.Status-ne200-or$BE.Body.data.reportsAfter-ne0){throw('backup_erase_failed:'+$BE.Raw)};$BackupId=[string]$BE.Body.data.backupId
 $Gone=PostJson $Bridge $AH @{schemaVersion='velmere.r7.audit-basic-customer-bridge-request.v1';action='read_report';reportId=$ReportId};if($Gone.Status-ne404){throw('post_erase_visible:'+$Gone.Status)}
 $BCross=PostJson $Life $BH @{schemaVersion='velmere.r7.audit-basic-lifecycle-bridge-request.v1';action='restore_report';backupId=$BackupId};if($BCross.Status-ne404){throw('cross_account_restore_not_denied:'+$BCross.Status)}
 $Restore=PostJson $Life $AH @{schemaVersion='velmere.r7.audit-basic-lifecycle-bridge-request.v1';action='restore_report';backupId=$BackupId};if($Restore.Status-ne200-or$Restore.Body.data.exactPdfRestored-ne$true){throw('restore_failed:'+$Restore.Raw)}
 $Read2=PostJson $Bridge $AH @{schemaVersion='velmere.r7.audit-basic-customer-bridge-request.v1';action='read_report';reportId=$ReportId};if($Read2.Status-ne200){throw('post_restore_read_failed:'+$Read2.Raw)};$After=[Convert]::FromBase64String([string]$Read2.Body.pdfBase64);if((Sha256HexBytes $After)-ne(Sha256HexBytes $BeforeBytes)){throw'post_restore_pdf_not_identical'}
 $BRead=PostJson $Bridge $BH @{schemaVersion='velmere.r7.audit-basic-customer-bridge-request.v1';action='read_report';reportId=$ReportId};if($BRead.Status-ne404){throw('post_restore_cross_read_not_denied:'+$BRead.Status)}
 $Erase2=PostJson $Life $AH @{schemaVersion='velmere.r7.audit-basic-lifecycle-bridge-request.v1';action='backup_erase_report';reportId=$ReportId};if($Erase2.Status-ne200){throw('final_erase_failed:'+$Erase2.Raw)}
 $Purge=PostJson $Life $AH @{schemaVersion='velmere.r7.audit-basic-lifecycle-bridge-request.v1';action='purge_backup';backupId=$BackupId};if($Purge.Status-ne200-or$Purge.Body.data.presentAfter-ne0){throw('purge_failed:'+$Purge.Raw)}
 $Receipt=[ordered]@{schemaVersion='velmere.r7.audit-basic-lifecycle-e2e.v2';status='PASS_BACKUP_ERASE_RESTORE_EXACT_PDF';runId=$env:GITHUB_RUN_ID;runAttempt=$env:GITHUB_RUN_ATTEMPT;caseRef=$CaseRef;reportId=$ReportId;backupId=$BackupId;preEraseExactPdf=$true;eraseRead404=$true;crossAccountRestoreDenied=$true;restoreExactPdf=$true;postRestoreOwnerRead=$true;postRestoreCrossAccountDenied=$true;postRestorePdfByteIdentical=$true;finalReportErased=$true;backupPurged=$true;serviceRoleInWorkflow=$false;customerFinalCredit=$false};New-Item -ItemType Directory -Force -Path 'artifacts/r7/audit-basic/lifecycle'|Out-Null;$Receipt|ConvertTo-Json -Depth20|Set-Content 'artifacts/r7/audit-basic/lifecycle/R7_AUDIT_BASIC_LIFECYCLE_E2E_V2.json' -Encoding utf8;Write-Host($Receipt|ConvertTo-Json -Depth20)
}finally{if($A-and$B-and$Oidc){try{PostJson $OidcUrl $OH @{action='cleanup';userIds=@([string]$A.userId,[string]$B.userId);caseRef=$CaseRef}|Out-Null}catch{Write-Warning $_.Exception.Message}}}
