#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path

def sha(p:Path): return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p:Path): return json.loads(p.read_text(encoding='utf-8'))

def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--root',required=True); ap.add_argument('--zip',required=True); ap.add_argument('--verification',required=True); ap.add_argument('--output',required=True); a=ap.parse_args()
 root=Path(a.root).resolve(); zp=Path(a.zip).resolve(); ver=load(Path(a.verification).resolve()); out=Path(a.output).resolve(); c=root/'artifacts/closure/p86r1'
 ck=load(c/'P86R1_CHECKPOINT_RECEIPT.json'); src=load(c/'P86R1_SOURCE_CHANGE_MANIFEST.json'); pr=load(c/'P86R1_CURRENT_PRODUCT_PROJECTION_MANIFEST.json'); hist=load(c/'P86R1_HISTORICAL_RECEIPT_IMMUTABILITY.json'); tests=load(c/'P86R1_TEST_AGGREGATE.json'); td=load(c/'P86R1_LOCAL_TYPESCRIPT_DIAGNOSTIC.json'); st=load(root/'receipts/p86/P86_EXACT_PDF_FAIL_CLOSED_STATIC.json'); rt=load(root/'receipts/p86/P86_EXACT_PDF_FAIL_CLOSED_RUNTIME.json'); rep=load(root/'receipts/p86/P86_EXACT_PDF_FAIL_CLOSED_REPEATABILITY.json'); compat=load(root/'receipts/p86/P86_P85_COMPATIBILITY.json'); master=load(root/'receipts/p86/P86_MASTER_DIRECTIVE_V2_OWNER_AUTHORITY_BINDING.json')
 z=ver['final']; product=pr['currentCandidateProjection']
 L=[
 'VELMÈRE CURRENT STATE & PASS DELTA LEDGER — P86R1 / V17 + MASTER DIRECTIVE V2',
 'DATE: 2026-08-20',
 'CLASSIFICATION: PASS_BOUNDED_P86R1_ACCOUNT_ARTIFACT_EXACT_PDF_FAIL_CLOSED_NO_RERENDER',
 'GLOBAL: NO_GO / STOP_SELL','LIVE: false','SALE_ENABLED: false','PRODUCTION_APPROVED: false','WORLD_CLASS_PROVEN: false','',
 '0. AUTHORITY AND CANONICAL BINDING','',
 f"Latest explicit owner execution authority: {master['authority']['title']}",
 f"Master binding status: {master['status']}",
 'Master Directive V2 controls closure execution and does not mutate product topology.',
 f"Capture boundary: {master['captureBoundary']['receivedVisibleContentThrough']}; no unseen tail was invented and no fake full-transcript hash is claimed.",
 '',f"Canonical topology directive: {ck['canonicalBinding']['canonicalTopologyDirectiveFile']}",f"SHA-256: {ck['canonicalBinding']['canonicalTopologyDirectiveSha256']}",'Directive changed in P86R1: NO','Current topology remains 10 families / 20 customer rows / 20 profiles / 10 paid transitions.','',
 'Parent checkpoint: P85R1',f"Parent ledger bytes: {ck['canonicalBinding']['parentLedgerBytes']:,}",f"Parent ledger SHA-256: {ck['canonicalBinding']['parentLedgerSha256']}",f"Parent SOURCE_ONLY bytes: {ck['canonicalBinding']['parentSourceOnlyBytes']:,}",f"Parent SOURCE_ONLY entries: {ck['canonicalBinding']['parentSourceOnlyEntries']:,}",f"Parent SOURCE_ONLY SHA-256: {ck['canonicalBinding']['parentSourceOnlySha256']}",'',
 'Current P86R1 SOURCE_ONLY:',zp.name,f"Bytes: {z['bytes']:,}",f"Entries: {z['entryCount']:,}",f"SHA-256: {z['sha256']}",f"Deterministic rebuild: {ver['deterministicRebuild']}",f"ZIP CRC: {z['crc']}",f"Clean unpack: {z['cleanUnpack']}",'ZIP ordering: lexicographic','ZIP timestamp: fixed 1980-01-01T00:00:00Z','Directory entries: 0','ZIP createSystem: 0','Private-key/credential scan: PASS / 0 matches','',
 '1. REAL BLOCKER FOUND AND REPAIRED','',
 'Before P86R1, the common account artifact route could recreate historical Lens/Shield/Real Markets PDFs during download from retained payloads. That meant a deterministic renderer could be mistaken for the immutable customer artifact, while preview had a stricter rule than download.','',
 'P86R1 physically changes this boundary:','- the account endpoint imports no legacy PDF renderer;','- neither preview nor download can rerender a customer PDF;','- only a snapshot carrying the digest-bound exact_immutable_blob marker plus a matching stored blob may be served;','- legacy metadata remains readable for historical compatibility;','- legacy list/detail responses expose pdfAvailability=legacy_exact_bytes_unavailable and both PDF routes are null;','- a direct legacy preview or download returns a non-retryable 409;','- new TypeScript snapshot construction without exact immutable storage is rejected;','- a new ordered PostgreSQL trigger rejects every new non-exact customer artifact row;','- all current Lens, Shield, Real Markets and Audit writers remain bound to exact atomic storage.','',
 '2. CURRENT LOCAL DEFENSIVE PROOF','',
 f"P86 exact-PDF route runtime: {rt['checks']['passed']}/{rt['checks']['total']} {rt['status']}",f"P86 repeatability: {rep['checks']['passed']}/{rep['checks']['total']} PASS; stdout and receipt byte-identical",f"P86 source/migration static: {st['checks']['passed']}/{st['checks']['total']} PASS",f"P86/P85 compatibility: {compat['checks']['passed']}/{compat['checks']['total']} PASS",'Changed production module imports: 3/3 PASS','Targeted strict TypeScript for the new availability authority: PASS','',
 'Executed behavior includes exact preview/download byte identity, new legacy-write rejection, historical legacy metadata compatibility, v3 list/detail availability semantics, both legacy dispositions blocked, cross-account denial and exact stored-byte revalidation.','',
 'Authorized PostgreSQL/Supabase execution of the P86 trigger: WITHHELD','Real service_role/authenticated/anon grants: WITHHELD','Two-owner JWT/RLS/PostgREST: WITHHELD','Deployed preview/download/account bytes: WITHHELD','',
 '3. CURRENT GREEN CONTROLS ON P86R1 BYTES','']
 for x in tests['controls']: L.append(f"- {x['label']}: {x['checks']}/{x['checks']} PASS")
 L += ['',f"Aggregate executed checks across overlapping harnesses: {tests['aggregateExecutedChecksAcrossOverlappingHarnesses']}",'IMPORTANT: 1148 is not an independent-evidence count, detector accuracy, provider count, customer count or FINAL numerator.','',
 'Historical receipt integrity:',f"- verified frozen historical files: {hist['verifiedHistoricalFiles']}",f"- mismatches: {hist['mismatchCount']}",'- result: PASS_BYTE_IDENTICAL.','',
 '4. CURRENT PRODUCT SOURCE PROJECTION CANDIDATE','',f"Parent P85R1 product files: {pr['parentProjection']['fileCount']:,}",f"Parent P85R1 payload: {pr['parentProjection']['payloadBytes']:,} B",f"P86R1 product files: {product['fileCount']:,}",f"P86R1 payload: {product['payloadBytes']:,} B",f"Delta files: {pr['delta']['fileCount']:+d}",f"Delta payload: {pr['delta']['payloadBytes']:+,} B",f"Changed build-relevant files: {pr['delta']['changedBuildRelevantFiles']}",f"Path-set SHA-256: {product['pathSetSha256']}",f"Source aggregate SHA-256: {product['sourceContentAggregateSha256']}",'Projection classification: LOCAL_DETERMINISTIC_SOURCE_IDENTITY_ONLY','Exact-Windows credit on P86R1 current bytes: WITHHELD','','Build-relevant changes:']
 for x in pr['changedBuildRelevantFiles']: L.append(f"- {x['path']} — {x['change']} — {x['afterBytes']:,} B — {x['afterSha256']}")
 L += ['','Database closure-critical changes outside the historical product projection:','- lib/db/schema.sql','- supabase/migrations/20260820000004_p86_customer_artifact_exact_pdf_new_write_gate.sql','',
 '5. TYPE / LINT / ENVIRONMENT TRUTH','',f"Current local Node: {td['environment']['node']}",f"Current local npm: {td['environment']['npm']}",f"Current local TypeScript: {td['environment']['tsc']}",f"Platform: {td['environment']['platform']}",'Targeted strict TypeScript: PASS','Changed production module imports: 3/3 PASS','Whole-project semantic TypeScript: WITHHELD_DEPENDENCY_ENVIRONMENT_MISSING','ESLint: WITHHELD_DEPENDENCY_ENVIRONMENT_MISSING','Webpack/Turbopack: WITHHELD_DEPENDENCY_ENVIRONMENT_MISSING','PostgreSQL/Supabase runtime: WITHHELD_NO_SERVER_BINARY_OR_NETWORK_RETRIEVAL','Exact Windows Server 2025 / Node 24.18.0 / npm 11.16.0: WITHHELD','',
 '6. SECURITY / PRIVACY / SAFETY BOUNDARY','', '- no blockchain transaction, signature or external state change was sent;','- no live exploit, authorization bypass, weaponized PoC or external scan was performed;','- no raw Solidity, ABI, runtime, trace or state was redistributed;','- the route no longer treats retained payload plus renderer as delivered evidence;','- exact marker without blob, blob without marker and digest mismatch all fail closed;','- public response exposes customer-safe availability state rather than internal storage details;','- current exploitability remains unproven.','',
 '7. RIGHTS / CURRENTNESS','', 'P86R1 changes no external data license or redistribution decision.','Rights remain 2/203 inherited only.','Current deployment/trusted-forwarder/exploitability currentness remains NOT PROVEN.','No staging authorization or deployed artifact credit exists.','',
 '8. ZERO-FAKE-CREDIT NUMERATORS','', 'Customer FINAL: 0/20','Audit FINAL PDF: 0/3','Rights: 2/203 inherited only','Paid value: 0/10','Sale eligible: 0/20','LIVE: false','Global: NO_GO / STOP_SELL','P86 exact-PDF no-rerender sub-scope: GREEN_BOUNDED','P86 overall: NOT FINAL','',
 '9. NEXT CONTINUOUS CLOSURE WORK','', 'External-environment blocker:','1. Apply ordered P83–P86 migrations on an authorized staging PostgreSQL/Supabase project.','2. Prove the P86 insert trigger rejects new legacy rows while historical rows remain metadata-readable.','3. Verify service-role-only publication, authenticated owner read, anon denial and two-owner cross-account non-disclosure.','4. Force snapshot/blob/link conflicts and prove complete rollback.','5. Retrieve one published artifact through preview, download and account routes and independently compare actual bytes and SHA-256.','',
 'Independent workstreams that must continue without retry-looping unavailable staging:','6. Audit all remaining product/customer artifact paths for render-on-download, mutable bytes or missing canonical blob identity.','7. Execute rights-bound current BSC quorum and authorized offline archival replay when an authorized environment exists.','8. Continue product-by-product current output, rights/currentness, value, security and holdout closure across the 20 rows.','9. Restore full dependency closure, semantic TypeScript, ESLint, dual build and exact Windows on exact successor bytes.','',
 '10. CURRENT VERDICT','', 'P86R1 removes a material evidence-integrity ambiguity from the shared customer account path. A renderer is no longer accepted as a substitute for the exact delivered PDF. Historical records are not falsified or rewritten; they remain visible as metadata while PDF delivery is explicitly unavailable.','',
 'The result is intentionally bounded:','- local source/static/route proof: green;','- P83–P85 publication and owner-read semantics: preserved;','- PostgreSQL/JWT/RLS/PostgREST/deployed HTTP: withheld;','- Customer FINAL: 0/20;','- Audit FINAL PDF: 0/3.','',f"Exact parent delta files outside self-generated closure: {src['changeCount']}",'','END OF LEDGER']
 out.parent.mkdir(parents=True,exist_ok=True); out.write_text('\n'.join(L)+'\n',encoding='utf-8'); print(json.dumps({'status':'PASS','output':out.name,'bytes':out.stat().st_size,'sha256':sha(out),'packageSha256':z['sha256']},indent=2))
if __name__=='__main__': main()
