import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildCurrentEvidenceAvailabilityMatrix } from '../../../../lib/commerce/vlm-current-evidence-availability-matrix.ts';
const args=process.argv.slice(2); const i=args.indexOf('--output'); if(i<0) throw new Error('missing --output'); const output=resolve(args[i+1]);
const evaluatedAt='2026-08-16T18:30:00.000Z';
const locales=['pl','en','de'];
const matrices=Object.fromEntries(locales.map(locale=>[locale,buildCurrentEvidenceAvailabilityMatrix({locale,evaluatedAt})]));
function canonical(v){ if(v===null||typeof v!=='object')return JSON.stringify(v); if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`; return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`; }
const sha=v=>createHash('sha256').update(Buffer.from(canonical(v))).digest('hex');
const rowSignature=r=>({rowId:r.rowId,family:r.canonicalFamily,tier:r.customerTier,context:r.evaluationContext,receiptHash:r.receipt.receiptHash,availabilityState:r.receipt.availabilityState,analysisEligible:r.receipt.analysisEligible,checkoutEligible:r.receipt.checkoutEligible,saleEligible:r.receipt.saleEligible,valueEligible:r.receipt.valueEligible,historicalEligible:r.receipt.historicalEligible,missingEvidenceIds:r.receipt.missingEvidenceIds,staleEvidenceIds:r.receipt.staleEvidenceIds,conflictedEvidenceIds:r.receipt.conflictedEvidenceIds,unsupportedEvidenceIds:r.receipt.unsupportedEvidenceIds,rightsBlockedEvidenceIds:r.receipt.rightsBlockedEvidenceIds,runtimeBlockedEvidenceIds:r.receipt.runtimeBlockedEvidenceIds,limitationEvidenceIds:r.receipt.limitationEvidenceIds,reasonCodes:r.receipt.reasonCodes});
const profileSignature=p=>({profileId:p.profileId,family:p.canonicalFamily,context:p.context,tier:p.customerTier,receiptHash:p.receipt.receiptHash,availabilityState:p.receipt.availabilityState,analysisEligible:p.receipt.analysisEligible,checkoutEligible:p.receipt.checkoutEligible,saleEligible:p.receipt.saleEligible,missingEvidenceIds:p.receipt.missingEvidenceIds,reasonCodes:p.receipt.reasonCodes});
const baselineRows=matrices.en.customerFacingRows.map(rowSignature); const baselineProfiles=matrices.en.profiles.map(profileSignature);
const localeResults=locales.map(locale=>{ const rows=matrices[locale].customerFacingRows.map(rowSignature); const profiles=matrices[locale].profiles.map(profileSignature); return {locale,rowCount:rows.length,profileCount:profiles.length,rowDecisionAggregateSha256:sha(rows),profileDecisionAggregateSha256:sha(profiles),semanticRowsEqualEnglish:canonical(rows)===canonical(baselineRows),semanticProfilesEqualEnglish:canonical(profiles)===canonical(baselineProfiles),localizedCustomerMessages:matrices[locale].customerFacingRows.map(r=>({rowId:r.rowId,message:r.publicProjection.customerMessage}))}; });
const packet={schemaVersion:'velmere.p67.locale-decision-invariance.v1',generatedAt:'2026-08-16T18:45:00.000Z',evaluatedAt,locales,customerRowsPerLocale:20,profilesPerLocale:20,localeResults,allSemanticRowsInvariant:localeResults.every(x=>x.semanticRowsEqualEnglish),allSemanticProfilesInvariant:localeResults.every(x=>x.semanticProfilesEqualEnglish),allSaleZero:locales.every(l=>matrices[l].saleEligibleCustomerFacingRowCount===0),status:'PASS_P67_PL_EN_DE_DECISION_INVARIANCE_NO_PROMOTION',truthBoundary:'PL/EN/DE public copy may differ, but source/fallback eligibility truth, receipt hashes and release decisions must remain identical. This is decision-layer coverage only and grants no final customer-output, rights, value, sale or LIVE credit.'};
if(!packet.allSemanticRowsInvariant||!packet.allSemanticProfilesInvariant||!packet.allSaleZero) throw new Error('locale invariance failed');
const b=Buffer.from(JSON.stringify(packet,null,2)+'\n'); writeFileSync(output,b); console.log(JSON.stringify({status:packet.status,rows:20,profiles:20,locales:3,sha256:createHash('sha256').update(b).digest('hex')},null,2));
