-- PASS2922 Public Restore Seal / Long-Term Surveillance Handoff Gate
CREATE TABLE IF NOT EXISTS market_integrity_post_graduation_public_restore_seal_gates (
  id text PRIMARY KEY,
  release_candidate text NOT NULL,
  pass integer NOT NULL DEFAULT 2922,
  public_restore_seal_status text NOT NULL DEFAULT 'NO_GO_POST_GRADUATION_PUBLIC_RESTORE_SEAL_REQUIRED',
  long_term_surveillance_handoff_status text NOT NULL DEFAULT 'NO_GO_LONG_TERM_SURVEILLANCE_HANDOFF_REQUIRED',
  public_restore_publication_status text NOT NULL DEFAULT 'NO_GO_PUBLIC_RESTORE_PUBLICATION_REQUIRED',
  pass2921_graduation_seal_digest text,
  public_restore_seal_packet_sha256 text,
  shield_post_graduation_restore_receipt_sha256 text,
  realmarkets_post_graduation_restore_receipt_sha256 text,
  pdf_tier_post_graduation_restore_receipt_sha256 text,
  payment_entitlement_post_graduation_restore_receipt_sha256 text,
  provider_freshness_post_graduation_restore_receipt_sha256 text,
  customer_visible_restore_publication_board_sha256 text,
  long_term_surveillance_handoff_sha256 text,
  restore_expiry_revalidation_schedule_sha256 text,
  append_only_post_graduation_history_sha256 text,
  can_publish_restored_status_without_public_seal boolean NOT NULL DEFAULT false,
  can_show_green_badge_without_long_term_surveillance boolean NOT NULL DEFAULT false,
  can_use_graduation_seal_as_permanent_green_proof boolean NOT NULL DEFAULT false,
  can_rewrite_post_graduation_history boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pass2922_no_restore_without_public_restore_seal CHECK (can_publish_restored_status_without_public_seal = false),
  CONSTRAINT pass2922_no_green_without_long_term_surveillance CHECK (can_show_green_badge_without_long_term_surveillance = false),
  CONSTRAINT pass2922_no_permanent_green_from_graduation_seal CHECK (can_use_graduation_seal_as_permanent_green_proof = false),
  CONSTRAINT pass2922_no_history_rewrite CHECK (can_rewrite_post_graduation_history = false),
  CONSTRAINT pass2922_restore_seal_status_must_no_go CHECK (public_restore_seal_status = 'NO_GO_POST_GRADUATION_PUBLIC_RESTORE_SEAL_REQUIRED'),
  CONSTRAINT pass2922_surveillance_status_must_no_go CHECK (long_term_surveillance_handoff_status = 'NO_GO_LONG_TERM_SURVEILLANCE_HANDOFF_REQUIRED')
);
