#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path

def sha(p:Path):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for c in iter(lambda:f.read(4*1024*1024),b''):h.update(c)
 return h.hexdigest()
def load(p):return json.loads(Path(p).read_text())
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--root',required=True);ap.add_argument('--package-verification',required=True);ap.add_argument('--output',required=True);a=ap.parse_args()
 root=Path(a.root);out=Path(a.output);pv=load(a.package_verification);cl=root/'artifacts/closure/p90r1'
 source=load(cl/'P90R1_SOURCE_CHANGE_MANIFEST.json');product=load(cl/'P90R1_CURRENT_PRODUCT_PROJECTION_MANIFEST.json');tests=load(cl/'P90R1_TEST_AGGREGATE.json');hist=load(cl/'P90R1_HISTORICAL_RECEIPT_IMMUTABILITY.json');fail=load(cl/'P90R1_FAILURE_ADJUDICATION.json');rights=load(cl/'P90R1_PROVIDER_RIGHTS_CURRENTNESS_BOUNDARY.json');block=load(cl/'P90R1_CURRENT_BLOCKER_QUEUE.json');authority=load(cl/'P90R1_AUTHORITY_BINDING.json');ts=load(cl/'P90R1_LOCAL_TYPESCRIPT_DIAGNOSTIC.json');final=pv['final']
 lines=[];A=lines.append
 A('VELMÈRE CURRENT STATE & PASS DELTA LEDGER — P90R1 / V17')
 A('DATE: 2026-08-20')
 A('CLASSIFICATION: PASS_BOUNDED_P90R1_AUDIT_FIELD_LEVEL_RIGHTS_CURRENTNESS_AND_CUSTOMER_FAIL_CLOSED')
 A('GLOBAL: NO_GO / STOP_SELL')
 A('LIVE: false')
 A('SALE_ENABLED: false')
 A('PRODUCTION_APPROVED: false')
 A('WORLD_CLASS_PROVEN: false')
 A('')
 A('0. CANONICAL BINDING')
 A(f"Master Directive V2: {authority['masterDirective']['path']}")
 A(f"Master SHA-256: {authority['masterDirective']['sha256']}")
 A('Master completeness: SECTIONS 0–88 PRESENT; START NOW and END-OF-DIRECTIVE sentinel present.')
 A(f"Canonical Owner Directive: {authority['canonicalOwnerDirective']['path']}")
 A(f"V17 SHA-256: {authority['canonicalOwnerDirective']['sha256']}")
 A('Master/V17 changed in P90R1: NO / NO')
 A('Topology remains 10 families / 20 customer rows / 20 execution profiles / 10 material paid transitions.')
 A(f"Parent SOURCE_ONLY: {source['parentSourceOnly']}")
 A(f"Parent SOURCE_ONLY SHA-256: {source['parentSourceOnlySha256']}")
 A('')
 A('1. REAL SOURCE DELTA')
 A(f"Exact parent delta files: {source['changeCount']}")
 A(f"Build-relevant product files changed: {len(source['buildRelevantChangedFiles'])}")
 for path in source['buildRelevantChangedFiles']:A(f'- {path}')
 A('')
 A('P90 physically adds a versioned field-level provider rights/currentness registry and evaluator, a minimal no-socket Sourcify verification lane, target-relevant successful-execution accounting, customer-safe blocked Audit projection/payload, and the same rights decision in Basic/Pro/Advanced PDF contracts.')
 A('')
 A('2. MATERIAL DEFECTS FOUND AND REPAIRED')
 A('- Technical evidence readiness could progress without field-level commercial/display/PDF/retention rights/currentness. Paid checkout/delivery and Basic customer output now fail closed on the separate rights gate.')
 A('- HTTP success could be overinterpreted as useful execution. Current evidence dimensions require target-relevant liveExecutionEligible=true and deduplicate by canonical provider identity.')
 A('- A blocked pipeline object retained provider-derived riskScore=97 even though known outer handlers blocked delivery. P90 now returns a dedicated blocked schema with riskScore=null, WITHHELD labels and empty findings/pages/receipts.')
 A('- Basic PDF initially carried a Pro rights summary. Tier-specific Basic/Pro/Advanced summaries are now bound independently; the first FAIL remains preserved.')
 A('- Report route and customer pipeline referenced a nonexistent readiness.requirements property. They now consume the actual versioned minimum contract.')
 A('- Blocked route responses now expose only customer-safe public availability; internal provider topology and detailed readiness remain internal.')
 A('')
 A('3. RIGHTS / CURRENTNESS TRUTH')
 A(f"Registry SHA-256: {rights['registrySha256']}")
 A(f"Provider decision rows: {rights['providerDecisionRows']}")
 A('Canonical customer-approved providers: 0')
 A('Canonical paid-approved providers: 0')
 A('Canonical PDF-export-approved providers: 0')
 A('Raw provider terms stored in SOURCE_ONLY: false')
 A('Raw terms-document hash availability: false')
 A('Rights numerator remains 2/203 inherited only; P90 grants zero new rights credit.')
 A('Synthetic approved registry cases are local positive controls only and cannot authorize customer or commercial use.')
 A('')
 A('4. SOURCIFY MINIMAL LANE BOUNDARY')
 A(f"Local full no-socket runtime/control checks: {rights['sourcify']['checks']}/{rights['sourcify']['checks']} PASS")
 A('The lane requests only a minimal chain/address verification object in the controlled harness. Exact target identity may earn strict plus live credit; a target-bound non-exact result may earn live-only credit; wrong identity, raw-sensitive fields, 404 and target-irrelevant HTTP success earn zero credit.')
 A('Real network execution: NOT PERFORMED. Provider rights approval: NOT GRANTED. Raw source/ABI acquisition: NOT PERFORMED.')
 A('')
 A('5. CURRENT TEST EVIDENCE')
 A(f"P90 core bounded checks: {tests['p90Core']['checks']}/{tests['p90Core']['checks']} PASS")
 for key,value in tests['p90Core']['rows'].items():A(f'- {key}: {value}')
 A(f"Segment B: {tests['segmentB']['commands']}/15 commands, {tests['segmentB']['checks']} overlapping checks PASS")
 A(f"Cross-workstream: {tests['crossWorkstream']['commands']}/7 commands, {tests['crossWorkstream']['checks']} overlapping checks PASS")
 A(f"Aggregate current execution: {tests['aggregateExecutedChecksAcrossOverlappingHarnesses']}/{tests['aggregateExecutedChecksAcrossOverlappingHarnesses']} PASS")
 A(f"Preserved first FAIL/test-defect/orchestration logs: {fail['firstFailureCount']}; superseded P89 harnesses with zero credit: {fail['supersededHarnessCount']}.")
 A(f"IMPORTANT: {tests['aggregateExecutedChecksAcrossOverlappingHarnesses']} is an overlapping execution count. It is not independent evidence, detector accuracy, provider count, customer count, Customer FINAL or Audit FINAL PDF.")
 A('')
 A('6. SOURCE / PRODUCT IDENTITY')
 p=product['parentProjection'];c=product['currentCandidateProjection'];d=product['delta']
 A(f"Parent product projection: {p['fileCount']} files / {p['payloadBytes']} B / aggregate {p['sourceContentAggregateSha256']}")
 A(f"P90 product projection: {c['fileCount']} files / {c['payloadBytes']} B")
 A(f"P90 path-set SHA-256: {c['pathSetSha256']}")
 A(f"P90 source aggregate SHA-256: {c['sourceContentAggregateSha256']}")
 A(f"Delta: files {d['fileCount']:+d}; payload {d['payloadBytes']:+d} B; changed build-relevant files {d['changedBuildRelevantFiles']}")
 A('Projection classification: LOCAL_DETERMINISTIC_SOURCE_IDENTITY_ONLY. Exact-Windows credit: WITHHELD.')
 A(f"Historical parent receipt/artifact files verified byte-identical: {hist['verifiedHistoricalReceiptArtifactFiles']}; mismatch count: {hist['mismatchCount']}")
 A('')
 A('7. TYPE / LINT / BUILD / ENVIRONMENT')
 A('Local: Node v22.16.0 / npm 10.9.2 / TypeScript 5.8.3 / Linux x64.')
 A('Targeted strict TypeScript for the P90 evidence-dimensions and rights/currentness cores: PASS 2/2.')
 A('Changed production module imports: PASS 13/13.')
 A(f"Whole-project semantic TypeScript: {ts['wholeProjectSemanticTypeScript']}")
 A(f"ESLint: {ts['eslint']}")
 A(f"Webpack: {ts['webpack']}")
 A(f"Turbopack: {ts['turbopack']}")
 A(f"Exact Windows Server 2025: {ts['exactWindowsServer2025']}")
 A('No prior exact-Windows/full-build result is inherited to changed P90 bytes.')
 A('')
 A('8. ZERO-FAKE-CREDIT NUMERATORS')
 A('Customer FINAL remains 0/20')
 A('Audit FINAL PDF remains 0/3')
 A('Rights remains 2/203 inherited only')
 A('Paid value remains 0/10')
 A('Sale eligible remains 0/20')
 A('PILOT_READY: false')
 A('GO_PAID: false')
 A('LIVE: false')
 A('WORLD_CLASS_PROVEN: false')
 A('Global: NO_GO / STOP_SELL')
 A('')
 A('9. DETERMINISTIC SOURCE_ONLY')
 A(f"Output: {pv['output']}")
 A(f"Entries: {final['entryCount']}")
 A(f"Bytes: {final['bytes']}")
 A(f"SHA-256: {final['sha256']}")
 A('Deterministic rebuild: 2/2 BYTE_IDENTICAL')
 A('CRC: PASS for both builds')
 A('Clean unpack: PASS_PATH_AND_CONTENT_IDENTITY')
 A('Ordering: lexicographic; timestamp: 1980-01-01T00:00:00Z; directory entries: 0; createSystem: 0.')
 A('Full private-key/credential scan: 0 matches. Current P90 unexpected binary scan: 0 matches.')
 A('')
 A('10. CURRENT BLOCKER QUEUE')
 for r in block['rows']:A(f"{r['priority']}. {r['id']} — {r['category']} — {r['state']} — {r['nextSafeAction']}")
 A('')
 A('11. CURRENT VERDICT')
 A('P90R1 is PASS_BOUNDED for local field-level rights/currentness enforcement, target-relevant execution accounting, customer-safe blocked projection/payload, no-socket Sourcify parsing, rights-bound PDF schema and final-byte regression.')
 A('It is not a provider-rights approval, deployed proof, customer audit, sale authorization or FINAL.')
 A('Customer FINAL remains 0/20. Audit FINAL PDF remains 0/3. Global remains NO_GO / STOP_SELL.')
 A('END OF LEDGER')
 out.parent.mkdir(parents=True,exist_ok=True);out.write_text('\n'.join(lines)+'\n',encoding='utf-8')
 print(json.dumps({'status':'PASS','output':str(out),'bytes':out.stat().st_size,'sha256':sha(out),'package':final},indent=2))
if __name__=='__main__':main()
