#!/usr/bin/env python3
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
checks=[]
def check(i,c,d=None):
 checks.append({'id':i,'status':'PASS' if c else 'FAIL',**({} if d is None else {'detail':d})})
 if not c: raise RuntimeError(f'{i}:{d}')
def text(p): return (ROOT/p).read_text()
registry=json.loads(text('config/p90/audit-provider-field-rights-currentness-registry.json'))
rights=text('lib/security/audit-provider-rights-currentness.ts')
readiness=text('lib/security/audit-paid-evidence-readiness.ts')
handler=text('lib/security/audit-watch-post-handler.ts')
pipeline=text('lib/security/audit-customer-report-pipeline.ts')
projection=text('lib/security/audit-report-customer-projection.ts')
runtime=text('lib/security/audit-provider-runtime-client.ts')
dimensions=text('lib/security/audit-provider-evidence-dimensions.ts')
renderer=text('lib/security/pro-audit-pdf/render-pro-audit-pdf.ts')
broker=text('lib/network/brokered-egress.ts')
check('registry_schema',registry['schemaVersion']=='velmere.p90.audit-provider-field-rights-currentness-registry.v1')
check('registry_six_unique_providers',len(registry['providers'])==6 and len({p['providerId'] for p in registry['providers']})==6)
check('canonical_rights_all_fail_closed',all(p['legalApprovalStatus']!='APPROVED' and all(v is False for k,v in p['rights'].items() if k!='internalDiagnosticAllowed') for p in registry['providers']))
check('raw_terms_not_packaged',registry['rawTermsStoredInSource'] is False and registry['rawTermsDocumentHashAvailable'] is False)
check('readiness_has_separate_technical_and_commercial',all(x in readiness for x in ['technicalBlockers','commercialBlockers','technicalMet','commercialMet']))
check('handler_evaluates_rights_before_checkout',handler.find('pass4826AuditPaidEvidenceReadiness') < handler.find('requestedReadinessTier'))
check('handler_blocks_before_artifact_render',handler.find('canonicalCustomerPipeline.releaseState === "blocked"') < handler.find('const renderedCanonicalAuditPdf'))
check('handler_block_response_customer_safe', 'availability: canonicalCustomerPipeline.publicAvailability' in handler and 'providerRightsCurrentness:' not in handler[handler.find('if (canonicalCustomerPipeline.releaseState === "blocked")'):handler.find('const unboundCanonicalCustomerSnapshot')])
check('pipeline_filters_rights_current_lanes','selectedRightsProviderIds' in pipeline and 'customerEligibleLanes' in pipeline)
check('pipeline_blocks_before_customer_payload', pipeline.find('if (!readinessInternal.basic.commercialMet)') < pipeline.find('const payload = buildCustomerReportPayload'))
check('blocked_pipeline_returns_public_availability_only', all(fragment in pipeline for fragment in ['buildBlockedPipelineResult','customerReportPreviewLayout: null','providerAvailabilityDigest']) and 'technical provider topology and provider-derived audit facts remain internal' in pipeline.lower())
check('blocked_customer_report_zeroes_score_and_evidence', all(fragment in pipeline for fragment in ['riskScore: null','pages: [] as const','decisionSections: [] as const','receipts: [] as const','providerConflicts: [] as const']))
check('pipeline_has_defense_in_depth_blocked_projection','projectBlockedAuditReportForCustomer' in pipeline and 'rights/currentness blocking removes scores' in projection.lower())
check('blocked_projection_removes_findings',all(x in projection for x in ['topFindings: []','proPdfLines: []','sections: []','riskScore: null']))
check('timestamp_provenance_not_relabelled','sourceProvenance === "provider"' in pipeline and 'provider_timestamp_not_source_bound' in pipeline)
check('sourcify_host_allowlisted','sourcify.dev' in broker)
check('sourcify_minimal_path','/server/v2/contract/' in runtime and 'fields=all' not in runtime)
check('sourcify_raw_sensitive_fail_closed','raw_sensitive_fields_present' in runtime and 'parsePass4827SourcifyLookupResponse' in runtime)
check('current_evidence_dimension_versioned', 'pass4830-audit-provider-evidence-dimensions-v2' in dimensions and 'P89_PASS4809_AUDIT_PROVIDER_EVIDENCE_DIMENSIONS_ID' in dimensions)
check('target_irrelevant_http_success_rejected', 'lane.liveExecutionEligible !== false' in dimensions and 'explicitLiveExecutionIneligibleLanesRejected' in dimensions)
check('runtime_emits_live_execution_eligibility', 'liveExecutionEligible: boolean' in runtime and runtime.count('liveExecutionEligible: Boolean(') >= 6)
check('duplicate_successful_provider_blocks_commercial', 'duplicate_successful_provider_contributor' in rights and 'duplicateSuccessfulProviderIds.length === 0' in rights)
check('public_availability_has_no_topology_counts', 'buildPublicAuditProviderAvailability' in rights and 'PASS4830_AUDIT_PROVIDER_PUBLIC_AVAILABILITY_SCHEMA' in rights)
check('sourcify_no_state_change_methods',not re.search(r'eth_send|eth_sign|personal_sign|debug_trace|trace_replay',runtime,re.I))
check('renderer_binds_rights_root','providerRightsCurrentnessRoot' in renderer and 'customerEligibility' in renderer)
check('renderer_evaluates_all_three_tiers_separately',all(fragment in renderer for fragment in ['tier: "basic"','tier: "pro"','tier: "advanced"','basicPaidReadiness.rightsCurrentness']))
check('renderer_validates_summary_tier_matches_pdf','parsed.tier !== tier' in renderer)
check('renderer_binds_independence_counts','Eligible provider independence:' in renderer)
check('renderer_customer_lines_no_provider_urls','source.url' not in renderer and 'requiredPlanOrConsent' not in renderer)
assembler=text('lib/server/security-route-modules/audit-report-assembler.ts')
check('report_route_uses_actual_minimum_contract','requirements: evidenceReadinessInternal.minimum' in assembler and 'evidenceReadinessInternal.requirements' not in assembler)
check('pipeline_uses_actual_minimum_contract',all(fragment in pipeline for fragment in ['requirements: readinessInternal.basic.minimum','requirements: readinessInternal.pro.minimum','requirements: readinessInternal.advanced.minimum']) and '.requirements,' not in pipeline)
check('blocked_handler_uses_public_availability','customerReport.runtimeCanonicalValues' not in handler and 'canonicalCustomerPipeline.publicAvailability' in handler)
blocked_assembler_segment=assembler[assembler.find('if (customerPipeline.releaseState === \"blocked\")'):assembler.find('return NextResponse.json({\n    ok: true',assembler.find('if (customerPipeline.releaseState === \"blocked\")'))]
check('blocked_report_route_uses_public_availability','availability: customerPipeline.publicAvailability' in blocked_assembler_segment and 'auditTierReadiness: customerPipeline.readiness' not in blocked_assembler_segment)
check('pipeline_uses_dedicated_blocked_customer_schema','velmere.p90.audit-customer-report-blocked.v1' in pipeline and 'buildBlockedCustomerReport' in pipeline)
check('blocked_customer_payload_withholds_risk','riskScore: null' in pipeline and 'riskLabel: "WITHHELD"' in pipeline and 'decisionSections: [] as const' in pipeline and 'receipts: [] as const' in pipeline)
check('blocked_pipeline_returns_before_customer_payload_build',pipeline.find('if (!readinessInternal.basic.commercialMet)') < pipeline.find('const payload = buildCustomerReportPayload'))
check('blocked_pipeline_digest_bound','customerReportDigest: sha256Digest(canonicalJson(unsigned))' in pipeline and 'pipelineDigest: sha256Digest(canonicalJson(unsigned))' in pipeline)
failed=[x for x in checks if x['status']!='PASS']
receipt={'schemaVersion':'velmere.p90.audit-commercial-path-static.v2','generatedAt':'2026-08-20T12:00:00.000Z','status':'PASS' if not failed else 'FAIL','checks':{'total':len(checks),'passed':len(checks)-len(failed),'failed':len(failed),'rows':checks},'truthBoundary':'Static path proof only; no provider network, legal approval, staging, deployed HTTP or exact-Windows execution is inferred.'}
(ROOT/'receipts/p90').mkdir(parents=True,exist_ok=True)
(ROOT/'receipts/p90/P90_AUDIT_COMMERCIAL_PATH_STATIC.json').write_text(json.dumps(receipt,indent=2)+'\n')
print(json.dumps({'status':receipt['status'],'checks':receipt['checks']},indent=2))
