#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--root',default=str(ROOT));ap.add_argument('--output',required=True);a=ap.parse_args();root=Path(a.root).resolve();out=Path(a.output).resolve();pol=json.load(open(root/'config/p42/p42-exact-windows-semantic-dual-build-policy.json'));wf=(root/'.github/workflows/p42-exact-windows-semantic-dual-build.yml').read_text();runner=(root/'scripts/pass42/run-p42-exact-windows-semantic-dual-build.mjs').read_text();dep=json.load(open(root/'artifacts/closure/p42/P42_EXACT_WINDOWS_DEPENDENCY_INGEST_VERIFICATION.json'))
 checks={'dependencyPass':dep.get('status')=='PASS','packageHash':sha(root/'package.json')==pol['currentRootBindings']['packageJson']['sha256'],'lockHash':sha(root/'package-lock.json')==pol['currentRootBindings']['packageLock']['sha256'],'windows2025':bool(re.search(r'runs-on:\s*windows-2025',wf)),'nodeExact':'node-version: 24.18.0' in wf,'npmExact':'npm@11.16.0' in wf,'readOnly':bool(re.search(r'permissions:\s*\n\s+contents:\s*read',wf)),'noPersistedCredentials':'persist-credentials: false' in wf,'alwaysUpload':'if: always()' in wf,'currentRootRunner':'scripts/pass42/run-p42-exact-windows-semantic-dual-build.mjs' in wf,'noEmbeddedPayload':all(t not in wf+runner for t in ['payload.part-','brotliDecompressSync','package.full.part']),'checkpoint':'const checkpoint=' in runner,'failureReceipt':'const fail=' in runner,'selfTest':'--self-test' in runner,'simulatedFailure':'--simulate-failure' in runner,'allCommands':all(k in pol['commands'] for k in ['trustedNative','typecheck','lint','webpack','turbopack'])}
 status='PASS' if all(checks.values()) else 'FAIL';res={'schemaVersion':'velmere.p42.semantic-dual-build-bridge-verification.v1','revision':pol['revision'],'generatedAt':'2026-08-14T10:26:00.000Z','status':status,'checks':checks,'workflowSha256':sha(root/'.github/workflows/p42-exact-windows-semantic-dual-build.yml'),'runnerSha256':sha(root/'scripts/pass42/run-p42-exact-windows-semantic-dual-build.mjs'),'classification':'PORTABLE_CURRENT_ROOT_EXACT_WINDOWS_SEMANTIC_DUAL_BUILD_BRIDGE_VERIFIED' if status=='PASS' else 'BRIDGE_FAIL','creditBoundary':'Static/portable bridge verification only; no native execution or build credit.'};res['integritySha256']=hashlib.sha256(json.dumps(res,sort_keys=True,separators=(',',':')).encode()).hexdigest();out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(res,indent=2)+'\n');print(json.dumps({'status':status,'output':str(out)}));return 0 if status=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
